<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thème 7: Analyse de survie</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/clipboard/clipboard.min.js"></script>
<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/quarto.js"></script>
<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/popper.min.js"></script>
<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/anchor.min.js"></script>
<link href="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LIVRABLE_T7-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="LIVRABLE_T7-DESKTOP-OQF5J47_files/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#contexte-dapplication" id="toc-contexte-dapplication" class="nav-link" data-scroll-target="#contexte-dapplication">Contexte d’application</a></li>
  <li><a href="#cadre-général-danalyse" id="toc-cadre-général-danalyse" class="nav-link" data-scroll-target="#cadre-général-danalyse">Cadre général d’analyse</a></li>
  <li><a href="#pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" id="toc-pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" class="nav-link" data-scroll-target="#pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas">Pourquoi l’approche de régression linéaire ne fonctionne pas?</a></li>
  <li><a href="#mise-en-contexte" id="toc-mise-en-contexte" class="nav-link" data-scroll-target="#mise-en-contexte">Mise en contexte</a></li>
  <li><a href="#quelques-statistiques-descriptives" id="toc-quelques-statistiques-descriptives" class="nav-link" data-scroll-target="#quelques-statistiques-descriptives">Quelques statistiques descriptives</a></li>
  <li><a href="#analyse-de-survie" id="toc-analyse-de-survie" class="nav-link" data-scroll-target="#analyse-de-survie">Analyse de survie</a></li>
  <li><a href="#les-fonctions-utiles-en-analyse-de-survie" id="toc-les-fonctions-utiles-en-analyse-de-survie" class="nav-link" data-scroll-target="#les-fonctions-utiles-en-analyse-de-survie">Les fonctions utiles en analyse de survie</a></li>
  <li><a href="#les-fonctions-utiles-en-analyse-de-survie-1" id="toc-les-fonctions-utiles-en-analyse-de-survie-1" class="nav-link" data-scroll-target="#les-fonctions-utiles-en-analyse-de-survie-1">Les fonctions utiles en analyse de survie</a></li>
  <li><a href="#méthodes-destimation-non-paramétriques" id="toc-méthodes-destimation-non-paramétriques" class="nav-link" data-scroll-target="#méthodes-destimation-non-paramétriques">Méthodes d’estimation non paramétriques</a>
  <ul class="collapse">
  <li><a href="#estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" id="toc-estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" class="nav-link" data-scroll-target="#estimation-de-la-fonction-de-survie-lapproche-non-paramétrique">Estimation de la fonction de survie: l’approche non paramétrique</a></li>
  </ul></li>
  <li><a href="#lestimateur-de-kaplan-meier-km" id="toc-lestimateur-de-kaplan-meier-km" class="nav-link" data-scroll-target="#lestimateur-de-kaplan-meier-km">L’estimateur de Kaplan-Meier (KM)</a></li>
  <li><a href="#méthode-destimation-semi-paramétrique-modèle-de-cox" id="toc-méthode-destimation-semi-paramétrique-modèle-de-cox" class="nav-link" data-scroll-target="#méthode-destimation-semi-paramétrique-modèle-de-cox">Méthode d’estimation semi-paramétrique: Modèle de Cox</a>
  <ul class="collapse">
  <li><a href="#introduction-au-modèle-de-cox" id="toc-introduction-au-modèle-de-cox" class="nav-link" data-scroll-target="#introduction-au-modèle-de-cox">Introduction au modèle de COX</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thème 7: Analyse de survie</h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>L’analyse de survie est une branche de la statistique qui étudie le <strong>Temps qu’une unité statistique</strong> (individu, machine, entreprise, un employé, une franchise…) passe dans un état donné. L’analyse de survie doit son nom à ses premières applications concernant l’analyse de la durée de vie des individus en épidémiologie et en médecine (patients, malades…). L’analyse de survie s’applique de nos jours à presque tous les domaines: marketing, finance, comptabilité, économie, ingénierie…</p>
<p><strong><code>Exemples</code></strong></p>
<ul>
<li><p>Temps qu’un client reste abonné à un service offert par une entreprise (avant résiliation du contrat)</p></li>
<li><p>Temps qu’un employé au service de l’entreprise (avant licenciement ou avant de quitter l’emploi)</p></li>
<li><p>Temps qu’une entreprise demeure en opération sur le marché (avant de faire faillite)</p></li>
<li><p>Temps qu’un client demeure solvable (avant de déclarer faillite)</p></li>
<li><p>Temps qu’une machine demeure fonctionnelle (avant de tomber en panne)</p></li>
<li><p>Temps qu’une économie reste en croissance (avant la récession ou un crash boursier)</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'survival' a été compilé avec la version R 4.4.3</code></pre>
</div>
</div></li>
</ul>
</section>
<section id="contexte-dapplication" class="level3">
<h3 class="anchored" data-anchor-id="contexte-dapplication">Contexte d’application</h3>
<p>L’analyse de survie est utilisée pour les données longitudinales qui rapportent (relatent) l’occurrence ou l’apparition d’un événement.</p>
<p><strong>Qu’est ce qu’un événement?</strong></p>
<p>Un événement est un changement qualitatif ou quantitatif qui survient dans le temps.</p>
<p><strong>Qualitatif:</strong></p>
<p>Changement d’un statut: faillite, divorce, mariage, le fait d’avoir un enfant, l’interruption d’un contrat, promotion…</p>
<p><strong>Quantitatif:</strong></p>
<p>Un changement soudain et significatif (plus important que les variations observées habituellement):</p>
<p>-Crash boursier définit par une baisse de plus de 20% des indices boursiers.</p>
<p>-Un enrichissement: une augmentation de plus de 50% du revenu. Dans ce cas la définition de l’événement est très arbitraire.</p>
</section>
<section id="cadre-général-danalyse" class="level3">
<h3 class="anchored" data-anchor-id="cadre-général-danalyse">Cadre général d’analyse</h3>
<p>On s’intéresse au TEMPS qu’un individu passe dans un état donné. On observe chaque individu à partir du moment où il entre dans l’état jusqu’à ce que l’une des deux situations suivantes survient:</p>
<ul>
<li><p>L’individu quitte l’état avant la fin de l’observation ( exemple: entreprise fait faillite)</p></li>
<li><p>L’étude se termine et l’individu est toujours dans l’état (exemple: entreprise encore en opération)</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>NB :</strong> Le début de l’état n’est pas nécessairement le même pour chaque individu, mais il faut s’assurer que les critères utilisés pour définir le début et la fin d’un état soient les mêmes pour tous.</p>
<p><strong>Exemple :</strong> Si on étudie la durée de vie des entreprises avant la faillite, il faut définir à quel moment une entreprise <em>naît</em> et à quel moment elle <em>meurt</em> (lorsqu’elle déclare faillite ou lorsque la faillite est approuvée légalement ?).</p>
</div>
</div>
<p>On notera par Temps, la variable «temps de survie» dans l’état. Pour chaque individu, la variable «Temps» est soit non censurée ou censurée.</p>
<p><strong>Le temps est non censuré</strong>: si l’individu a quitté l’état avant la fin de l’observation. Dans ce cas, on observele vrai temps passé dans l’état.</p>
<p><strong>Le temps est censuré</strong>: si l’individu est toujours dans l’état à la fin de l’observation. Dans ce cas, on n’observe qu’une borne inférieure du temps passé dans l’état. On notera par Censure, la variable qui indique si temps est censuré ou non.</p>
</section>
<section id="pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" class="level3">
<h3 class="anchored" data-anchor-id="pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas">Pourquoi l’approche de régression linéaire ne fonctionne pas?</h3>
<ul>
<li><p>Bien que la variable «Temps de survie» soit quantitative, le modèle de régression linéaire n’est pas adéquat pour comprendre les facteurs qui influencent le temps de survie des clients.</p></li>
<li><p>Le problème vient du fait que nous n’observons qu’une borne inférieure du temps de survie des données censurées.</p></li>
<li><p>Éliminer ces observations (les données censurées) de l’échantillon biaiserait le résultat et sous-estimerait le temps de survie des clients.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mise-en-contexte" class="level3">
<h3 class="anchored" data-anchor-id="mise-en-contexte">Mise en contexte</h3>
<p>Netflix s’intéresse aux facteurs influençant le temps qu’un client reste abonné à son service de vidéos en ligne et en streaming. Les données d’un échantillon de 500 clients se trouvent dans le fichier «Netflix.sav». Certains clients sont encore abonnés et d’autres ont déjà quitté.</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Temps</td>
<td style="text-align: left;">Durée en semaines de l’abonnement. Temps réel si le client a quitté, temps censuré sinon.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Censure</td>
<td style="text-align: left;">Indique si l’observation est censurée (1 = client encore abonné, 0 = client a quitté).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">Âge du client au début de l’abonnement.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sexe</td>
<td style="text-align: left;">Sexe du client (0 = Homme, 1 = Femme).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Région</td>
<td style="text-align: left;">Région de résidence actuelle du client (valeurs possibles : 1 à 5).</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail où se trouve le fichier de données</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Importer le jeu de données</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>netflix <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Netflix.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reconvertir les variables</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>censure <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(netflix<span class="sc">$</span>censure)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>sexe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(netflix<span class="sc">$</span>sexe)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(netflix<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="quelques-statistiques-descriptives" class="level3">
<h3 class="anchored" data-anchor-id="quelques-statistiques-descriptives">Quelques statistiques descriptives</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package dplyr</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives de la variable Temps en fonction de la variable Censure </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>stat_descriptive_temps <span class="ot">&lt;-</span> netflix <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(censure) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mediane =</span> <span class="fu">round</span>(<span class="fu">median</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_type =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>stat_descriptive_temps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  censure     N Moyenne Mediane Ecart_type Minimum Maximum
    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;
1       0   334    96.2      98       33.8       2     216
2       1   166   131.      142       41.4      43     203</code></pre>
</div>
</div>
<ul>
<li><p>334 clients parmi les 500 ne sont plus abonnés. Seulement 166 clients sont encore abonnés.</p></li>
<li><p>La moyenne de 131.18 semaines d’abonnement (pour les clients actuels) n’est pas représentative car elle désigne la durée moyenne minimale de l’abonnement de ces clients.</p></li>
<li><p>La moyenne de 96.16 semaines (pour les clients ayant rompu l’abonnement) n’est pas non plus représentative car ces clients ne forment pas un échantillon représentatif de la clientèle de l’entreprise.</p></li>
<li><p>En analyse de survie, un aspect aussi simple que l’estimation de la moyenne devient très difficile.</p></li>
<li><p>La médiane est beaucoup plus représentative du comportement de la variable Temps dans ce contexte d’analyse.</p></li>
<li><p>50% des clients qui ont quitté (censure=0) s’abonnent à moins de 98 semaines chez Netflix.</p></li>
<li><p>50% des clients qui n’ont pas encore quitté (censure=1) ont un abonnement d’au moins 142 semaines.</p></li>
</ul>
</section>
<section id="analyse-de-survie" class="level3">
<h3 class="anchored" data-anchor-id="analyse-de-survie">Analyse de survie</h3>
<p>On peut utiliser l’analyse de survie pour :</p>
<ol type="1">
<li><p>Estimer le temps de survie dans un état donné.</p></li>
<li><p>Déterminer les variables qui influencent le temps de survie.</p></li>
<li><p>Prévoir le moment où l’individu va quitter cet état (complexe).</p></li>
</ol>
<p>Il existe trois approches pour analyser les données de survie:</p>
<ol type="1">
<li><p><strong>L’approche non paramétrique : Tables de survie et Kaplan-Meier</strong></p></li>
<li><p><strong>L’approche semi-paramétrique : Modèle à risques proportionnels de Cox.</strong></p></li>
<li><p><strong>L’approche paramétrique: Modèle de Weibull, log-normal, Gamma</strong></p></li>
</ol>
<p>Nous nous limiterons aux deux premières méthodes dans le cadre de ce cours.</p>
</section>
<section id="les-fonctions-utiles-en-analyse-de-survie" class="level3">
<h3 class="anchored" data-anchor-id="les-fonctions-utiles-en-analyse-de-survie">Les fonctions utiles en analyse de survie</h3>
<p><code>Rappel</code></p>
<p>Soit T une variable aléatoire représentant la durée de vie d’un individu. T désigne le temps passé dans cet état. <strong>En statistique</strong>, 2 fonctions sont utilisées pour décrire le comportement d’une variable aléatoire, soit sa fonction de densité et sa fonction de répartition.</p>
<ol type="1">
<li><p><u>La fonction de densité:</u> 𝒇( 𝒕) = 𝑷(𝑻 = 𝒕) : 𝒍𝒂 𝒑𝒓𝒐𝒃𝒂𝒃𝒊𝒍𝒊𝒕é 𝒅𝒆 𝒎𝒐𝒖𝒓𝒊𝒓 à 𝒍′𝒊𝒏𝒔𝒕𝒂𝒏𝒕 𝒕.</p></li>
<li><p><u>La fonction de répartition</u>: F (𝒕) = 𝑷(𝑻 ≤ 𝒕) : 𝒍𝒂 𝒑𝒓𝒐𝒃𝒂𝒃𝒊𝒍𝒊𝒕é 𝒅𝒆 𝒎𝒐𝒖𝒓𝒊𝒓 à 𝒍′𝒊𝒏𝒔𝒕𝒂𝒏𝒕 𝒕 𝒐𝒖 𝒂𝒗𝒂𝒏𝒕.</p></li>
</ol>
</section>
<section id="les-fonctions-utiles-en-analyse-de-survie-1" class="level3">
<h3 class="anchored" data-anchor-id="les-fonctions-utiles-en-analyse-de-survie-1">Les fonctions utiles en analyse de survie</h3>
<p>En analyse de survie, les deux fonctions vues précédemment sont un peu modifiées.</p>
<ol type="1">
<li>La fonction de survie: 𝑺(𝒕) = 𝑷(𝑻 ≥ 𝒕 )= 𝟏 − 𝑭 (𝒕)</li>
</ol>
<p><strong><em>La probabilité que le temps de survie soit supérieur ou égal à t.</em></strong></p>
<ol start="2" type="1">
<li>La fonction de risque (hasard fonction): h(𝒕) = 𝒇(𝒕) /𝒔(𝒕) = 𝑷 {𝑻 = 𝒕 |𝑻 ≥ 𝒕)</li>
</ol>
<p><strong><em>La probabilité de mourir à l’instant t, sachant que la personne a été vivante jusqu’à cet instant</em></strong></p>
<p>C’est la fonction de risque qui sera modélisée avec le modèle de régression de Cox qu’on abordera plus loin.</p>
<ul>
<li><p>En régression logistique, on modélise un Logit.</p></li>
<li><p>En analyse de survie, on modélise une fonction de risque.</p></li>
</ul>
</section>
<section id="méthodes-destimation-non-paramétriques" class="level2">
<h2 class="anchored" data-anchor-id="méthodes-destimation-non-paramétriques">Méthodes d’estimation non paramétriques</h2>
<section id="estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" class="level3">
<h3 class="anchored" data-anchor-id="estimation-de-la-fonction-de-survie-lapproche-non-paramétrique">Estimation de la fonction de survie: l’approche non paramétrique</h3>
<p>L’estimation de la fonction de survie est très utile pour:</p>
<ul>
<li><p>Effectuer une analyse descriptive préliminaire pour comprendre le comportement du temps de survie.</p></li>
<li><p>Évaluer l’adéquation de certains modèles de régression.</p></li>
<li><p>Comparer différents groupes de l’échantillon.</p></li>
<li><p>Estimer certains indicateurs d’intérêts comme la médiane ou la moyenne</p></li>
</ul>
</section>
</section>
<section id="lestimateur-de-kaplan-meier-km" class="level2">
<h2 class="anchored" data-anchor-id="lestimateur-de-kaplan-meier-km">L’estimateur de Kaplan-Meier (KM)</h2>
<ul>
<li><p>L’estimateur de Kaplan-Meier est la méthode d’estimation d’une fonction de survie la plus utilisée.</p></li>
<li><p>Cette méthode permet d’estimer la fonction de survie sans devoir regrouper les observations par intervalles.</p></li>
<li><p>KM est la méthode à privilégier si le temps de survie est mesuré avec précision et/ou le nombre d’observations est faible.</p></li>
<li><p>C’est une méthodes d’estimation non paramétrique, dans le sens où on ne suppose pas que le temps de survie suit une loi en particulier.</p></li>
<li><p>Si l’échantillon ne contient aucune censure( uniquement les temps exact sont observés), l’estimateur KM donne la proportion des observations qui possède un temps de survie supérieur à un t (temps) donné.</p></li>
<li><p>s’il y a une censure l’estimateur de KM va ajuster les outputs en tenant compte de la censure.</p></li>
</ul>
<section id="lestimateur-de-kaplan-meier-km-1" class="level4">
<h4 class="anchored" data-anchor-id="lestimateur-de-kaplan-meier-km-1">L’estimateur de Kaplan-Meier (KM)</h4>
<p>L’estimateur KM est donné par :</p>
<p><span class="math display">\[
\hat{S}(T) = \prod_{i: t_i &lt; t} \left( 1 - \frac{d_i}{n_i} \right) = \left( 1 - \frac{d_1}{n_1} \right) \times \left( 1 - \frac{d_2}{n_2} \right) \times \dots
\]</span></p>
<ul>
<li><p><strong><em>dᵢ</em></strong>: le nombre d’individus qui quittent l’état (résilient le contrat ) au temps tᵢ .</p></li>
<li><p><em><strong>nᵢ</strong>:</em> le nombre d’individus à risque au temps tᵢ (l’idée est semblable aux tables de survie).</p></li>
<li><p>(1-<strong><em>dᵢ</em></strong> /<strong><em>nᵢ</em></strong>): la probabilité conditionnelle de rester dans l’état un temps supérieur à tᵢ, étant donné qu’on s’est rendu jusque là.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un objet de survie</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>objet_survie2 <span class="ot">&lt;-</span> <span class="fu">Surv</span>(<span class="at">time =</span> netflix<span class="sc">$</span>Temps, <span class="at">event =</span> <span class="dv">1</span> <span class="sc">-</span> netflix<span class="sc">$</span>censure)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle de survie sans variable explicative</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>fit_km2 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie2 <span class="sc">~</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="output-r-km" class="level4">
<h4 class="anchored" data-anchor-id="output-r-km">Output R (KM)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumer le modèle de survie</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km2, <span class="fu">head</span>(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ 1)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   10    499       1    0.998   0.002        0.994            1</code></pre>
</div>
</div>
<p><strong>Exercice</strong></p>
<p>Calculer la probabilité de survivre plus de 30 semaines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la probabilité de survie au-delà de 30 semaines</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km2, <span class="at">times =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ 1)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   30    494       7    0.986 0.00525        0.976        0.996</code></pre>
</div>
</div>
<p><strong>Réponse</strong></p>
<ol type="1">
<li><p>Les individus à risque de quitter à ce moment = 493 = 500-n.event=500-7 (ils n’ont pas quitté ni n’ont été censurés).</p></li>
<li><p>7 individus ont quitté à moins de 30 semaines d’abonnement.</p></li>
<li><p>S(30)= (1-1/499)<em>(1-1/498)</em>(1-1/497)<em>(1-1/496)</em>(1-1/495)<em>(1-1/494)</em>(1-1/493)=1-7/493= 0.98597</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie de Kaplan-Meier</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
</section>
<section id="quelques-stats-avec-km" class="level4">
<h4 class="anchored" data-anchor-id="quelques-stats-avec-km">Quelques stats avec KM</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renvoie les temps où la survie atteint 75%, 50% et 25% (Q1, médiane, Q3)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(fit_km2, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$quantile
 25  50  75 
 84 114 171 

$lower
 25  50  75 
 80 110 143 

$upper
 25  50  75 
 90 119  NA </code></pre>
</div>
</div>
<p>Pour mesurer la tendance centrale de la variable d’intérêt, il est préférable d’utiliser la médiane ou les quartiles. S(171)= 25% S(114)=50% (médiane) S(84)=75%</p>
<p><code>Exemple:</code> la probabilité de survivre plus de 171 semaines est de 25%.</p>
</section>
<section id="courbes-de-survie-hommefemme" class="level4">
<h4 class="anchored" data-anchor-id="courbes-de-survie-hommefemme">Courbes de survie Homme/Femme</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On ajuste le modèle de survie sur la variable sexe</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fit_km_sexe2 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km_sexe2, <span class="fu">head</span>(<span class="dv">10</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ netflix$sexe)

                netflix$sexe=0 
        time       n.risk      n.event     survival      std.err lower 95% CI 
    1.00e+01     3.08e+02     1.00e+00     9.97e-01     3.23e-03     9.90e-01 
upper 95% CI 
    1.00e+00 

                netflix$sexe=1 
        time       n.risk      n.event     survival      std.err lower 95% CI 
          10          191            0            1            0            1 
upper 95% CI 
           1 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie de Kaplan-Meier</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km_sexe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(fit_km_sexe2, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$quantile
               25  50  75
netflix$sexe=0 78 110 135
netflix$sexe=1 98 123 216

$lower
               25  50  75
netflix$sexe=0 71 102 128
netflix$sexe=1 91 114 171

$upper
                25  50  75
netflix$sexe=0  84 115 177
netflix$sexe=1 105 136  NA</code></pre>
</div>
</div>
<p><strong>Exercice:</strong></p>
<p>Commentez les résultats.</p>
</section>
<section id="comparaison-de-deux-groupes" class="level4">
<h4 class="anchored" data-anchor-id="comparaison-de-deux-groupes">Comparaison de deux groupes</h4>
<p>Les hypothèses du test sont identiques à celle énoncées dans le cas des tables de survie.</p>
<p>H₀ : S fₑₘₘₑ(t)= S hₒₘₘₑ(t)<br>
H₁ : S fₑₘₘₑ(t) ≠ S hₒₘₘₑ(t) pour au moins une valeur de t</p>
<p><strong>Log-rank</strong> : suppose que le ratio des fonctions de risques des 2 groupes est constant pour toute la période d’intérêt.</p>
<p><strong>Breslow (Wilcoxon)</strong>: accorde plus de poids aux différences observées dés le début qu’aux différences observées plus loin dans le temps. Il est donc le plus puissant dans un contexte où les différences sont plus prononcées au tout début.</p>
<p><strong>Terone-Ware:</strong> plus de poids au début.</p>
<p>On a effectué le test du Log-Rank plus haut. Ici, on s’intéresse au test test de Breslow et celui de Tarone-Ware.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Breslow</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe, <span class="at">rho =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = objet_survie2 ~ netflix$sexe, rho = 1)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
netflix$sexe=0 309    145.9    120.2      5.48      17.6
netflix$sexe=1 191     69.4     95.1      6.93      17.6

 Chisq= 17.6  on 1 degrees of freedom, p= 3e-05 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Tarone-Ware </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe, <span class="at">rho =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = objet_survie2 ~ netflix$sexe, rho = 0.5)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
netflix$sexe=0 309    175.3      145      6.21      17.3
netflix$sexe=1 191     88.6      119      7.61      17.3

 Chisq= 17.3  on 1 degrees of freedom, p= 3e-05 </code></pre>
</div>
</div>
<p><strong>Exercice</strong></p>
<p>Comparer les fonctions de survies des différentes régions. Commentez les résultats.</p>
</section>
</section>
<section id="méthode-destimation-semi-paramétrique-modèle-de-cox" class="level2">
<h2 class="anchored" data-anchor-id="méthode-destimation-semi-paramétrique-modèle-de-cox">Méthode d’estimation semi-paramétrique: Modèle de Cox</h2>
<section id="introduction-au-modèle-de-cox" class="level3">
<h3 class="anchored" data-anchor-id="introduction-au-modèle-de-cox">Introduction au modèle de COX</h3>
<ul>
<li><p>Le modèle de Cox est un modèle de régression semi-paramétrique, appelé aussi, modèle à risques proportionnels (<strong>proportional Hazard model</strong>).</p></li>
<li><p>Le modèle de Cox permet d’estimer l’effet des variables explicatives sur la variable aléatoire T sans postulat de distribution particulière (sans spécifier une loi de distribution) pour celle celle-ci.</p></li>
<li><p>C’est un modèle semi-paramétrique car <strong>seulement une partie</strong> du modèle doit être <strong>spécifiée</strong>.</p></li>
<li><p>Le modèle de Cox est similaire au modèle de régression logistique mais évalue la relation entre le temps de survie et les variables explicatives.</p></li>
<li><p>C’est le modèle le plus utilisé pour analyser les données de survie.</p></li>
</ul>
<section id="description-du-modèle" class="level4">
<h4 class="anchored" data-anchor-id="description-du-modèle">Description du modèle</h4>
<p>𝒉(𝒕|𝒙₁, 𝒙₂, … , 𝒙ₖ) est la fonction de risque pour les individus ayant les caractéristiques spécifiques (𝒙₁, 𝒙₂, … , 𝒙ₖ).</p>
<p>Le modèle de Cox s’écrit: <span class="math display">\[
h(t | x_1, x_2, \dots, x_k) = h_0(t) \times \exp(\beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k)
\]</span> est une fonction de risque de base qui n’ a pas besoin d’être spécifié.</p>
<p>La fonction de risque est donc le produit de deux parties distinctes:</p>
<ol type="1">
<li><p>une partie sans paramètres, <strong>qui dépend uniquement du temps</strong></p></li>
<li><p>et une partie avec paramètres qui <strong>dépend uniquement des variables explicatives.</strong></p></li>
</ol>
<p>Remarques:</p>
<ul>
<li><p>Lorsque toutes les variables explicatives prennent la valeur 0, on retrouve 𝒉₀ 𝒕 (cette valeur est équivalente à « l’ordonnée à l’origine en régression linéaire »).</p></li>
<li><p>ex p(β₁x₁ + β₂x₂ + … + βₖxₖ modélise l’effet d’un changement des valeurs des variables explicatives sur la fonction de risque de base”)</p></li>
</ul>
</section>
<section id="interprétation-des-paramètres-r-modèle-de-cox-avec-toutes-les-variables-explicatives" class="level4">
<h4 class="anchored" data-anchor-id="interprétation-des-paramètres-r-modèle-de-cox-avec-toutes-les-variables-explicatives">Interprétation des paramètres R: Modèle de Cox avec toutes les variables explicatives</h4>
<p>Si on compare le ratio des risques de deux individus ayant les mêmes valeurs pour les variables explicatives, à l’exception de la variable x1, qui diffère d’une unité, on obtient ce qui suit:</p>
<p><span class="math display">\[
\frac{h(t | x_1 + 1, x_2, \dots, x_k)}{h(t | x_1, x_2, \dots, x_k)}
= \frac{h_0(t) \exp\left(\beta_1 (x_1 + 1) + \beta_2 x_2 + \dots + \beta_k x_k \right)}{h_0(t) \exp\left(\beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k \right)}
= e^{\beta_1}
\]</span></p>
<p><strong>Interprétation de β₁ :</strong></p>
<p>lorsque x1 augmente d’une unité, le risque est multiplié par 𝒆ᵝ¹ (ratio de risque).</p>
<p><strong>Résultats:</strong></p>
<ul>
<li><p>Le ratio de risque ne dépend pas du temps.</p></li>
<li><p>Le ratio de risque est constant par rapport au temps. (l’effet de la variable explicative est stable dans le temps).</p></li>
</ul>
</section>
<section id="r-modèle-de-cox-avec-toutes-les-variables-explicatives" class="level4">
<h4 class="anchored" data-anchor-id="r-modèle-de-cox-avec-toutes-les-variables-explicatives">R: Modèle de Cox avec toutes les variables explicatives</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle de Cox avec les variables âge, sexe et région</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(Temps, censure) <span class="sc">~</span> age <span class="sc">+</span> sexe <span class="sc">+</span> region, <span class="at">data =</span> netflix, <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumer le modèle de Cox</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(Temps, censure) ~ age + sexe + region, data = netflix, 
    ties = "exact")

  n= 500, number of events= 166 

            coef exp(coef) se(coef)      z Pr(&gt;|z|)    
age     -0.04314   0.95778  0.00947 -4.555 5.23e-06 ***
sexe1   -0.48278   0.61706  0.17045 -2.832  0.00462 ** 
region2 -0.40384   0.66775  0.27041 -1.493  0.13532    
region3 -0.04773   0.95339  0.25291 -0.189  0.85031    
region4 -0.41091   0.66304  0.25774 -1.594  0.11087    
region5 -0.16652   0.84661  0.25633 -0.650  0.51594    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

        exp(coef) exp(-coef) lower .95 upper .95
age        0.9578      1.044    0.9402    0.9757
sexe1      0.6171      1.621    0.4418    0.8618
region2    0.6677      1.498    0.3930    1.1345
region3    0.9534      1.049    0.5808    1.5651
region4    0.6630      1.508    0.4001    1.0988
region5    0.8466      1.181    0.5123    1.3992

Concordance= 0.637  (se = 0.026 )
Likelihood ratio test= 29.62  on 6 df,   p=5e-05
Wald test            = 27.97  on 6 df,   p=1e-04
Score (logrank) test = 28.22  on 6 df,   p=9e-05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie estimée à partir du modèle de Cox</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(cox))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la fonction de risque cumulée </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(cox), <span class="at">fun =</span> <span class="st">"cumhaz"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interprétation" class="level4">
<h4 class="anchored" data-anchor-id="interprétation">Interprétation</h4>
<p>On estime, toutes choses étant égale par ailleurs (si tout demeure constant):</p>
<ul>
<li><p><strong>À tout moment dans le temps</strong>, le risque qu’une femme (sexe=1) mette fin à son contrat est exp(-0.519)=0.595 fois le risque d’un homme (le risque est 40.5% inférieur (1-0.595=0.405)).</p></li>
<li><p>Pour chaque augmentation d’une année de l’âge lors de l’abonnement, le risque de quitter diminue de 4.3% (exp(-0,043)=0.957) <strong>à tout moment dans le temps</strong>.</p></li>
<li><p><strong>À tout moment dans le temps</strong>, le risque qu’un client de la région 2 résilie son contrat est exp(-0.329)=0.729 fois celui de la région 1 (référence).</p></li>
</ul>
<p><strong>Exercice</strong></p>
<p>Testez les significativité des paramètres dans le modèle au niveau 5% et interprétez le reste des coefficients estimés.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>