<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thème 5: La régréssion linéaire</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LIVRABLE_T5_files/libs/clipboard/clipboard.min.js"></script>
<script src="LIVRABLE_T5_files/libs/quarto-html/quarto.js"></script>
<script src="LIVRABLE_T5_files/libs/quarto-html/popper.min.js"></script>
<script src="LIVRABLE_T5_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LIVRABLE_T5_files/libs/quarto-html/anchor.min.js"></script>
<link href="LIVRABLE_T5_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LIVRABLE_T5_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LIVRABLE_T5_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LIVRABLE_T5_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LIVRABLE_T5_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="LIVRABLE_T5_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="LIVRABLE_T5_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="LIVRABLE_T5_files/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#mise-en-situation-1" id="toc-mise-en-situation-1" class="nav-link active" data-scroll-target="#mise-en-situation-1"><span class="header-section-number">0.1</span> Mise en situation 1</a></li>
  <li><a href="#objectif" id="toc-objectif" class="nav-link" data-scroll-target="#objectif"><span class="header-section-number">0.2</span> Objectif</a></li>
  <li><a href="#lien-entre-deux-variables-quantitatives-rappel" id="toc-lien-entre-deux-variables-quantitatives-rappel" class="nav-link" data-scroll-target="#lien-entre-deux-variables-quantitatives-rappel"><span class="header-section-number">0.3</span> Lien entre deux variables quantitatives (rappel)</a></li>
  <li><a href="#diagnostic-graphique-diagramme-de-dispersion" id="toc-diagnostic-graphique-diagramme-de-dispersion" class="nav-link" data-scroll-target="#diagnostic-graphique-diagramme-de-dispersion"><span class="header-section-number">0.4</span> Diagnostic graphique: diagramme de dispersion</a></li>
  <li><a href="#coefficient-de-corrélation-de-pearson" id="toc-coefficient-de-corrélation-de-pearson" class="nav-link" data-scroll-target="#coefficient-de-corrélation-de-pearson"><span class="header-section-number">0.5</span> Coefficient de corrélation de Pearson</a></li>
  <li><a href="#calcul-du-coefficient-de-corrélation-de-pearson" id="toc-calcul-du-coefficient-de-corrélation-de-pearson" class="nav-link" data-scroll-target="#calcul-du-coefficient-de-corrélation-de-pearson"><span class="header-section-number">0.6</span> Calcul du coefficient de corrélation de Pearson</a></li>
  <li><a href="#modèle-de-régression-linéaire" id="toc-modèle-de-régression-linéaire" class="nav-link" data-scroll-target="#modèle-de-régression-linéaire"><span class="header-section-number">0.7</span> Modèle de régression linéaire</a></li>
  <li><a href="#analyse-de-la-variance" id="toc-analyse-de-la-variance" class="nav-link" data-scroll-target="#analyse-de-la-variance"><span class="header-section-number">0.8</span> Analyse de la variance</a></li>
  <li><a href="#validation-du-modèle" id="toc-validation-du-modèle" class="nav-link" data-scroll-target="#validation-du-modèle"><span class="header-section-number">0.9</span> Validation du modèle</a></li>
  <li><a href="#coefficient-de-determination-r²-mesure-de-performance-du-modèle" id="toc-coefficient-de-determination-r²-mesure-de-performance-du-modèle" class="nav-link" data-scroll-target="#coefficient-de-determination-r²-mesure-de-performance-du-modèle"><span class="header-section-number">0.10</span> Coefficient de determination R² : mesure de performance du modèle</a></li>
  <li><a href="#la-statistique-r²-ajusté" id="toc-la-statistique-r²-ajusté" class="nav-link" data-scroll-target="#la-statistique-r²-ajusté"><span class="header-section-number">0.11</span> La statistique R² ajusté</a></li>
  <li><a href="#exercice-1" id="toc-exercice-1" class="nav-link" data-scroll-target="#exercice-1"><span class="header-section-number">0.12</span> Exercice 1</a></li>
  <li><a href="#intervalle-de-confiance-pour-estimer-la-moyenne-conditionnelle-et-intervalle-de-prévision" id="toc-intervalle-de-confiance-pour-estimer-la-moyenne-conditionnelle-et-intervalle-de-prévision" class="nav-link" data-scroll-target="#intervalle-de-confiance-pour-estimer-la-moyenne-conditionnelle-et-intervalle-de-prévision"><span class="header-section-number">0.13</span> Intervalle de confiance pour estimer la moyenne conditionnelle et intervalle de prévision</a></li>
  <li><a href="#exercice-2" id="toc-exercice-2" class="nav-link" data-scroll-target="#exercice-2"><span class="header-section-number">0.14</span> Exercice 2:</a></li>
  <li><a href="#exercice-3" id="toc-exercice-3" class="nav-link" data-scroll-target="#exercice-3"><span class="header-section-number">0.15</span> Exercice 3</a></li>
  <li><a href="#régression-avec-variable-service-seulement" id="toc-régression-avec-variable-service-seulement" class="nav-link" data-scroll-target="#régression-avec-variable-service-seulement"><span class="header-section-number">0.16</span> Régression avec variable service seulement</a></li>
  <li><a href="#régression-avec-service-qualité-et-décor." id="toc-régression-avec-service-qualité-et-décor." class="nav-link" data-scroll-target="#régression-avec-service-qualité-et-décor."><span class="header-section-number">0.17</span> Régression avec service, qualité et décor.</a></li>
  <li><a href="#modélisation-avec-variables-explicatives-catégorielles" id="toc-modélisation-avec-variables-explicatives-catégorielles" class="nav-link" data-scroll-target="#modélisation-avec-variables-explicatives-catégorielles"><span class="header-section-number">0.18</span> Modélisation avec variables explicatives catégorielles</a></li>
  <li><a href="#mise-en-situation-2" id="toc-mise-en-situation-2" class="nav-link" data-scroll-target="#mise-en-situation-2"><span class="header-section-number">0.19</span> Mise en situation 2</a></li>
  <li><a href="#exercice-4" id="toc-exercice-4" class="nav-link" data-scroll-target="#exercice-4"><span class="header-section-number">0.20</span> Exercice 4</a></li>
  <li><a href="#démarche-et-solution" id="toc-démarche-et-solution" class="nav-link" data-scroll-target="#démarche-et-solution"><span class="header-section-number">0.21</span> Démarche et solution</a></li>
  <li><a href="#test-de-significativité-globale-pour-un-sous-ensemble-de-variable" id="toc-test-de-significativité-globale-pour-un-sous-ensemble-de-variable" class="nav-link" data-scroll-target="#test-de-significativité-globale-pour-un-sous-ensemble-de-variable"><span class="header-section-number">0.22</span> Test de significativité globale pour un sous ensemble de variable</a></li>
  <li><a href="#modèle-hiérarchique-ou-régression-séquentielle" id="toc-modèle-hiérarchique-ou-régression-séquentielle" class="nav-link" data-scroll-target="#modèle-hiérarchique-ou-régression-séquentielle"><span class="header-section-number">0.23</span> Modèle hiérarchique ou régression séquentielle</a></li>
  <li><a href="#méthodes-de-sélection-de-modèles-stepwise" id="toc-méthodes-de-sélection-de-modèles-stepwise" class="nav-link" data-scroll-target="#méthodes-de-sélection-de-modèles-stepwise"><span class="header-section-number">0.24</span> Méthodes de Sélection de modèles (Stepwise)</a></li>
  <li><a href="#méthodes-de-sélection-de-modèles-backward" id="toc-méthodes-de-sélection-de-modèles-backward" class="nav-link" data-scroll-target="#méthodes-de-sélection-de-modèles-backward"><span class="header-section-number">0.25</span> Méthodes de Sélection de modèles (Backward)</a></li>
  <li><a href="#sélection-du-meilleur-modèle-selon-un-critère" id="toc-sélection-du-meilleur-modèle-selon-un-critère" class="nav-link" data-scroll-target="#sélection-du-meilleur-modèle-selon-un-critère"><span class="header-section-number">0.26</span> Sélection du meilleur modèle selon un critère</a></li>
  <li><a href="#interaction" id="toc-interaction" class="nav-link" data-scroll-target="#interaction"><span class="header-section-number">0.27</span> Interaction</a></li>
  <li><a href="#exemple-pour-illustrer-linteraction" id="toc-exemple-pour-illustrer-linteraction" class="nav-link" data-scroll-target="#exemple-pour-illustrer-linteraction"><span class="header-section-number">0.28</span> Exemple pour illustrer l’interaction</a></li>
  <li><a href="#multicolinéarité" id="toc-multicolinéarité" class="nav-link" data-scroll-target="#multicolinéarité"><span class="header-section-number">0.29</span> Multicolinéarité</a></li>
  <li><a href="#diagnostic-de-la-multicolinéarité" id="toc-diagnostic-de-la-multicolinéarité" class="nav-link" data-scroll-target="#diagnostic-de-la-multicolinéarité"><span class="header-section-number">0.30</span> Diagnostic de la multicolinéarité</a></li>
  <li><a href="#validité-du-modèle-de-régression-linéaire" id="toc-validité-du-modèle-de-régression-linéaire" class="nav-link" data-scroll-target="#validité-du-modèle-de-régression-linéaire"><span class="header-section-number">0.31</span> Validité du modèle de régression linéaire</a></li>
  <li><a href="#étapes-pour-valider-le-modèle" id="toc-étapes-pour-valider-le-modèle" class="nav-link" data-scroll-target="#étapes-pour-valider-le-modèle"><span class="header-section-number">0.32</span> Étapes pour valider le modèle</a></li>
  <li><a href="#transformation" id="toc-transformation" class="nav-link" data-scroll-target="#transformation"><span class="header-section-number">0.33</span> Transformation</a></li>
  <li><a href="#ajout-de-termes-polynomiaux" id="toc-ajout-de-termes-polynomiaux" class="nav-link" data-scroll-target="#ajout-de-termes-polynomiaux"><span class="header-section-number">0.34</span> Ajout de termes polynomiaux</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thème 5: La régréssion linéaire</h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="mise-en-situation-1" class="level3" data-number="0.1">
<h3 data-number="0.1" class="anchored" data-anchor-id="mise-en-situation-1"><span class="header-section-number">0.1</span> Mise en situation 1</h3>
<p>Au cours d’une enquête menée en 2001, un chercheur a demandé aux clients d’évaluer 168 restaurants Italiens situés dans la ville de New York en fonction de trois aspects différents: la qualité de la nourriture, la décoration et le service. Les variables disponibles dans la base de données «Restaurants.csv» sont définies comme suit:</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nom</td>
<td style="text-align: left;">Nom du restaurant</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prix</td>
<td style="text-align: left;">Prix du dîner incluant une boisson et le pourboire</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qualité</td>
<td style="text-align: left;">Score d’évaluation de la qualité de la nourriture sur une échelle de 0 à 30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Décor</td>
<td style="text-align: left;">Score d’évaluation de la décoration du restaurant sur une échelle de 0 à 30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Service</td>
<td style="text-align: left;">Score d’évaluation du service sur une échelle de 0 à 30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emplacement</td>
<td style="text-align: left;">1 : restaurant situé à l’Est de la cinquième avenue ; 0 : restaurant situé à l’Ouest de la cinquième avenue</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>resto<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"Restaurants.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la variable Emplacement en facteur </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>resto<span class="sc">$</span>Emplacement <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(resto<span class="sc">$</span>Emplacement)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="objectif" class="level3" data-number="0.2">
<h3 data-number="0.2" class="anchored" data-anchor-id="objectif"><span class="header-section-number">0.2</span> Objectif</h3>
<p>On s’intéresse, en règle générale, aux types de liens qui existent entre différentes variables.</p>
<p><strong>Exemples</strong></p>
<ul>
<li><p>Existe-t-il un lien entre le prix d’un repas et la qualité du restaurant?</p></li>
<li><p>La qualité a-t-elle un impact significatif sur le prix du repas?</p></li>
<li><p>Le prix varie-t-il en fonction de l’emplacement du restaurant?</p></li>
<li><p>Est-ce que le service, le décor, la qualité et l’emplacement ont un impact sur le prix d’un dîner dans un restaurant italien?</p></li>
</ul>
<p>Le type de variables et le nombre de variables impliquées dans les relations qui nous intéressent guident le choix de la méthode et de la direction de notre analyse.</p>
</section>
<section id="lien-entre-deux-variables-quantitatives-rappel" class="level3" data-number="0.3">
<h3 data-number="0.3" class="anchored" data-anchor-id="lien-entre-deux-variables-quantitatives-rappel"><span class="header-section-number">0.3</span> Lien entre deux variables quantitatives (rappel)</h3>
<p>Pour détecter, mesurer et interpréter un <strong>lien linéaire</strong> entre deux variables quantitatives, on commence, dans l’ordre, par:</p>
<p>1-Effectuer un diagnostic graphique (<strong>nuage de point /diagramme de dispersion/ scatterplot</strong>) pour détecter le mouvement conjoint dans la variation des deux variables.</p>
<p>2-Calculer le <strong>coefficient de corrélation linéaire</strong> observé dans l’échantillon.</p>
<p>3-Tester la <strong>significativité du lien</strong> linéaire entre les deux variables.</p>
</section>
<section id="diagnostic-graphique-diagramme-de-dispersion" class="level3" data-number="0.4">
<h3 data-number="0.4" class="anchored" data-anchor-id="diagnostic-graphique-diagramme-de-dispersion"><span class="header-section-number">0.4</span> Diagnostic graphique: diagramme de dispersion</h3>
<p>Un diagramme de dispersion permet:</p>
<ul>
<li><p>de valider si une relation semble exister entre les variables&nbsp;;</p></li>
<li><p>de visualiser le type de la relation (linéaire ou autre)&nbsp;;</p></li>
<li><p>de vérifier s’il y a des valeurs qui diffèrent de la tendance (valeurs aberrantes ou extrêmes</p></li>
</ul>
<p><strong>Exemple 1: relation entre qualité et prix</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les bibliothèques nécessaires</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot pour visualiser la relation entre qualité et prix</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resto, <span class="fu">aes</span>(<span class="at">x =</span> Qualité, <span class="at">y =</span> Prix)) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Cercle vide</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>  <span class="co"># Thème simple</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relation entre qualité et prix"</span>, <span class="at">x =</span> <span class="st">"Qualité"</span>, <span class="at">y =</span> <span class="st">"Prix"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="coefficient-de-corrélation-de-pearson" class="level3" data-number="0.5">
<h3 data-number="0.5" class="anchored" data-anchor-id="coefficient-de-corrélation-de-pearson"><span class="header-section-number">0.5</span> Coefficient de corrélation de Pearson</h3>
<p><strong>Rappel</strong>: La corrélation (aussi appelée coefficient de corrélation de Pearson) mesure la force et la direction de la relation linéaire entre deux variables quantitatives sur une échelle allant de -1 à 1.</p>
<p>On dénote la corrélation observée dans l’échantillon par r (le coefficient de corrélation dans la population est noté par ρ ).</p>
<p><span class="math display">\[
r = \frac{\sum\limits_{i=1}^{n} (X_i - \overline{X})(Y_i - \overline{Y})}
{\sqrt{\sum\limits_{i=1}^{n} (X_i - \overline{X})^2 \sum\limits_{i=1}^{n} (Y_i - \overline{Y})^2}}
\]</span></p>
<p>Plus on est près des extrémités de l’échelle (-1 ou 1), plus l’intensité de la relation est forte.</p>
<ul>
<li><p><strong>Un coefficient <em>r</em> = -1</strong>&nbsp;: une parfaite relation négative.</p></li>
<li><p><strong>Un coefficient <em>r</em> = 0</strong>&nbsp;: il n’y a <strong>aucune relation linéaire</strong> entre les variables ou il y a une relation entre les deux variables mais le lien n’est pas linéaire.</p></li>
<li><p><strong>Un coefficient <em>r</em> = 1</strong>&nbsp;: une parfaite relation <strong>positive.</strong></p></li>
</ul>
<p>Attention r peut être influencé par la présence de valeurs extrêmes ou aberrantes d’où l’importance du diagnostique graphique.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calcul-du-coefficient-de-corrélation-de-pearson" class="level3" data-number="0.6">
<h3 data-number="0.6" class="anchored" data-anchor-id="calcul-du-coefficient-de-corrélation-de-pearson"><span class="header-section-number">0.6</span> Calcul du coefficient de corrélation de Pearson</h3>
<p><span class="math display">\[
\textbf{Les hypothèses :}
\]</span></p>
<p><span class="math display">\[
H_0 : \rho = 0 \quad \text{(Absence de relation linéaire)}
\]</span></p>
<p><span class="math display">\[
H_1 : \rho \neq 0 \quad \text{(Présence d’une relation linéaire)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la matrice de corrélation de Pearson entre les variables numériques</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(resto[, <span class="fu">c</span>(<span class="st">"Prix"</span>, <span class="st">"Qualité"</span>, <span class="st">"Service"</span>, <span class="st">"Décor"</span>)], <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la matrice de corrélation</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Prix   Qualité   Service     Décor
Prix    1.0000000 0.6270435 0.6411402 0.7243525
Qualité 0.6270435 1.0000000 0.7945248 0.5039161
Service 0.6411402 0.7945248 1.0000000 0.6453306
Décor   0.7243525 0.5039161 0.6453306 1.0000000</code></pre>
</div>
</div>
<section id="retour-à-lexemple" class="level4" data-number="0.6.1">
<h4 data-number="0.6.1" class="anchored" data-anchor-id="retour-à-lexemple"><span class="header-section-number">0.6.1</span> Retour à l’exemple</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatterplot avec une ligne de régression linéaire</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resto, <span class="fu">aes</span>(<span class="at">x =</span> Qualité, <span class="at">y =</span> Prix)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span>  </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Qualité"</span>, <span class="at">y =</span> <span class="st">"Prix"</span>, <span class="at">title =</span> <span class="st">"Relation entre Qualité et Prix"</span>) <span class="sc">+</span>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Les données observées nous permettent de détecter une dépendance linéaire assez forte et significative (au niveau 1%) entre la qualité des mets et le prix du repas.</p></li>
<li><p>Plus le score de qualité est élevé, plus les prix ont aussi tendance à être élevés. Cette tendance se confirme aussi par la valeur du coefficient de corrélation linéaire (r = 0,627)</p></li>
<li><p>Comment peut-on utiliser l’information fournie par les données observées pour «&nbsp;prédire&nbsp;» les prix d’un repas pour un restaurant italien donné?</p></li>
<li><p>Pour ce faire, on peut modéliser la relation observée entre les deux variables à l’aide d’une fonction.</p></li>
</ul>
</section>
</section>
<section id="modèle-de-régression-linéaire" class="level3" data-number="0.7">
<h3 data-number="0.7" class="anchored" data-anchor-id="modèle-de-régression-linéaire"><span class="header-section-number">0.7</span> Modèle de régression linéaire</h3>
<p>Le modèle de régression linéaire est:</p>
<p><span class="math display">\[ Y = \beta_0 + \beta_1 X_1 + \dots + \beta_k X_k + \varepsilon \]</span></p>
<ul>
<li><p>Y = variable <strong>expliquée</strong> ou <strong>dépendante</strong> ou réponse</p></li>
<li><p>X₁, …, Xₖ = variables <strong>explicatives</strong> ou <strong>indépendantes</strong> (une seule dans le cas de la régression simple, 2 ou plus pour la régression multiple)</p></li>
<li><p>On dispose de n observations (X₁₁, …, Xₖ₁, Y₁), (X₁₂, …, Xₖ₂, Y₂), …, (X₁ₙ, …, Xₖₙ, Yₙ), sur ces variables.</p></li>
<li><p>Le terme 𝝐 est appelé l<strong>’erreur du modèle</strong>.</p></li>
<li><p>L’erreur représente tous les autres facteurs ( omis dans l’équation) pouvant «expliquer» la valeur de Y.</p></li>
<li><p>Ce type de modèle est très souvent adéquat lorsque nous assumons que 𝝐 est une variable aléatoire suivant une loi normale d’espérance 0 et d’écart-type σₑ.</p></li>
<li><p>Les paramètres du modèles sont estimés par la méthode des moindres carrés</p></li>
</ul>
<p>Le modèle stipule qu’il existe une relation linéaire entre les variables explicatives (X₁, …, Xₖ) et la moyenne des Y correspondants et non pas directement entre les variables explicatives (X₁, …, Xₖ) et Y.</p>
<p>Par exemple, pour la régression linéaire simple:</p>
<p><img src="images/clipboard-3195730040.png" class="img-fluid"></p>
</section>
<section id="analyse-de-la-variance" class="level3" data-number="0.8">
<h3 data-number="0.8" class="anchored" data-anchor-id="analyse-de-la-variance"><span class="header-section-number">0.8</span> Analyse de la variance</h3>
<p>On peut décomposer la variabilité totale de Y en deux composantes :</p>
<ul>
<li><p>Celle qui est expliquée par le modèle de régression</p></li>
<li><p>et celle qui ne l’est pas (variation résiduelle <strong>due à l’erreur</strong>).</p></li>
</ul>
<p><span class="math display">\[
\sum (y_i - \bar{y})^2 = \sum (\hat{y_i} - \bar{y})^2 + \sum (y_i - \hat{y_i})^2
\]</span></p>
<p><span class="math display">\[
SS_C = SS_R + SS_e
\]</span></p>
<p>Cette décomposition nous permet d’obtenir un tableau d’Anova à partir duquel on pourra développer un test permettant de vérifier si <strong>la régression est globalement significative</strong> pour expliquer la variabilité de Y (<strong>Test F</strong>).</p>
<p><strong><em>Tableau d’analyse de la variance: cas général</em></strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Source.de.la.variation</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Somme.de.carrés</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Degrés.de.liberté</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Carré.moyen</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important;">Régression</td>
<td style="text-align: center;">SS_R</td>
<td style="text-align: center;">k</td>
<td style="text-align: center;">MSR = SS_R / k</td>
<td style="text-align: center; font-weight: bold; color: black !important;">F = MSR / MSE</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important;">Résiduelle (erreur)</td>
<td style="text-align: center;">SS_e</td>
<td style="text-align: center;">n - k - 1</td>
<td style="text-align: center;">MSE = SS_e / (n-k-1)</td>
<td style="text-align: center; font-weight: bold; color: black !important;"></td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important;">Totale</td>
<td style="text-align: center;">SS_C</td>
<td style="text-align: center;">n - 1</td>
<td style="text-align: center;"></td>
<td style="text-align: center; font-weight: bold; color: black !important;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</section>
<section id="validation-du-modèle" class="level3" data-number="0.9">
<h3 data-number="0.9" class="anchored" data-anchor-id="validation-du-modèle"><span class="header-section-number">0.9</span> Validation du modèle</h3>
<p>L’équation expérimentale (modèle ajusté) devient: <span class="math display">\[
\hat{Y} = b_0 + b_1 X_1 + b_2 X_2 + \dots + b_k X_k
\]</span></p>
<p><strong>1-Test sur la significativité globale: (Test F du tableau d’ANOVA).</strong></p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \dots = \beta_p = 0 \quad \text{(Globalement, la régression n’est pas significative)}
\]</span></p>
<p><span class="math display">\[
H_1: \text{au moins un de ces paramètres} \neq 0 \quad \text{(Globalement, la régression est significative)}
\]</span></p>
<p>Si H₀ est vraie, la statistique du test: F = <span class="math display">\[
F = \frac{\frac{SSR}{(n-1)}}{\frac{SSE}{(n-p-1)}}
\]</span></p>
<p>Si on rejette H₀, on en conclut que le Modèle est globalement significatif c.a.d qu’il existe au moins une variable X utile pour expliquer le comportement de Y.</p>
<p><strong>2-Tests sur les contributions marginales individuelles (Tests T sur les coefficients).</strong></p>
<p>Il y a autant de tests individuels que de variables dans le modèle</p>
<p><span class="math display">\[
H_0: \beta_i = 0 \quad \text{vs} \quad H_1: \beta_i \neq 0, \quad i = 1, \dots, k
\]</span></p>
<ul>
<li><p>En régression linéaire multiple, on teste la contribution partielle de Xⱼ sachant que les autres variables sont dans le modèle.</p></li>
<li><p>Le non rejet de H₀ veut dire qu’il n’y a pas de lien linéaire significatif entre Xⱼ et Y une fois que l’on tient compte de toutes les autres variables dans le modèle.</p></li>
<li><p>Le rejet de H₀ veut dire que la variable Xⱼ contribue à expliquer Y au delà des autres variables dans le modèle.</p></li>
</ul>
<p><strong>Interprétation des coefficients:</strong></p>
<p>b₀ : représente la moyenne de Y lorsque X₁ = 0, X₂ = 0 … 𝑒𝑡 Xₖ=0, <em>si cela a du sens</em>.</p>
<p>bⱼ : mesure <strong><em>l’effet marginal ou la contribution marginale</em></strong> de la variable Xⱼ <em>une fois que l’on tient compte des autres variables dans le modèle.</em></p>
<p>bⱼ : s’interprète comme la variation de la moyenne de Y lorsque Xⱼ augmente d’une unité, <em>lorsque les autres variables demeurent inchangées.</em></p>
</section>
<section id="coefficient-de-determination-r²-mesure-de-performance-du-modèle" class="level3" data-number="0.10">
<h3 data-number="0.10" class="anchored" data-anchor-id="coefficient-de-determination-r²-mesure-de-performance-du-modèle"><span class="header-section-number">0.10</span> Coefficient de determination R² : mesure de performance du modèle</h3>
<p>Le coefficient de détermination R² mesure la proportion de la variabilité observée de Y qui est expliquée par la régression.</p>
<p><span class="math display">\[
R^2 = \frac{SS_R}{SS_C}
\]</span></p>
<ul>
<li><p>Ce coefficient peut servir à mesurer la performance du modèle comme outil de prévision.</p></li>
<li><p>R² prend ses valeurs entre 0 et 1. Plus ce coefficient est grand, plus la relation linéaire est forte.</p></li>
<li><p>En régression linéaire simple, ce coefficient est simplement égal au carré du coefficient de corrélation de Pearson.</p></li>
</ul>
</section>
<section id="la-statistique-r²-ajusté" class="level3" data-number="0.11">
<h3 data-number="0.11" class="anchored" data-anchor-id="la-statistique-r²-ajusté"><span class="header-section-number">0.11</span> La statistique R² ajusté</h3>
<ul>
<li><p>En régression linéaire multiple, la performance du modèle ajusté est évalué par son coefficient de détermination R².</p></li>
<li><p>Lorsque des variables indépendantes additionnelles sont ajoutées à un modèle, le R² ne peut qu’augmenter ce qui laisse à croire, à tort, que plus il y a de variables dans le modèle mieux c’est.</p></li>
<li><p>La statistique R² peut être gonflée artificiellement par l’ajout de n’importe quelle variable indépendante au modèle.</p></li>
<li><p>Si on veut donc comparer des modèles ne comportant pas le même nombre de variables explicatives, on utilisera une mesure qui pénalise l’ajout de prédicteurs. Cette mesure s’appelle le R² ajusté.</p></li>
</ul>
<p><span class="math display">\[
R^2 = \frac{SS_E}{SS_T}
\]</span></p>
<p><span class="math display">\[
R^2ajusté = 1-(\frac{SS_E}{SS_T})(\frac{n-1}{n-p-1})
\]</span></p>
</section>
<section id="exercice-1" class="level3" data-number="0.12">
<h3 data-number="0.12" class="anchored" data-anchor-id="exercice-1"><span class="header-section-number">0.12</span> Exercice 1</h3>
<ol type="1">
<li><p>Estimez le modèle de régression linéaire simple pour expliquer le prix d’un repas dans un restaurant italien à New York par la variable qualité.</p></li>
<li><p>Donnez la droite de régression estimée.</p></li>
<li><p>Interprétez les estimés ponctuels et les intervalles de confiances des paramètres du modèle.</p></li>
<li><p>Une ordonnée à l’origine négative fait elle du sens dans ce contexte? Le modèle est-il globalement significatif?</p></li>
<li><p>Quelle est la valeur du R²? Interprétez-en la valeur.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour prédire le prix en fonction de la qualité</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>modele_qualite <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Qualité, <span class="at">data =</span> resto)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_qualite)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Qualité, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.8860  -3.9470   0.2056   4.2513  26.9919 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -17.8321     5.8631  -3.041  0.00274 ** 
Qualité       2.9390     0.2834  10.371  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.261 on 166 degrees of freedom
Multiple R-squared:  0.3932,    Adjusted R-squared:  0.3895 
F-statistic: 107.6 on 1 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="intervalle-de-confiance-pour-estimer-la-moyenne-conditionnelle-et-intervalle-de-prévision" class="level3" data-number="0.13">
<h3 data-number="0.13" class="anchored" data-anchor-id="intervalle-de-confiance-pour-estimer-la-moyenne-conditionnelle-et-intervalle-de-prévision"><span class="header-section-number">0.13</span> Intervalle de confiance pour estimer la moyenne conditionnelle et intervalle de prévision</h3>
<p>La droite de régression estimée peut être utilisée pour :</p>
<ol type="1">
<li><p>Estimer la moyenne conditionnelle de Y pour une valeur de x fixée.</p></li>
<li><p>Prévoir la valeur de Y pour une nouvelle observation de x.</p></li>
</ol>
<ul>
<li><p>Pour le même x fixé, la valeur <em>ŷ(x)</em> fournit à la fois une estimation ponctuelle de la moyenne conditionnelle de Y et une prévision ponctuelle de la valeur de Y.</p></li>
<li><p>Cependant, la marge d’erreur associée à la prévision sera nécessairement plus grande que la marge d’erreur associée à l’estimation de la moyenne.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalle de confiance pour un restaurant d'une qualité de 17:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer une nouvelle observation avec qualité = 17</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>nouveau_resto <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Qualité <span class="ot">=</span> <span class="dv">17</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Prédiction du prix avec intervalle de confiance</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>prediction_17 <span class="ot">&lt;-</span> <span class="fu">predict</span>(modele_qualite, <span class="at">newdata =</span> nouveau_resto, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Prédiction du prix avec intervalle de prévision</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>prevision_17 <span class="ot">&lt;-</span> <span class="fu">predict</span>(modele_qualite, <span class="at">newdata =</span> nouveau_resto, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la prédiction</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prediction_17)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 32.13017 29.83465 34.42569</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher l'intervalle de prévision</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prevision_17)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 32.13017 17.61227 46.64807</code></pre>
</div>
</div>
<p>Estimation ponctuelle et intervalle de confiance du prix moyen pour un restaurant ayant un score de qualité de 17:</p>
<ul>
<li><p>Estimé du prix moyen= -17.832+2.94*17= 32.13$</p></li>
<li><p>Au niveau de confiance 95%, on estime que <strong>le prix moyen des restaurants ayant un score de qualité de 17</strong> est situé entre 29.83$ et 34.42</p></li>
<li><p>Au niveau de confiance 95% on estime que <strong>le prix d’un restaurant ayant un score de qualité de 17</strong> est entre 17.61$ et 46.65%.</p></li>
</ul>
</section>
<section id="exercice-2" class="level3" data-number="0.14">
<h3 data-number="0.14" class="anchored" data-anchor-id="exercice-2"><span class="header-section-number">0.14</span> Exercice 2:</h3>
<ol type="1">
<li><p>Ajustez différents modèles de régression linéaires simples en fonction des variables explicatives disponibles pour tenter d’expliquer le prix du repas dans les restaurants Italiens.</p></li>
<li><p>Pour chacun des modèles, présentez l’équation estimée et discutez de la significativité des coefficients.</p></li>
<li><p>Pour chacun des modèles, interprétez chaque coefficient estimé dans le contexte du problème.</p></li>
<li><p>Parmi ces modèles ajustés, lequel vous semble le plus approprié?</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour prédire le prix en fonction du décor</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>modele_decor <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Décor, <span class="at">data =</span> resto)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle (coefficients, R², p-value, etc.)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_decor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Décor, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.9578  -4.4862  -0.4673   4.0422  18.5138 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -1.362      3.292  -0.414     0.68    
Décor          2.490      0.184  13.537   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.426 on 166 degrees of freedom
Multiple R-squared:  0.5247,    Adjusted R-squared:  0.5218 
F-statistic: 183.2 on 1 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot (nuage de points) pour visualiser la relation entre le décor et le prix</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resto, <span class="fu">aes</span>(<span class="at">x =</span> Décor, <span class="at">y =</span> Prix)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Points représentés par des cercles vides</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>  <span class="co"># Appliquer un thème épuré</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relation entre Décor et Prix"</span>, <span class="at">x =</span> <span class="st">"Décor"</span>, <span class="at">y =</span> <span class="st">"Prix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour prédire le prix en fonction du service</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>modele_service <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Service, <span class="at">data =</span> resto)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle (coefficients, R², p-value, etc.)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_service)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Service, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.6646  -4.7540  -0.2093   4.3368  26.2460 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11.9778     5.1093  -2.344   0.0202 *  
Service       2.8184     0.2618  10.764   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.153 on 166 degrees of freedom
Multiple R-squared:  0.4111,    Adjusted R-squared:  0.4075 
F-statistic: 115.9 on 1 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot  pour visualiser la relation entre le service et le prix</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resto, <span class="fu">aes</span>(<span class="at">x =</span> Service, <span class="at">y =</span> Prix)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relation entre Service et Prix"</span>, <span class="at">x =</span> <span class="st">"Service"</span>, <span class="at">y =</span> <span class="st">"Prix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire pour analyser l'effet de l'emplacement sur le prix</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>modele_emplacement <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Emplacement, <span class="at">data =</span> resto)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_emplacement)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Emplacement, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-25.0189  -7.0189  -0.0189   5.9811  24.5645 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    40.435      1.163  34.770   &lt;2e-16 ***
Emplacement1    3.583      1.464   2.448   0.0154 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.157 on 166 degrees of freedom
Multiple R-squared:  0.03483,   Adjusted R-squared:  0.02902 
F-statistic: 5.991 on 1 and 166 DF,  p-value: 0.01542</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiser la relation entre l'emplacement et le prix avec un boxplot</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> resto, <span class="fu">aes</span>(<span class="at">x =</span> Emplacement, <span class="at">y =</span> Prix)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span>  </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>  </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution des prix par emplacement"</span>, <span class="at">x =</span> <span class="st">"Emplacement"</span>, <span class="at">y =</span> <span class="st">"Prix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercice-3" class="level3" data-number="0.15">
<h3 data-number="0.15" class="anchored" data-anchor-id="exercice-3"><span class="header-section-number">0.15</span> Exercice 3</h3>
<ol type="1">
<li><p>Estimez le modèle de régression linéaire multiple pour expliquer le prix d’un repas dans un restaurant italien à New York en utilisant toutes les variables disponibles.</p></li>
<li><p>Donnez la droite de régression estimée.</p></li>
<li><p>Interprétez les coefficients dans le contexte du problème.</p></li>
<li><p>Le modèle est-il globalement significatif?</p></li>
<li><p>Est-ce que toutes les variables contribuent significativement dans ce modèle multiple pour expliquer le prix d’un repas dans un restaurant italien à New York?</p></li>
<li><p>Quel pourcentage de la variabilité des prix d’un repas dans un restaurant italien à New York est expliquée par ce modèle?</p></li>
</ol>
<p><strong>Le modèle complet</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire multiple pour prédire le prix en fonction de plusieurs variables explicatives</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>modele_complet_resto <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Qualité <span class="sc">+</span> Décor <span class="sc">+</span> Service <span class="sc">+</span> Emplacement, <span class="at">data =</span> resto)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_complet_resto)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Qualité + Décor + Service + Emplacement, 
    data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.0465  -3.8837   0.0373   3.3942  17.7491 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -24.023800   4.708359  -5.102 9.24e-07 ***
Qualité        1.538120   0.368951   4.169 4.96e-05 ***
Décor          1.910087   0.217005   8.802 1.87e-15 ***
Service       -0.002727   0.396232  -0.007   0.9945    
Emplacement1   2.068050   0.946739   2.184   0.0304 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.738 on 163 degrees of freedom
Multiple R-squared:  0.6279,    Adjusted R-squared:  0.6187 
F-statistic: 68.76 on 4 and 163 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="régression-avec-variable-service-seulement" class="level3" data-number="0.16">
<h3 data-number="0.16" class="anchored" data-anchor-id="régression-avec-variable-service-seulement"><span class="header-section-number">0.16</span> Régression avec variable service seulement</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle de régression pour la variable Service</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_service)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Service, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.6646  -4.7540  -0.2093   4.3368  26.2460 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11.9778     5.1093  -2.344   0.0202 *  
Service       2.8184     0.2618  10.764   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.153 on 166 degrees of freedom
Multiple R-squared:  0.4111,    Adjusted R-squared:  0.4075 
F-statistic: 115.9 on 1 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Il n’y a pas de lien linéaire significatif entre la variable service et le prix quand elle est seul.</p>
</section>
<section id="régression-avec-service-qualité-et-décor." class="level3" data-number="0.17">
<h3 data-number="0.17" class="anchored" data-anchor-id="régression-avec-service-qualité-et-décor."><span class="header-section-number">0.17</span> Régression avec service, qualité et décor.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire multiple pour prédire le prix en fonction du service, de la qualité et du décor</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>modele_service_qualite_decor <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Service <span class="sc">+</span> Qualité <span class="sc">+</span> Décor, <span class="at">data =</span> resto)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_service_qualite_decor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prix ~ Service + Qualité + Décor, data = resto)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.8440  -3.7039  -0.1525   3.6218  19.0576 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -24.6409     4.7536  -5.184 6.33e-07 ***
Service       0.1350     0.3957   0.341    0.733    
Qualité       1.5556     0.3731   4.170 4.93e-05 ***
Décor         1.8473     0.2176   8.491 1.17e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.803 on 164 degrees of freedom
Multiple R-squared:  0.617, Adjusted R-squared:   0.61 
F-statistic: 88.06 on 3 and 164 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Il y a un lien linéaire significatif entre la variable service et le prix, mais cette variable ne contribue plus(p-value=0.733) à expliquer le prix une fois que l’on tient compte du décor et de la qualité.</p>
<p>La variable Service est très corrélée à la variable qualité. (à suivre…)</p>
</section>
<section id="modélisation-avec-variables-explicatives-catégorielles" class="level3" data-number="0.18">
<h3 data-number="0.18" class="anchored" data-anchor-id="modélisation-avec-variables-explicatives-catégorielles"><span class="header-section-number">0.18</span> Modélisation avec variables explicatives catégorielles</h3>
<p><strong>Rappel:</strong> En régression linéaire simple ou multiple, la variable dépendante Y doit être <strong>quantitative</strong> mais les prédicteurs (les variables indépendantes X) peuvent être de n’importe quel type: quantitatif, nominal, ordinal, binaire.</p>
<ul>
<li><p><strong>Variable binaire</strong><em>:</em> Pour utiliser une variable binaire, il suffit de créer une variable indicatrice qui prend les valeurs 0 et 1 et l’inclure dans le modèle.</p></li>
<li><p><strong>Variable nominale</strong><em>:</em> Pour utiliser une variable nominale ayant k valeurs possibles, il suffit de créer (k – 1) variables indicatrices et de les inclure dans le modèle.</p></li>
<li><p><strong>Variable ordinale</strong><em>:</em> Selon la situation, une variable ordinale pourra être utilisée comme une variable quantitative, en l’ajoutant telle quelle au modèle, ou bien comme une variable catégorielle, en la modélisant à l’aide de variables indicatrices comme pour une variable nominale. Le choix dépendra de la variable elle-même <em>et du nombre de modalités qu’elle possède</em>.</p></li>
</ul>
</section>
<section id="mise-en-situation-2" class="level3" data-number="0.19">
<h3 data-number="0.19" class="anchored" data-anchor-id="mise-en-situation-2"><span class="header-section-number">0.19</span> Mise en situation 2</h3>
<p>Une importante chaîne de magasins compte un très grand nombre de succursales réparties à travers le Canada et les États-Unis. La direction dispose de certaines données sur un échantillon de 342 succursales.</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 95%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Profit</td>
<td style="text-align: left;">Profit de l’année 2016 (en milliers de dollars). Un profit négatif correspond à une perte.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Budget</td>
<td style="text-align: left;">Budget publicitaire de l’année 2016 (en milliers de dollars).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Local</td>
<td style="text-align: left;">Évaluation globale de la localisation de la succursale (score de 0 à 100). Calculé en fonction de plusieurs critères tels que la taille de la population environnante, le revenu médian, l’accès par transport en commun et les places de stationnement.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Direction</td>
<td style="text-align: left;">Indice de la qualité de la direction de la succursale : 1 = acceptable, 2 = bon, 3 = excellent.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comp</td>
<td style="text-align: left;">Présence d’un compétiteur dans un rayon de 5 km : 0 = pas de compétiteur, 1 = présence d’un compétiteur.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Loc_categ</td>
<td style="text-align: left;">Variable indicatrice dérivée de ‘Local’ : 1 si Local &gt;= 50 (bonne localisation), 0 sinon.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Importer le jeu de données</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>magasins <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Magasins.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercice-4" class="level3" data-number="0.20">
<h3 data-number="0.20" class="anchored" data-anchor-id="exercice-4"><span class="header-section-number">0.20</span> Exercice 4</h3>
<ol type="1">
<li><p>Donnez le type de chaque variable dans la base de données.</p></li>
<li><p>Ajustez un modèle de régression linéaire multiple pour expliquer la variable Profit en utilisant uniquement les variables Budget et Direction (modèle 1). Interprétez les coefficients estimés obtenus.</p></li>
<li><p>Ajustez un modèle de régression linéaire multiple pour expliquer la variable Profit incluant toutes les variables dans le modèle (modèle 2). Interprétez les coefficients estimés obtenus.</p></li>
<li><p>Quelle variable explicative semble avoir l’impact le plus important sur le Profit dans le modèle 2?</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variable...Type</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Quantitative</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Qualitative.nominale</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Qualitative.ordinale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Profit</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Budget</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Local</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Direction</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Comp</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; background-color: lightblue !important;">Loc_categ</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="démarche-et-solution" class="level3" data-number="0.21">
<h3 data-number="0.21" class="anchored" data-anchor-id="démarche-et-solution"><span class="header-section-number">0.21</span> Démarche et solution</h3>
<ul>
<li><p>La variable Direction est ordinale mais ne comporte que trois modalités, on va donc créer deux variables indicatrices pour deux des trois modalités). La catégorie omise sera notre catégorie de référence.</p></li>
<li><p>Les variables Comp et Loc_categ peuvent être introduites telles qu’elles dans le modèle (attention si on décide de choisir la variable locale dans le modèle, on n’utilise plus Loc_categ).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir les variables catégorielles en facteurs</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>magasins<span class="sc">$</span>Direction <span class="ot">&lt;-</span> <span class="fu">factor</span>(magasins<span class="sc">$</span>Direction)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#magasins$Comp &lt;- as.factor(magasins$Comp)</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Redéfinir la modalité 1 comme modalité de référence</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(magasins<span class="sc">$</span>Direction) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">3</span>, <span class="at">base =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercice-4--question-2-modèle-1" class="level4" data-number="0.21.1">
<h4 data-number="0.21.1" class="anchored" data-anchor-id="exercice-4--question-2-modèle-1"><span class="header-section-number">0.21.1</span> Exercice 4- Question 2: modèle 1</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire multiple pour prédire le profit en fonction du budget et de la direction</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>modele_magasin1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget <span class="sc">+</span> Direction, <span class="at">data =</span> magasins)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_magasin1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Direction, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-226.79  -58.39  -14.58   40.88  323.58 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -17.8348    19.2117  -0.928 0.353898    
Budget        2.0269     0.2544   7.967 2.51e-14 ***
Direction2   28.0467    12.7187   2.205 0.028116 *  
Direction3   49.7672    13.6513   3.646 0.000309 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 90.22 on 338 degrees of freedom
Multiple R-squared:  0.1779,    Adjusted R-squared:  0.1706 
F-statistic: 24.38 on 3 and 338 DF,  p-value: 2.636e-14</code></pre>
</div>
</div>
<p>Le profit moyen estimé pour un magasin n’ayant aucun budget publicitaire (Budget=0) et une appréciation jugée « acceptable » du mode de direction (Direction=1; ie, Bon=0 et Excellent=0) est de -17.835 milliers de dollars.</p>
</section>
<section id="exercice-4--question-2-interprétation-des-coefficients" class="level4" data-number="0.21.2">
<h4 data-number="0.21.2" class="anchored" data-anchor-id="exercice-4--question-2-interprétation-des-coefficients"><span class="header-section-number">0.21.2</span> Exercice 4- Question 2: interprétation des coefficients</h4>
<p><em>Budget:</em> Toute chose étant égale par ailleurs (TCEPA), selon le modèle ajusté le profit moyen augmente en moyenne de 2.027$ pour chaque augmentation d’un dollar du budget publicitaire.</p>
<p><em>Direction:</em> Introduite par le biais de deux variables indicatrices; Bon et Excellent</p>
<p><em>Excellent:</em> On estime la différence moyenne de profit entre un magasin ayant un mode de gestion jugé «&nbsp;Excellent&nbsp;» et un magasin ayant un mode de gestion jugé «&nbsp;Acceptable&nbsp;» à 49 767 $ une fois que l’on contrôle pour le niveau du budget publicitaire (TCEPA).</p>
<p><em>Bon</em>: On estime la différence moyenne de profit entre un magasin ayant un mode de gestion jugé «&nbsp;Bon&nbsp;» et un magasin ayant un mode de gestion jugé «&nbsp;Acceptable&nbsp;» à 28 047 $ une fois que l’on contrôle pour le niveau du budget publicitaire (TCEPA).</p>
<p><span class="math display">\[
\begin{aligned}
\text{Lorsque } \text{Direction} = 1, &amp; \quad \hat{y} = -17.835 + 2.027 \times \text{Budget} \\
\text{Lorsque } \text{Direction} = 2, &amp; \quad \hat{y} = (-17.835 + \mathbf{28.047}) + 2.027 \times \text{Budget} \\
\text{Lorsque } \text{Direction} = 3, &amp; \quad \hat{y} = (-17.835 + \mathbf{49.767}) + 2.027 \times \text{Budget}
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot pour visualiser la relation entre Budget et Profit selon la Direction</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(magasins, <span class="fu">aes</span>(<span class="at">x =</span> Budget, <span class="at">y =</span> Profit, <span class="at">color =</span> Direction)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span>  </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Budget"</span>, <span class="at">y =</span> <span class="st">"Profit"</span>, <span class="at">title =</span> <span class="st">"Relation entre Budget et Profit selon la Direction"</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercice-4--question-3-modèle-2" class="level4" data-number="0.21.3">
<h4 data-number="0.21.3" class="anchored" data-anchor-id="exercice-4--question-3-modèle-2"><span class="header-section-number">0.21.3</span> Exercice 4- Question 3: Modèle 2</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire multiple pour prédire le profit en fonction du budget, de la direction, </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># de la localisation et de la présence d’un compétiteur</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>modele_magasin2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget <span class="sc">+</span> Direction <span class="sc">+</span> Local <span class="sc">+</span> Comp, <span class="at">data =</span> magasins)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_magasin2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Direction + Local + Comp, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-184.36  -56.37  -14.98   48.09  301.28 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -38.0864    23.5819  -1.615   0.1072    
Budget        2.1017     0.2429   8.651  &lt; 2e-16 ***
Direction2   27.1729    12.1980   2.228   0.0266 *  
Direction3   53.3997    13.0313   4.098 5.23e-05 ***
Local         0.4590     0.1932   2.375   0.0181 *  
Comp        -57.4070    10.2958  -5.576 5.07e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 86.02 on 336 degrees of freedom
Multiple R-squared:  0.2572,    Adjusted R-squared:  0.2461 
F-statistic: 23.27 on 5 and 336 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Le profit moyen estimé pour un magasin, n’ayant aucun budget publicitaire (Budget=0), une localisation médiocre (Local=0), une appréciation du mode de direction jugée «&nbsp;acceptable&nbsp;» (Bon=0 et Excellent=0) et sans compétiteur dans un rayon de 5km, a (-38.086 $).</p>
<p><strong>Mise en garde:</strong> Si une des variables indicatrices s’avère significative et pas les autres, il serait dangereux d’exclure les variables indicatrices non significatives associée aux modalités de la variable qualitative recodée parce que l’interprétation des bêtas en sera altérée.</p>
</section>
<section id="exercice-4-question-4-comparaison-des-effets" class="level4" data-number="0.21.4">
<h4 data-number="0.21.4" class="anchored" data-anchor-id="exercice-4-question-4-comparaison-des-effets"><span class="header-section-number">0.21.4</span> Exercice 4-Question 4: Comparaison des effets</h4>
<ul>
<li><p>Comme la taille de chaque paramètre estimé bᵢ dépend de l’unité associée à la variable Xᵢ, les coefficients estimés ne sont donc pas comparables (si les unités de mesures sont différentes d’une variable à une autre).</p></li>
<li><p>La variable budget est exprimée en dollars, la localisation est un score allant de 0 à 100, la variable Comp est une indicatrice sans unité…</p></li>
<li><p>On peut également estimer les coefficients standardisés β dans R à l’aide de la fonction <code>lm.beta()</code></p></li>
<li><p>NB: une variable standardisée s’obtient en retranchant de la variable d’origine sa moyenne et en la divisant pas son écart type.</p></li>
<li><p><strong>Interprétation d’un coefficient standardisé</strong>: l’augmentation de Y, en moyenne, lorsque la variable explicative augmente de un écart type si le tout demeure constant.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Installer et charger le package lm.beta </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("lm.beta", repos = "https://cloud.r-project.org/")</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lm.beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'lm.beta' a été compilé avec la version R 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenir les coefficients standardisés</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>modele_standardise_magasin2 <span class="ot">&lt;-</span> <span class="fu">lm.beta</span>(modele_magasin2)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_standardise_magasin2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Direction + Local + Comp, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-184.36  -56.37  -14.98   48.09  301.28 

Coefficients:
            Estimate Standardized Std. Error t value Pr(&gt;|t|)    
(Intercept) -38.0864           NA    23.5819  -1.615   0.1072    
Budget        2.1017       0.4088     0.2429   8.651  &lt; 2e-16 ***
Direction2   27.1729       0.1371    12.1980   2.228   0.0266 *  
Direction3   53.3997       0.2509    13.0313   4.098 5.23e-05 ***
Local         0.4590       0.1124     0.1932   2.375   0.0181 *  
Comp        -57.4070      -0.2640    10.2958  -5.576 5.07e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 86.02 on 336 degrees of freedom
Multiple R-squared:  0.2572,    Adjusted R-squared:  0.2461 
F-statistic: 23.27 on 5 and 336 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="test-de-significativité-globale-pour-un-sous-ensemble-de-variable" class="level3" data-number="0.22">
<h3 data-number="0.22" class="anchored" data-anchor-id="test-de-significativité-globale-pour-un-sous-ensemble-de-variable"><span class="header-section-number">0.22</span> Test de significativité globale pour un sous ensemble de variable</h3>
<ul>
<li><p>Lorsqu’une variable qualitative comporte plusieurs modalités (k), il est possible de tester son effet global avant de la transformer en <strong>(k-1) variables indicatrices</strong> en utilisant un <strong>modèle linéaire</strong> dans R avec la fonction <code>lm()</code>.</p>
<p>On applique ensuite un <strong>test ANOVA de type III</strong> sur le modèle pour évaluer la <strong>significativité globale</strong> de la variable.</p></li>
<li><p>Exemple si l’effet de la variable Direction s’avère significatif au-delà du Budget, on procède par la suite à la création de variables indicatrices pour les inclure au modèle.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Le chargement a nécessité le package : carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.sum"</span>, <span class="st">"contr.poly"</span>))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Test ANOVA III</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>Anova_magasin2<span class="ot">&lt;-</span><span class="fu">Anova</span>(modele_magasin1,<span class="at">type=</span><span class="st">"III"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>Anova_magasin2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: Profit
             Sum Sq  Df F value    Pr(&gt;F)    
(Intercept)    7016   1  0.8618  0.353898    
Budget       516731   1 63.4764 2.509e-14 ***
Direction    108403   2  6.6582  0.001458 ** 
Residuals   2751499 338                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="modèle-hiérarchique-ou-régression-séquentielle" class="level3" data-number="0.23">
<h3 data-number="0.23" class="anchored" data-anchor-id="modèle-hiérarchique-ou-régression-séquentielle"><span class="header-section-number">0.23</span> Modèle hiérarchique ou régression séquentielle</h3>
<p>«Le terme « régression hiérarchique » fait référence à la situation où le chercheur décide d’ajuster des modèles emboîtés en entrant tour à tour <em>des blocs de variables</em> dans le modèle et ce, <em>afin de tester des hypothèses de recherche spécifiques</em>. Souvent, les variables formant le premier bloc sont les variables de contrôle. Les variables des blocs suivants sont alors souvent les variables d’intérêt.» Citation tirée du recueil Techniques Quantitatives en marketing de Denis Larocque</p>
<p><strong><em>Exemples:</em></strong></p>
<p><strong>1) Tester globalement l’effet du mode de gestion (Direction) lorsqu’on tient compte du Budget publicitaire.</strong></p>
<p>Premier Bloc: variables de contrôle: Budget</p>
<p>Deuxième Bloc: variables d’intérêt: Direction (introduite par l’entremise de deux variables indicatrices)</p>
<p><strong>2) Est-ce que la variable localisation reste significative une fois que l’on contrôle pour le budget publicitaire, le mode de gestion et la présence ou non de compétiteurs?</strong></p>
<p>Premier Bloc: variables de contrôle: Budget, Direction (introduite par l’entremise de deux variables indicatrices) et Comp</p>
<p>Deuxième Bloc: variables d’intérêt: Local</p>
<p><strong>Exemples:</strong></p>
<ol type="1">
<li>Tester globalement l’effet du mode de gestion (Direction) lorsqu’on tient compte du Budget publicitaire.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour analyser l'effet du budget sur le profit</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>modele_budget <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget, <span class="at">data =</span> magasins)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_budget)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-225.24  -61.93  -15.06   46.22  321.78 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.9601    16.3193   0.917     0.36    
Budget        1.9613     0.2578   7.609 2.74e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 91.71 on 340 degrees of freedom
Multiple R-squared:  0.1455,    Adjusted R-squared:  0.143 
F-statistic:  57.9 on 1 and 340 DF,  p-value: 2.741e-13</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire multiple pour analyser l'effet du budget et de la direction sur le profit</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>modele_budget_direction <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget <span class="sc">+</span> Direction, <span class="at">data =</span> magasins)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_budget_direction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Direction, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-226.79  -58.39  -14.58   40.88  323.58 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -17.8348    19.2117  -0.928 0.353898    
Budget        2.0269     0.2544   7.967 2.51e-14 ***
Direction2   28.0467    12.7187   2.205 0.028116 *  
Direction3   49.7672    13.6513   3.646 0.000309 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 90.22 on 338 degrees of freedom
Multiple R-squared:  0.1779,    Adjusted R-squared:  0.1706 
F-statistic: 24.38 on 3 and 338 DF,  p-value: 2.636e-14</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer un test ANOVA sur le modele budget</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>Anova_budget <span class="ot">&lt;-</span> <span class="fu">anova</span>(modele_budget)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats de l'ANOVA</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>test_anova_direction<span class="ot">=</span><span class="fu">Anova</span>(modele_budget,modele_budget_direction)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>Anova_budget</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Profit
           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
Budget      1  486992  486992  57.896 2.741e-13 ***
Residuals 340 2859902    8411                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>test_anova_direction</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: Profit
           Sum Sq  Df F value    Pr(&gt;F)    
Budget     486992   1  59.823 1.205e-13 ***
Residuals 2751499 338                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>P-value=0.01 permet de répondre au test d’hypothèse relatif à un sous ensemble de paramètres dans le modèle (à ne pas confondre avec le test de significativité globale de tous les paramètres du modèle):</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_{\text{excellent}} = \beta_{\text{bon}} = 0  \quad \text{(aucun changement significatif suite à l’ajout de la variable Direction : augmentation marginale non significative de } R^2 \text{)} \\
H_1 &amp;: \text{il y a au moins un } \beta \neq 0  \quad \text{(la variable Direction est significative une fois que l’on tient compte du budget : augmentation marginale significative)}
\end{aligned}
\]</span></p>
<p><em>Est-ce que la variable localisation reste significative une fois que l’on contrôle pour le budget publicitaire, le mode de gestion et la présence ou non de compétiteurs?</em></p>
</section>
<section id="méthodes-de-sélection-de-modèles-stepwise" class="level3" data-number="0.24">
<h3 data-number="0.24" class="anchored" data-anchor-id="méthodes-de-sélection-de-modèles-stepwise"><span class="header-section-number">0.24</span> Méthodes de Sélection de modèles (Stepwise)</h3>
<p>Plusieurs techniques de sélection du meilleur modèle sont disponibles dans R.</p>
<p>Sélection pas à pas en ajoutant une variable à la fois, en commençant par la plus significative (stepwise, forward)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle de régression linéaire avec toutes les variables explicatives</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model_magasin_complet <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget<span class="sc">+</span>Local<span class="sc">+</span>Direction<span class="sc">+</span>Comp, <span class="at">data =</span> magasins)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression avec sélection de variables stepwise</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">step</span>(model_magasin_complet, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3052.86
Profit ~ Budget + Local + Direction + Comp

            Df Sum of Sq     RSS    AIC
&lt;none&gt;                   2486072 3052.9
- Local      1     41747 2527819 3056.6
- Direction  2    126020 2612091 3065.8
- Comp       1    230028 2716100 3081.1
- Budget     1    553761 3039832 3119.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le modèle final après sélection des variables</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>stepwise_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Local + Direction + Comp, data = magasins)

Coefficients:
(Intercept)       Budget        Local   Direction2   Direction3         Comp  
    -38.086        2.102        0.459       27.173       53.400      -57.407  </code></pre>
</div>
</div>
</section>
<section id="méthodes-de-sélection-de-modèles-backward" class="level3" data-number="0.25">
<h3 data-number="0.25" class="anchored" data-anchor-id="méthodes-de-sélection-de-modèles-backward"><span class="header-section-number">0.25</span> Méthodes de Sélection de modèles (Backward)</h3>
<p>Sélection à partir du modèle dans lequel toutes les variables sont incluses et en éliminant une variable à la fois en commençant par la moins significative (backward).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle de régression linéaire avec toutes les variables explicatives</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>model_magasin_complet <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> ., <span class="at">data =</span> magasins)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression avec sélection de variables backward</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>backward_model <span class="ot">&lt;-</span> <span class="fu">step</span>(model_magasin_complet, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=3054.76
Profit ~ Budget + Local + Direction + Comp + Loc_categ

            Df Sum of Sq     RSS    AIC
- Loc_categ  1       695 2486072 3052.9
&lt;none&gt;                   2485377 3054.8
- Local      1     22662 2508040 3055.9
- Direction  2    124633 2610010 3067.5
- Comp       1    230629 2716006 3083.1
- Budget     1    553650 3039027 3121.6

Step:  AIC=3052.86
Profit ~ Budget + Local + Direction + Comp

            Df Sum of Sq     RSS    AIC
&lt;none&gt;                   2486072 3052.9
- Local      1     41747 2527819 3056.6
- Direction  2    126020 2612091 3065.8
- Comp       1    230028 2716100 3081.1
- Budget     1    553761 3039832 3119.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le modèle final après sélection des variables</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>backward_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Local + Direction + Comp, data = magasins)

Coefficients:
(Intercept)       Budget        Local   Direction2   Direction3         Comp  
    -38.086        2.102        0.459       27.173       53.400      -57.407  </code></pre>
</div>
</div>
</section>
<section id="sélection-du-meilleur-modèle-selon-un-critère" class="level3" data-number="0.26">
<h3 data-number="0.26" class="anchored" data-anchor-id="sélection-du-meilleur-modèle-selon-un-critère"><span class="header-section-number">0.26</span> Sélection du meilleur modèle selon un critère</h3>
<ul>
<li><p>Construire tous les modèles possibles et choisir le meilleur sous-ensemble de variables selon un certain critère spécifique (ex: R² ajusté).</p></li>
<li><p>Si on a K prédicteurs, on peut construire (2ᵏ−1 ) modèles à comparer.</p></li>
<li><p>Plus k est grand, plus il devient difficile de procéder ainsi.</p></li>
</ul>
<p><strong>Exemple</strong></p>
<p>On dispose de 3 variables explicatives pour ajuster un modèle de régression linéaire. On peut ajuster donc 7 modèles différents et les comparer entre eux selon le R² ajusté.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparaison des modèles</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Modèles</th>
<th style="text-align: left;">R..ajusté</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Avec X1</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avec X2</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avec X3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avec X1 et X2</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avec X1 et X3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avec X2 et X3</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avec X1, X2 et X3</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interaction" class="level3" data-number="0.27">
<h3 data-number="0.27" class="anchored" data-anchor-id="interaction"><span class="header-section-number">0.27</span> Interaction</h3>
<ul>
<li><p>Il y a interaction entre deux variables explicatives Xᵢ et Xⱼ si l’effet d’une de ces variables sur les variations de Y n’est pas le même selon la valeur de l’autre variable et vice versa.</p></li>
<li><p>Il y a une interaction entre deux variables lorsque l’effet entre les deux variables est multiplicatif et pas uniquement additif.</p></li>
<li><p>l’interaction entre les deux variables Xᵢ et Xⱼ se fait via la création d’une nouvelle variable égale au produit des deux.</p></li>
<li><p>On ajoute ensuite au modèle le produit (Xᵢ * Xⱼ ) en plus des variables explicatives Xᵢ et Xⱼ.</p></li>
<li><p>On teste le paramètre associé à l’interaction pour évaluer sa significativité.</p></li>
</ul>
<p><strong>Remarque:</strong> Le choix des termes d’interaction à inclure dans le modèle se fait si on soupçonne un effet multiplicatif entre les variables.</p>
</section>
<section id="exemple-pour-illustrer-linteraction" class="level3" data-number="0.28">
<h3 data-number="0.28" class="anchored" data-anchor-id="exemple-pour-illustrer-linteraction"><span class="header-section-number">0.28</span> Exemple pour illustrer l’interaction</h3>
<ul>
<li><p>On soupçonne que l’effet du budget sur le profit n’est pas le même selon que l’on soit dans une zone où les compétiteurs y sont ou pas.</p></li>
<li><p>Pour répondre à cette hypothèse, on va ajuster un modèle de régression linéaire multiple pour expliquer le profit en fonction du budget publicitaire, de comp et d’une variable d’intéraction <strong>budget_comp= Budget*comp</strong>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modèle de régression linéaire avec interaction entre Budget et Compétiteur</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>modele_magasin3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Profit <span class="sc">~</span> Budget <span class="sc">+</span> Comp <span class="sc">+</span> Budget <span class="sc">*</span> Comp, <span class="at">data =</span> magasins)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_magasin3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Profit ~ Budget + Comp + Budget * Comp, data = magasins)

Residuals:
    Min      1Q  Median      3Q     Max 
-180.57  -58.37  -11.26   48.66  307.96 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  22.5274    18.4977   1.218    0.224    
Budget        2.1003     0.2941   7.142 5.68e-12 ***
Comp        -34.9596    35.3004  -0.990    0.323    
Budget:Comp  -0.3190     0.5524  -0.577    0.564    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 88.51 on 338 degrees of freedom
Multiple R-squared:  0.2088,    Adjusted R-squared:  0.2018 
F-statistic: 29.73 on 3 and 338 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>𝑙𝑒 𝑚𝑜𝑑è𝑙𝑒 𝑎𝑗𝑢𝑠𝑡é 𝑒𝑠𝑡 : 𝑦=22.527+2.1 ∗ 𝐵𝑢𝑑𝑔𝑒𝑡−34.96 ∗ 𝐶𝑜𝑚𝑝−𝟎.𝟑𝟏𝟗 ∗ (𝑏𝑢𝑑𝑔𝑒𝑡∗𝐶𝑜𝑚𝑝)</p>
<p>Il est plus facile d’interpréter ce modèle selon la variable Comp:</p>
<p>𝑃𝑟𝑜𝑓𝑖𝑡 (𝑐𝑜𝑚𝑝=0)=22.527+2.1∗𝑏𝑢𝑑𝑔𝑒𝑡</p>
<p>𝑃𝑟𝑜𝑓𝑖𝑡 (𝑐𝑜𝑚𝑝=1)=(22.527−34.960)+(2.1−0.319) ∗ 𝑏𝑢𝑑𝑔𝑒𝑡</p>
<p>Dans cet exemple:</p>
<ol type="1">
<li><p>l’ordonnée à l’origine (comp=1) n’est pas significativement différente de celle de (comp=0) (p-value=0.323).</p></li>
<li><p>l’effet du budget est le même peut importe se situe le magasin (p-value=0.564).</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot (nuage de points) pour visualiser la relation entre Budget et Profit selon la présence d'un compétiteur</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(magasins, <span class="fu">aes</span>(<span class="at">x =</span> Budget, <span class="at">y =</span> Profit, <span class="at">color =</span> Comp)) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span>  </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Budget"</span>, <span class="at">y =</span> <span class="st">"Profit"</span>, <span class="at">title =</span> <span class="st">"Relation entre Budget et Profit selon la Présence d'un Compétiteur"</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The following aesthetics were dropped during statistical transformation:
colour.
ℹ This can happen when ggplot fails to infer the correct grouping structure in
  the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
  variable into a factor?</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multicolinéarité" class="level3" data-number="0.29">
<h3 data-number="0.29" class="anchored" data-anchor-id="multicolinéarité"><span class="header-section-number">0.29</span> Multicolinéarité</h3>
<ul>
<li><p>Si le seul but de la régression est de déterminer un modèle pour faire de la prévision, la multicolinéarité n’est pas si grave, mais si l’objectif est de construire un modèle explicatif (parcimonieux) pour analyser le comportement de Y en fonction des variables explicatives pertinentes, alors le problème est plus grave car les estimations des paramètres est <strong>moins précise</strong> (écart type élevé).</p></li>
<li><p>Si deux variables explicatives sont <strong>fortement corrélées</strong> (|𝒓|&gt;𝟎.𝟖), <strong>alors on peut se débarrasser de l’une de ces deux variables</strong>.</p></li>
<li><p>Le diagnostic de la multicolinéarité par le biais du coefficient de corrélation bivarié (deux par deux) n’est pas suffisant car plusieurs variables explicatives peuvent être très corrélées à une <em>combinaison linéaire</em> des autres variables explicatives.</p></li>
</ul>
<p>Les autres variables explicatives, comme Qualité et Décor, sont respectivement fortement (|r| = 0.795) et modérément (|r| = 0.645) corrélées avec la variable Service. (Voir le tableau de corrélation plus haut.)</p>
</section>
<section id="diagnostic-de-la-multicolinéarité" class="level3" data-number="0.30">
<h3 data-number="0.30" class="anchored" data-anchor-id="diagnostic-de-la-multicolinéarité"><span class="header-section-number">0.30</span> Diagnostic de la multicolinéarité</h3>
<p><strong>Le «&nbsp;Variance inflation factor&nbsp;» noté VIF</strong></p>
<p>Pour une variable explicative donnée Xᵢ, <span class="math display">\[ VIF(i) = \frac{1}{1 - R^2(i)} \]</span><br>
𝑜ù R²(𝑖) est le coeff de determination du modèle ajusté en regressant Xᵢ en fonction de toutes les autres variables explicatives.</p>
<p>Règle générale un VIF &gt; 10 signale un problème de multicolinéarité.</p>
<p>Exemple: Un VIF=5 implique un R² (𝑖)= 0.8. 80% de la variabilité observée dans Xᵢ est expliquée par les autres variables explicatives.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger la bibliothèque </span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer le VIF des variables explicatives du modèle pour détecter la colinéarité</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modele_complet_resto)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Qualité       Décor     Service Emplacement 
   2.714261    1.744851    3.558735    1.064985 </code></pre>
</div>
</div>
<p>On ne détecte pas de problème de multicolinéarité dans notre exemple car les VIF&lt;10.</p>
</section>
<section id="validité-du-modèle-de-régression-linéaire" class="level3" data-number="0.31">
<h3 data-number="0.31" class="anchored" data-anchor-id="validité-du-modèle-de-régression-linéaire"><span class="header-section-number">0.31</span> Validité du modèle de régression linéaire</h3>
<p>La validité du modèle de régression linéaire repose sur 4 hypothèses:</p>
<p><em>Hypothèse 1 :</em> Les erreurs ɛᵢ sont de moyenne nulle (condition de linéarité du modèle);</p>
<p><em>Hypothèse 2 :</em> La variance des erreurs reste constante;</p>
<p><em>Hypothèse 3 :</em> Les erreurs ɛᵢ sont indépendantes (méthodes d’échantillonnage);</p>
<p><em>Hypothèse 4 :</em> Les erreurs ɛᵢ sont distribuées selon une loi Normale (plus l’échantillon est « grand », moins cette condition est importante);</p>
<p>On limitera notre analyse des résidus (hypothèses 1,2 et 4), dans le cadre de ce cours, à un examen graphique de la distribution des erreurs standardisées en fonction des variables explicatives.</p>
</section>
<section id="étapes-pour-valider-le-modèle" class="level3" data-number="0.32">
<h3 data-number="0.32" class="anchored" data-anchor-id="étapes-pour-valider-le-modèle"><span class="header-section-number">0.32</span> Étapes pour valider le modèle</h3>
<p>Modèle Profit=−𝟑𝟖.𝟎𝟖𝟔+𝟐.𝟏𝟎𝟐 ∗ 𝐵𝑢𝑑𝑔𝑒𝑡−𝟓𝟕.𝟒𝟎𝟕 ∗ 𝐶𝑜𝑚𝑝+𝟎.𝟒𝟓𝟗 ∗ 𝐿𝑜𝑐𝑎𝑙+𝟐𝟕.𝟏𝟕𝟑 ∗𝐵𝑜𝑛+𝟓𝟑.𝟒 ∗ 𝐸𝑥𝑐𝑒𝑙𝑙𝑒𝑛𝑡</p>
<p><em>Première étape:</em> calculer les erreurs standardisées.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les valeurs prédictives standardisées du modèle</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>magasins<span class="sc">$</span>valeurs_predites_std <span class="ot">&lt;-</span> <span class="fu">scale</span>(<span class="fu">predict</span>(modele_magasin2))</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les résidus standardisés du modèle</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>magasins<span class="sc">$</span>residus_std <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(modele_magasin2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Deuxième étape:</em> Construire les graphiques des résidus en fonction des variables explicatives.</p>
<ul>
<li><p>Si X est continue —— Scatterplot (nuage de points)</p></li>
<li><p>Si X est catégérielle —— Boxplot par modalité(groupe)</p></li>
</ul>
<p>Les points doivent être disposés aléatoirement dans le graphique (aucun pattern anormal).</p>
<p><em>Troisième étape</em>: construire l’histogramme des résidus standardisés:</p>
<ul>
<li><p>la forme de l’histogramme doit se rapprocher d’une distribution normale autour d’une moyenne de 0 et d’écart type d’environ 1.</p></li>
<li><p>95% des résidus standardisés doivent être situés à [-2; 2] (règle empirique d’une distribution normale)</p></li>
</ul>
<p>Exemple: Validation avec <em>variable Budget</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot pour analyser la distribution des résidus standardisés en fonction du budget</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(magasins, <span class="fu">aes</span>(<span class="at">x =</span> Budget, <span class="at">y =</span> residus_std)) <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span> </span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Budget"</span>, <span class="at">y =</span> <span class="st">"Résidus standardisés"</span>, <span class="at">title =</span> <span class="st">"Graphique des résidus standardisés"</span>) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Exemple: Validation avec <em>variable Direction</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un boxplot pour analyser la distribution des résidus standardisés selon la Direction</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(magasins, <span class="fu">aes</span>(<span class="at">x =</span> Direction, <span class="at">y =</span> residus_std)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">median</span>(magasins<span class="sc">$</span>residus_std), <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span>   </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Direction"</span>, <span class="at">y =</span> <span class="st">"Résidus standardisés"</span>, <span class="at">title =</span> <span class="st">"Distribution des résidus standardisés par Direction"</span>) <span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Exemple: Validation avec l<em>’histogramme des erreurs</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracer l'histogramme des résidus standardisés avec une courbe de densité</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(magasins, <span class="fu">aes</span>(<span class="at">x =</span> residus_std)) <span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..),  </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">30</span>, </span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"khaki"</span>, </span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  </span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution des résidus standardisés"</span>,</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Résidus standardisés"</span>,</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densité"</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Conclusion</strong></p>
<p>Rien ne semble indiquer une violation aux hypothèses sur lesquelles repose le modèle de régression linéaire.</p>
<p>Si les hypothèses ne sont pas vérifier, pensez à transformer soit la variables dépendantes et/ou les variables indépendantes pour s’approcher de l’hypothèse de linéarité.</p>
</section>
<section id="transformation" class="level3" data-number="0.33">
<h3 data-number="0.33" class="anchored" data-anchor-id="transformation"><span class="header-section-number">0.33</span> Transformation</h3>
<p>Exemple:</p>
<p>Le fichier (fictif) epicerie.csv contient les informations suivantes sur 100 000 adultes vivant seuls et détenant une carte fidélité du supermarché&nbsp;:</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dépense</td>
<td style="text-align: left;">Le montant dépensé annuellement dans ce supermarché.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Revenu</td>
<td style="text-align: left;">Le revenu annuel net avant impôt de ce client.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Importer le jeu de données</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>epicerie <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"epicerie.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir log_revenu en numérique </span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>epicerie<span class="sc">$</span>log_revenu <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, epicerie<span class="sc">$</span>log_revenu))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En utilisant R, trouvez un bon modèle permettant de prévoir les dépenses à partir du revenu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot  pour visualiser la relation entre Revenu et Dépenses</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epicerie, <span class="fu">aes</span>(<span class="at">x =</span> Revenu, <span class="at">y =</span> Dépenses)) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Revenu"</span>, <span class="at">y =</span> <span class="st">"Dépenses"</span>, <span class="at">title =</span> <span class="st">"Relation entre Revenu et Dépenses"</span>) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour analyser l'effet du revenu sur les dépenses</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>modele_epicerie_revenu <span class="ot">&lt;-</span> <span class="fu">lm</span>(Dépenses <span class="sc">~</span> Revenu, <span class="at">data =</span> epicerie)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_epicerie_revenu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Dépenses ~ Revenu, data = epicerie)

Residuals:
    Min      1Q  Median      3Q     Max 
-3803.6  -361.4    46.1   422.0  2243.5 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.914e+03  5.426e+00   905.6   &lt;2e-16 ***
Revenu      4.420e-02  7.641e-05   578.5   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 636.4 on 99998 degrees of freedom
Multiple R-squared:  0.7699,    Adjusted R-squared:  0.7699 
F-statistic: 3.346e+05 on 1 and 99998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot  pour visualiser la relation entre le log du revenu et les dépenses</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(epicerie, <span class="fu">aes</span>(<span class="at">x =</span> log_revenu, <span class="at">y =</span> Dépenses)) <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  </span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Log(Revenu)"</span>, <span class="at">y =</span> <span class="st">"Dépenses"</span>, <span class="at">title =</span> <span class="st">"Relation entre le Log du Revenu et les Dépenses"</span>) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Régression linéaire simple pour analyser l'effet du log du revenu sur les dépenses</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>modele_epicerie_log_revenu <span class="ot">&lt;-</span> <span class="fu">lm</span>(Dépenses <span class="sc">~</span> log_revenu, <span class="at">data =</span> epicerie)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résumé du modèle </span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele_epicerie_log_revenu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Dépenses ~ log_revenu, data = epicerie)

Residuals:
    Min      1Q  Median      3Q     Max 
-2256.5  -337.2     1.1   337.8  2107.8 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22983.496     39.726  -578.6   &lt;2e-16 ***
log_revenu    2798.607      3.605   776.2   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 500.5 on 99998 degrees of freedom
Multiple R-squared:  0.8577,    Adjusted R-squared:  0.8577 
F-statistic: 6.025e+05 on 1 and 99998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="ajout-de-termes-polynomiaux" class="level3" data-number="0.34">
<h3 data-number="0.34" class="anchored" data-anchor-id="ajout-de-termes-polynomiaux"><span class="header-section-number">0.34</span> Ajout de termes polynomiaux</h3>
<ul>
<li><p>Une droite peut ne pas être adéquate pour modéliser la relation entre X et Y. L’utilisation de termes polynomiaux d’ordre 2 ou 3 peut améliorer la performance d’un modèle.</p></li>
<li><p>L’interprétation de ces termes demeure un défi. C’est la raison pour laquelle ce genre de manipulation est plus utilisé pour la construction de modèle prédictif.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot et ajuster une régression linéaire</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Régression Linéaire (Mauvais Ajustement ?)"</span>, <span class="at">x =</span> <span class="st">"x"</span>, <span class="at">y =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un scatter plot et ajuster une régression quadratique</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  </span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Régression Quadratique (Bon Ajustement ?)"</span>, <span class="at">x =</span> <span class="st">"x"</span>, <span class="at">y =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T5_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>