<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thème 7: Analyse de survie</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LIVRABLE_T7_files/libs/clipboard/clipboard.min.js"></script>
<script src="LIVRABLE_T7_files/libs/quarto-html/quarto.js"></script>
<script src="LIVRABLE_T7_files/libs/quarto-html/popper.min.js"></script>
<script src="LIVRABLE_T7_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LIVRABLE_T7_files/libs/quarto-html/anchor.min.js"></script>
<link href="LIVRABLE_T7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LIVRABLE_T7_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LIVRABLE_T7_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LIVRABLE_T7_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LIVRABLE_T7_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="LIVRABLE_T7_files/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">0.1</span> Introduction</a></li>
  <li><a href="#contexte-dapplication" id="toc-contexte-dapplication" class="nav-link" data-scroll-target="#contexte-dapplication"><span class="header-section-number">0.2</span> Contexte d’application</a></li>
  <li><a href="#cadre-général-danalyse" id="toc-cadre-général-danalyse" class="nav-link" data-scroll-target="#cadre-général-danalyse"><span class="header-section-number">0.3</span> Cadre général d’analyse</a></li>
  <li><a href="#pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" id="toc-pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" class="nav-link" data-scroll-target="#pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas"><span class="header-section-number">0.4</span> Pourquoi l’approche de régression linéaire ne fonctionne pas?</a></li>
  <li><a href="#mise-en-contexte" id="toc-mise-en-contexte" class="nav-link" data-scroll-target="#mise-en-contexte"><span class="header-section-number">0.5</span> Mise en contexte</a></li>
  <li><a href="#quelques-statistiques-descriptives" id="toc-quelques-statistiques-descriptives" class="nav-link" data-scroll-target="#quelques-statistiques-descriptives"><span class="header-section-number">0.6</span> Quelques statistiques descriptives</a></li>
  <li><a href="#analyse-de-survie" id="toc-analyse-de-survie" class="nav-link" data-scroll-target="#analyse-de-survie"><span class="header-section-number">0.7</span> Analyse de survie</a></li>
  <li><a href="#les-fonctions-utiles-en-analyse-de-survie" id="toc-les-fonctions-utiles-en-analyse-de-survie" class="nav-link" data-scroll-target="#les-fonctions-utiles-en-analyse-de-survie"><span class="header-section-number">0.8</span> Les fonctions utiles en analyse de survie</a></li>
  <li><a href="#les-fonctions-utiles-en-analyse-de-survie-1" id="toc-les-fonctions-utiles-en-analyse-de-survie-1" class="nav-link" data-scroll-target="#les-fonctions-utiles-en-analyse-de-survie-1"><span class="header-section-number">0.9</span> Les fonctions utiles en analyse de survie</a></li>
  <li><a href="#méthodes-destimation-non-paramétriques" id="toc-méthodes-destimation-non-paramétriques" class="nav-link" data-scroll-target="#méthodes-destimation-non-paramétriques"><span class="header-section-number">1</span> Méthodes d’estimation non paramétriques</a>
  <ul class="collapse">
  <li><a href="#estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" id="toc-estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" class="nav-link" data-scroll-target="#estimation-de-la-fonction-de-survie-lapproche-non-paramétrique"><span class="header-section-number">1.1</span> Estimation de la fonction de survie: l’approche non paramétrique</a></li>
  <li><a href="#approche-i-les-tables-de-survie-méthode-actuarielle" id="toc-approche-i-les-tables-de-survie-méthode-actuarielle" class="nav-link" data-scroll-target="#approche-i-les-tables-de-survie-méthode-actuarielle"><span class="header-section-number">1.2</span> Approche I: Les tables de survie (méthode actuarielle)</a></li>
  <li><a href="#approche-ii-lestimateur-de-kaplan-meier-km" id="toc-approche-ii-lestimateur-de-kaplan-meier-km" class="nav-link" data-scroll-target="#approche-ii-lestimateur-de-kaplan-meier-km"><span class="header-section-number">1.3</span> Approche II: L’estimateur de Kaplan-Meier (KM)</a></li>
  </ul></li>
  <li><a href="#méthode-destimation-semi-paramétrique-modèle-de-cox" id="toc-méthode-destimation-semi-paramétrique-modèle-de-cox" class="nav-link" data-scroll-target="#méthode-destimation-semi-paramétrique-modèle-de-cox"><span class="header-section-number">2</span> Méthode d’estimation semi-paramétrique: Modèle de Cox</a>
  <ul class="collapse">
  <li><a href="#introduction-au-modèle-de-cox" id="toc-introduction-au-modèle-de-cox" class="nav-link" data-scroll-target="#introduction-au-modèle-de-cox"><span class="header-section-number">2.1</span> Introduction au modèle de COX</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thème 7: Analyse de survie</h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level3" data-number="0.1">
<h3 data-number="0.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">0.1</span> Introduction</h3>
<p>L’analyse de survie est une branche de la statistique qui étudie le Temps qu’une unité statistique (individu, machine, entreprise, un employé, une franchise…) passe dans un état donné. L’analyse de survie doit son nom à ses premières applications concernant l’analyse de la durée de vie des individus en épidémiologie et en médecine (patients, malades…). L’analyse de survie s’applique de nos jours à presque tous les domaines: marketing, finance, comptabilité, économie, ingénierie…</p>
<p><strong>Exemples</strong></p>
<ul>
<li><p>Temps qu’un client reste abonné à un service offert par une entreprise (avant résiliation du contrat)</p></li>
<li><p>Temps qu’un employé au service de l’entreprise (avant licenciement ou avant de quitter l’emploi)</p></li>
<li><p>Temps qu’une entreprise demeure en opération sur le marché (avant de faire faillite)</p></li>
<li><p>Temps qu’un client demeure solvable (avant de déclarer faillite)</p></li>
<li><p>Temps qu’une machine demeure fonctionnelle (avant de tomber en panne)</p></li>
<li><p>Temps qu’une économie reste en croissance (avant la récession ou un crash boursier)</p></li>
</ul>
</section>
<section id="contexte-dapplication" class="level3" data-number="0.2">
<h3 data-number="0.2" class="anchored" data-anchor-id="contexte-dapplication"><span class="header-section-number">0.2</span> Contexte d’application</h3>
<p>L’analyse de survie est utilisée pour les données longitudinales qui rapportent (relatent) l’occurrence ou l’apparition d’un événement.</p>
<p><strong>Qu’est ce qu’un événement?</strong></p>
<p>Un événement est un changement qualitatif ou quantitatif qui survient dans le temps.</p>
<p><strong>Qualitatif:</strong></p>
<p>Changement d’un statut: faillite, divorce, mariage, le fait d’avoir un enfant, l’interruption d’un contrat, promotion…</p>
<p><strong>Quantitatif:</strong></p>
<p>Un changement soudain et significatif (plus important que les variations observées habituellement):</p>
<p>-Crash boursier définit par une baisse de plus de 20% des indices boursiers.</p>
<p>-Un enrichissement: une augmentation de plus de 50% du revenu. Dans ce cas la définition de l’événement est très arbitraire.</p>
</section>
<section id="cadre-général-danalyse" class="level3" data-number="0.3">
<h3 data-number="0.3" class="anchored" data-anchor-id="cadre-général-danalyse"><span class="header-section-number">0.3</span> Cadre général d’analyse</h3>
<p>On s’intéresse au TEMPS qu’un individu passe dans un état donné. On observe chaque individu à partir du moment où il entre dans l’état jusqu’à ce que l’une des deux situations suivantes survient:</p>
<ul>
<li><p>L’individu quitte l’état avant la fin de l’observation ( exemple: entreprise fait faillite)</p></li>
<li><p>L’étude se termine et l’individu est toujours dans l’état (exemple: entreprise encore en opération)</p></li>
</ul>
<p><em>NB: le début de l’état n’est pas nécessairement le même pour chaque individu mais il faut s’assurer que les critères utilisés pour définir le début et la fin d’un état soient les mêmes pour tous. Exemple: Si on étudie la durée de vie des entreprises avant la faillite, il faut définir à quel moment une entreprise nait et à quel moment elle meurt (lorsqu’elle déclare faillite ou lorsque la faillite est approuvée légalement?).</em></p>
<p>On notera par Temps, la variable «temps de survie» dans l’état. Pour chaque individu, la variable «Temps» est soit non censurée ou censurée.</p>
<p><strong>Le temps est non censuré</strong>: si l’individu a quitté l’état avant la fin de l’observation. Dans ce cas, on observele vrai temps passé dans l’état.</p>
<p><strong>Le temps est censuré</strong>: si l’individu est toujours dans l’état à la fin de l’observation. Dans ce cas, on n’observe qu’une borne inférieure du temps passé dans l’état. On notera par Censure, la variable qui indique si temps est censuré ou non.</p>
</section>
<section id="pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas" class="level3" data-number="0.4">
<h3 data-number="0.4" class="anchored" data-anchor-id="pourquoi-lapproche-de-régression-linéaire-ne-fonctionne-pas"><span class="header-section-number">0.4</span> Pourquoi l’approche de régression linéaire ne fonctionne pas?</h3>
<ul>
<li><p>Bien que la variable «Temps de survie» soit quantitative, le modèle de régression linéaire n’est pas adéquat pour comprendre les facteurs qui influencent le temps de survie des clients.</p></li>
<li><p>Le problème vient du fait que nous n’observons qu’une borne inférieure du temps de survie des données censurées.</p></li>
<li><p>Éliminer ces observations (les données censurées) de l’échantillon biaiserait le résultat et sous-estimerait le temps de survie des clients.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mise-en-contexte" class="level3" data-number="0.5">
<h3 data-number="0.5" class="anchored" data-anchor-id="mise-en-contexte"><span class="header-section-number">0.5</span> Mise en contexte</h3>
<p>Netflix s’intéresse aux facteurs influençant le temps qu’un client reste abonné à son service de vidéos en ligne et en streaming. Les données d’un échantillon de 500 clients se trouvent dans le fichier «Netflix.sav». Certains clients sont encore abonnés et d’autres ont déjà quitté.</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Temps</td>
<td style="text-align: left;">Durée en semaines de l’abonnement. Temps réel si le client a quitté, temps censuré sinon.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Censure</td>
<td style="text-align: left;">Indique si l’observation est censurée (1 = client encore abonné, 0 = client a quitté).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">Âge du client au début de l’abonnement.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sexe</td>
<td style="text-align: left;">Sexe du client (0 = Homme, 1 = Femme).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Région</td>
<td style="text-align: left;">Région de résidence actuelle du client (valeurs possibles : 1 à 5).</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail où se trouve le fichier de données</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Importer le jeu de données</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>netflix <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Netflix.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reconvertir les variables</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>censure <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(netflix<span class="sc">$</span>censure)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>sexe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(netflix<span class="sc">$</span>sexe)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>netflix<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(netflix<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="quelques-statistiques-descriptives" class="level3" data-number="0.6">
<h3 data-number="0.6" class="anchored" data-anchor-id="quelques-statistiques-descriptives"><span class="header-section-number">0.6</span> Quelques statistiques descriptives</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package dplyr</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives de la variable Temps en fonction de la variable Censure </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>stat_descriptive_temps <span class="ot">&lt;-</span> netflix <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(censure) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mediane =</span> <span class="fu">round</span>(<span class="fu">median</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_type =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">3</span>),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>stat_descriptive_temps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  censure     N Moyenne Mediane Ecart_type Minimum Maximum
    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;
1       0   334    96.2      98       33.8       2     216
2       1   166   131.      142       41.4      43     203</code></pre>
</div>
</div>
<ul>
<li><p>334 clients parmi les 500 ne sont plus abonnés. Seulement 166 clients sont encore abonnés.</p></li>
<li><p>La moyenne de 131.18 semaines d’abonnement (pour les clients actuels) n’est pas représentative car elle désigne la durée moyenne minimale de l’abonnement de ces clients.</p></li>
<li><p>La moyenne de 96.16 semaines (pour les clients ayant rompu l’abonnement) n’est pas non plus représentative car ces clients ne forment pas un échantillon représentatif de la clientèle de l’entreprise.</p></li>
<li><p>En analyse de survie, un aspect aussi simple que l’estimation de la moyenne devient très difficile.</p></li>
<li><p>La médiane est beaucoup plus représentative du comportement de la variable Temps dans ce contexte d’analyse.</p></li>
<li><p>50% des clients qui ont quitté (censure=0) s’abonnent à moins de 98 semaines chez Netflix.</p></li>
<li><p>50% des clients qui n’ont pas encore quitté (censure=1) ont un abonnement d’au moins 142 semaines.</p></li>
</ul>
</section>
<section id="analyse-de-survie" class="level3" data-number="0.7">
<h3 data-number="0.7" class="anchored" data-anchor-id="analyse-de-survie"><span class="header-section-number">0.7</span> Analyse de survie</h3>
<p>On peut utiliser l’analyse de survie pour :</p>
<ol type="1">
<li><p>Estimer le temps de survie dans un état donné.</p></li>
<li><p>Déterminer les variables qui influencent le temps de survie.</p></li>
<li><p>Prévoir le moment où l’individu va quitter cet état (complexe).</p></li>
</ol>
<p>Il existe trois approches pour analyser les données de survie:</p>
<ol type="1">
<li><p><strong>L’approche non paramétrique : Tables de survie et Kaplan-Meier</strong></p></li>
<li><p><strong>L’approche semi-paramétrique : Modèle à risques proportionnels de Cox.</strong></p></li>
<li><p><strong>L’approche paramétrique: Modèle de Weibull, log-normal, Gamma</strong></p></li>
</ol>
<p>Nous nous limiterons aux deux premières méthodes dans le cadre de ce cours.</p>
</section>
<section id="les-fonctions-utiles-en-analyse-de-survie" class="level3" data-number="0.8">
<h3 data-number="0.8" class="anchored" data-anchor-id="les-fonctions-utiles-en-analyse-de-survie"><span class="header-section-number">0.8</span> Les fonctions utiles en analyse de survie</h3>
<p>Rappel</p>
<p>Soit T une variable aléatoire représentant la durée de vie d’un individu. T désigne le temps passé dans cet état. <strong>En statistique</strong>, 2 fonctions sont utilisées pour décrire le comportement d’une variable aléatoire, soit sa fonction de densité et sa fonction de répartition.</p>
<ol type="1">
<li><p><u>La fonction de densité:</u> 𝒇( 𝒕) = 𝑷(𝑻 = 𝒕) : 𝒍𝒂 𝒑𝒓𝒐𝒃𝒂𝒃𝒊𝒍𝒊𝒕é 𝒅𝒆 𝒎𝒐𝒖𝒓𝒊𝒓 à 𝒍′𝒊𝒏𝒔𝒕𝒂𝒏𝒕 𝒕.</p></li>
<li><p><u>La fonction de répartition</u>: F (𝒕) = 𝑷(𝑻 ≤ 𝒕) : 𝒍𝒂 𝒑𝒓𝒐𝒃𝒂𝒃𝒊𝒍𝒊𝒕é 𝒅𝒆 𝒎𝒐𝒖𝒓𝒊𝒓 à 𝒍′𝒊𝒏𝒔𝒕𝒂𝒏𝒕 𝒕 𝒐𝒖 𝒂𝒗𝒂𝒏𝒕.</p></li>
</ol>
</section>
<section id="les-fonctions-utiles-en-analyse-de-survie-1" class="level3" data-number="0.9">
<h3 data-number="0.9" class="anchored" data-anchor-id="les-fonctions-utiles-en-analyse-de-survie-1"><span class="header-section-number">0.9</span> Les fonctions utiles en analyse de survie</h3>
<p>En analyse de survie, les deux fonctions vues précédemment sont un peu modifiées.</p>
<ol type="1">
<li>La fonction de survie: 𝑺(𝒕) = 𝑷(𝑻 ≥ 𝒕 )= 𝟏 − 𝑭 (𝒕)</li>
</ol>
<p><strong><em>La probabilité que le temps de survie soit supérieur ou égal à t.</em></strong></p>
<ol start="2" type="1">
<li>La fonction de risque (hasard fonction): h(𝒕) = 𝒇(𝒕) /𝒔(𝒕) = 𝑷 {𝑻 = 𝒕 |𝑻 ≥ 𝒕)</li>
</ol>
<p><strong><em>La probabilité de mourir à l’instant t, sachant que la personne a été vivante jusqu’à cet instant</em></strong></p>
<p>C’est la fonction de risque qui sera modélisée avec le modèle de régression de Cox qu’on abordera plus loin.</p>
<ul>
<li><p>En régression logistique, on modélise un Logit.</p></li>
<li><p>En analyse de survie, on modélise une fonction de risque.</p></li>
</ul>
</section>
<section id="méthodes-destimation-non-paramétriques" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="méthodes-destimation-non-paramétriques"><span class="header-section-number">1</span> Méthodes d’estimation non paramétriques</h2>
<section id="estimation-de-la-fonction-de-survie-lapproche-non-paramétrique" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="estimation-de-la-fonction-de-survie-lapproche-non-paramétrique"><span class="header-section-number">1.1</span> Estimation de la fonction de survie: l’approche non paramétrique</h3>
<p>L’estimation de la fonction de survie est très utile pour:</p>
<ul>
<li><p>Effectuer une analyse descriptive préliminaire pour comprendre le comportement du temps de survie.</p></li>
<li><p>Évaluer l’adéquation de certains modèles de régression.</p></li>
<li><p>Comparer différents groupes de l’échantillon.</p></li>
<li><p>Estimer certains indicateurs d’intérêts comme la médiane ou la moyenne</p></li>
</ul>
</section>
<section id="approche-i-les-tables-de-survie-méthode-actuarielle" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="approche-i-les-tables-de-survie-méthode-actuarielle"><span class="header-section-number">1.2</span> Approche I: Les tables de survie (méthode actuarielle)</h3>
<p>La méthode actuarielle est une méthode descriptive. Les tables de survie regroupent les observations de l’échantillon par intervalle de valeurs (<strong>le choix des intervalles est arbitraire</strong>).</p>
<ul>
<li><p>Cette méthode est utilisée lorsque <strong>la taille de l’échantillon est grande</strong> et l<strong>a mesure du temps de survie est rudimentaire (pas précise).</strong></p></li>
<li><p>Cette méthode est utile pour <strong>comprendre les concepts</strong> de fonction de survie et de risque.</p></li>
<li><p>Cette méthode permet également de comparer les indicateurs de survie de plusieurs groupes.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: le package 'survival' a été compilé avec la version R 4.4.3</code></pre>
</div>
</div></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un objet de survie </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>objet_survie1 <span class="ot">&lt;-</span> <span class="fu">Surv</span>(<span class="at">time =</span> netflix<span class="sc">$</span>Temps, <span class="at">event =</span> <span class="dv">1</span><span class="sc">-</span>netflix<span class="sc">$</span>censure)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle de survie sur aucune variable </span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>fit_km1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie1 <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Regrouper le temps en 20 unités</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>intervalle <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fu">max</span>(netflix<span class="sc">$</span>Temps, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">by =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exemple-dimplications-managériales" class="level4" data-number="1.2.1">
<h4 data-number="1.2.1" class="anchored" data-anchor-id="exemple-dimplications-managériales"><span class="header-section-number">1.2.1</span> Exemple d’implications managériales</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Résume du modèle de survie </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summary</span>(fit_km1, <span class="at">times =</span> intervalle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie1 ~ 1)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    0    500       0    1.000 0.00000        1.000        1.000
   20    496       4    0.992 0.00398        0.984        1.000
   40    482      16    0.960 0.00876        0.943        0.977
   60    443      27    0.905 0.01313        0.880        0.932
   80    372      58    0.785 0.01866        0.749        0.822
  100    284      74    0.623 0.02234        0.581        0.669
  120    187      83    0.430 0.02344        0.387        0.479
  140    111      53    0.295 0.02229        0.254        0.342
  160     53       9    0.262 0.02244        0.222        0.310
  180     23       6    0.221 0.02470        0.177        0.275
  200      8       1    0.204 0.02803        0.156        0.267</code></pre>
</div>
</div>
<p>La plus importante perte de clients survient approximativement durant la deuxième année du contrat (60 et 120 semaines). Une attention particulière doit être accordée aux abonnés à ce moment là. Des actions de rétention peuvent être mises en place durant la deuxième année d’bonnement (promotion, fidélisation, évaluation du niveau de la satisfaction…</p>
</section>
<section id="comprendre-loutput-de-la-table-de-survie-indicateurs" class="level4" data-number="1.2.2">
<h4 data-number="1.2.2" class="anchored" data-anchor-id="comprendre-loutput-de-la-table-de-survie-indicateurs"><span class="header-section-number">1.2.2</span> Comprendre l’output de la table de survie: indicateurs</h4>
<ul>
<li><p><strong>Time</strong> : les points temporels sur la courbe.</p></li>
<li><p><strong>N.risk</strong> : le nombre de sujets à risque au temps t-0</p></li>
<li><p><strong>N.events</strong> : le nombre cumulé d’événements survenus depuis le dernier temps répertorié jusqu’au temps t+0.</p></li>
<li><p><strong>Survival</strong> : la probabilité de survie estimée à chaque instant.</p></li>
<li><p><strong>Standard error</strong> : l’erreur standard de la valeur de survie.</p></li>
<li><p><strong>Lower 95% CI</strong> : la borne inférieure de l’intervalle de confiance à 95 % pour la courbe.</p></li>
<li><p><strong>Upper 95% CI</strong> : la borne supérieure de l’intervalle de confiance à 95 % pour la courbe.</p></li>
</ul>
</section>
<section id="output-courbe-de-survie" class="level4" data-number="1.2.3">
<h4 data-number="1.2.3" class="anchored" data-anchor-id="output-courbe-de-survie"><span class="header-section-number">1.2.3</span> Output: Courbe de survie</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie Kaplan-Meier</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ce graphique suggère quelques faits intéressants à propos de la variable aléatoire Temps:</p>
<ol type="1">
<li><p>Une proportion négligeable de clients mettent fin à leur contrat durant la première année de l’abonnement.</p></li>
<li><p>Le churn (le fait de rompre le contrat) est plus important durant la deuxième année.</p></li>
<li><p>Cependant, les clients qui ne quittent pas durant les 120-150 semaines semblent être très fidèles par la suite.</p></li>
</ol>
</section>
<section id="comparaison-de-deux-courbes-de-survie-hommefemme" class="level4" data-number="1.2.4">
<h4 data-number="1.2.4" class="anchored" data-anchor-id="comparaison-de-deux-courbes-de-survie-hommefemme"><span class="header-section-number">1.2.4</span> Comparaison de deux courbes de survie (Homme/Femme)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle en fonction du sexe</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fit_km_sexe <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie1 <span class="sc">~</span> netflix<span class="sc">$</span>sexe)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumer le modèle de survie</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km_sexe, <span class="at">times =</span> intervalle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie1 ~ netflix$sexe)

                netflix$sexe=0 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    0    309       0    1.000 0.00000       1.0000        1.000
   20    307       2    0.994 0.00456       0.9846        1.000
   40    294      15    0.945 0.01297       0.9199        0.971
   60    262      22    0.873 0.01904       0.8362        0.911
   80    210      41    0.733 0.02564       0.6842        0.785
  100    157      47    0.564 0.02926       0.5097        0.625
  120    101      46    0.385 0.02963       0.3311        0.448
  140     50      36    0.230 0.02675       0.1833        0.289
  160     20       5    0.195 0.02727       0.1482        0.256
  180      8       1    0.181 0.02866       0.1327        0.247
  200      3       1    0.151 0.03645       0.0939        0.242

                netflix$sexe=1 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    0    191       0    1.000 0.00000        1.000        1.000
   20    189       2    0.990 0.00737        0.975        1.000
   40    188       1    0.984 0.00900        0.967        1.000
   60    181       5    0.958 0.01453        0.930        0.987
   80    162      17    0.867 0.02481        0.820        0.917
  100    127      27    0.717 0.03334        0.654        0.785
  120     86      37    0.501 0.03776        0.432        0.581
  140     61      17    0.393 0.03769        0.325        0.474
  160     33       4    0.359 0.03804        0.292        0.442
  180     15       5    0.285 0.04273        0.212        0.382
  200      5       0    0.285 0.04273        0.212        0.382</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie Kaplan-Meier</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km_sexe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>La courbe de survie des femmes (sexe=1) est en tout point supérieure à celle des hommes (sexe=0).</p></li>
<li><p>La probabilité qu’une femme reste abonnée à plus de 140 semaines est plus grande que celle des hommes.</p>
<h4 id="test-de-comparaison-de-deux-courbes-de-survie" data-number="1.2.5" class="anchored"><span class="header-section-number">1.2.5</span> Test de comparaison de deux courbes de survie</h4></li>
</ol>
<p>Le test d’égalité des fonctions de survie se base sur les hypothèses suivantes:</p>
<p>H₀ : S fₑₘₘₑ(t)= S hₒₘₘₑ(t)<br>
H₁ : S fₑₘₘₑ(t) ≠ S hₒₘₘₑ(t)</p>
<ul>
<li><p>R retourne le résultat du test de Log-Rank</p></li>
<li><p>Dans ce contexte, on rejette H₀ et on conclut que la fonction de survie des femmes est significativement différente de celle des hommes.</p></li>
<li><p>Ce test peut servir à tester simultanément plus de deux fonctions de survie</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparer les courbes de survie selon le sexe avec le test de Wilcoxon</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(objet_survie1 <span class="sc">~</span> netflix<span class="sc">$</span>sexe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = objet_survie1 ~ netflix$sexe)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
netflix$sexe=0 309      217      181      7.33      16.4
netflix$sexe=1 191      117      153      8.63      16.4

 Chisq= 16.4  on 1 degrees of freedom, p= 5e-05 </code></pre>
</div>
</div>
</section>
<section id="exercice" class="level4" data-number="1.2.6">
<h4 data-number="1.2.6" class="anchored" data-anchor-id="exercice"><span class="header-section-number">1.2.6</span> Exercice</h4>
<ol type="1">
<li><p>Retrouver les courbes de survie des différentes régions.</p></li>
<li><p>Tester l’égalité des fonctions de survie entre les régions (test simultané et tests deux par deux).</p></li>
<li><p>Commenter les résultats.</p></li>
</ol>
</section>
</section>
<section id="approche-ii-lestimateur-de-kaplan-meier-km" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="approche-ii-lestimateur-de-kaplan-meier-km"><span class="header-section-number">1.3</span> Approche II: L’estimateur de Kaplan-Meier (KM)</h3>
<ul>
<li><p>L’estimateur de Kaplan-Meier est la méthode d’estimation d’une fonction de survie la plus utilisée.</p></li>
<li><p>Cette méthode permet d’estimer la fonction de survie sans devoir regrouper les observations par intervalles.</p></li>
<li><p>KM est la méthode à privilégier si le temps de survie est mesuré avec précision et/ou le nombre d’observations est faible.</p></li>
<li><p>C’est une méthodes d’estimation non paramétrique, dans le sens où on ne suppose pas que le temps de survie suit une loi en particulier.</p></li>
<li><p>Si l’échantillon ne contient aucune censure( uniquement les temps exact sont observés), l’estimateur KM donne la proportion des observations qui possède un temps de survie supérieur à un t (temps) donné.</p></li>
<li><p>s’il y a une censure l’estimateur de KM va ajuster les outputs en tenant compte de la censure.</p></li>
</ul>
<section id="lestimateur-de-kaplan-meier-km" class="level4" data-number="1.3.1">
<h4 data-number="1.3.1" class="anchored" data-anchor-id="lestimateur-de-kaplan-meier-km"><span class="header-section-number">1.3.1</span> L’estimateur de Kaplan-Meier (KM)</h4>
<p>L’estimateur KM est donné par :</p>
<p><span class="math display">\[
\hat{S}(T) = \prod_{i: t_i &lt; t} \left( 1 - \frac{d_i}{n_i} \right) = \left( 1 - \frac{d_1}{n_1} \right) \times \left( 1 - \frac{d_2}{n_2} \right) \times \dots
\]</span></p>
<ul>
<li><p><strong><em>dᵢ</em></strong>: le nombre d’individus qui quittent l’état (résilient le contrat ) au temps tᵢ .</p></li>
<li><p><em><strong>nᵢ</strong>:</em> le nombre d’individus à risque au temps tᵢ (l’idée est semblable aux tables de survie).</p></li>
<li><p>(1-<strong><em>dᵢ</em></strong> /<strong><em>nᵢ</em></strong>): la probabilité conditionnelle de rester dans l’état un temps supérieur à tᵢ, étant donné qu’on s’est rendu jusque là.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un objet de survie</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>objet_survie2 <span class="ot">&lt;-</span> <span class="fu">Surv</span>(<span class="at">time =</span> netflix<span class="sc">$</span>Temps, <span class="at">event =</span> <span class="dv">1</span> <span class="sc">-</span> netflix<span class="sc">$</span>censure)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle de survie sans variable explicative</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>fit_km2 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie2 <span class="sc">~</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="output-r-km" class="level4" data-number="1.3.2">
<h4 data-number="1.3.2" class="anchored" data-anchor-id="output-r-km"><span class="header-section-number">1.3.2</span> Output R (KM)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumer le modèle de survie</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ 1)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    2    500       1    0.998 0.00200        0.994        1.000
   11    499       1    0.996 0.00282        0.990        1.000
   14    498       1    0.994 0.00345        0.987        1.000
   18    497       1    0.992 0.00398        0.984        1.000
   27    496       1    0.990 0.00445        0.981        0.999
   29    495       1    0.988 0.00487        0.979        0.998
   30    494       1    0.986 0.00525        0.976        0.996
   34    493       4    0.978 0.00656        0.965        0.991
   36    489       1    0.976 0.00684        0.963        0.990
   37    488       2    0.972 0.00738        0.958        0.987
   38    486       2    0.968 0.00787        0.953        0.984
   39    484       2    0.964 0.00833        0.948        0.980
   40    482       2    0.960 0.00876        0.943        0.977
   42    480       3    0.954 0.00937        0.936        0.973
   43    477       1    0.952 0.00956        0.933        0.971
   44    474       1    0.950 0.00975        0.931        0.969
   45    473       2    0.946 0.01011        0.926        0.966
   46    471       1    0.944 0.01029        0.924        0.964
   48    468       2    0.940 0.01063        0.919        0.961
   49    466       1    0.938 0.01080        0.917        0.959
   50    465       2    0.934 0.01112        0.912        0.956
   51    463       1    0.932 0.01128        0.910        0.954
   52    461       3    0.926 0.01174        0.903        0.949
   54    456       2    0.922 0.01203        0.898        0.946
   55    454       2    0.918 0.01232        0.894        0.942
   56    452       1    0.916 0.01246        0.892        0.940
   57    450       2    0.912 0.01273        0.887        0.937
   58    446       1    0.910 0.01286        0.885        0.935
   59    444       1    0.907 0.01300        0.882        0.933
   60    443       1    0.905 0.01313        0.880        0.932
   61    441       2    0.901 0.01339        0.875        0.928
   63    439       4    0.893 0.01388        0.866        0.921
   64    435       2    0.889 0.01412        0.862        0.917
   65    433       6    0.877 0.01479        0.848        0.906
   67    424       5    0.866 0.01532        0.837        0.897
   68    417       4    0.858 0.01573        0.828        0.889
   69    413       2    0.854 0.01592        0.823        0.886
   70    411       4    0.846 0.01630        0.814        0.878
   71    406       5    0.835 0.01675        0.803        0.869
   73    401       4    0.827 0.01710        0.794        0.861
   75    394       1    0.825 0.01718        0.792        0.859
   76    391       2    0.821 0.01735        0.787        0.855
   77    389       5    0.810 0.01776        0.776        0.846
   78    383       7    0.795 0.01829        0.760        0.832
   79    375       1    0.793 0.01837        0.758        0.830
   80    372       4    0.785 0.01866        0.749        0.822
   81    367       5    0.774 0.01900        0.737        0.812
   82    362       3    0.767 0.01920        0.731        0.806
   83    358       3    0.761 0.01940        0.724        0.800
   84    355       6    0.748 0.01977        0.710        0.788
   85    349       3    0.742 0.01994        0.704        0.782
   86    345       7    0.727 0.02033        0.688        0.768
   87    337       3    0.720 0.02049        0.681        0.761
   88    331       1    0.718 0.02055        0.679        0.759
   89    329       3    0.711 0.02070        0.672        0.753
   90    326       2    0.707 0.02081        0.667        0.749
   91    324       3    0.701 0.02095        0.661        0.743
   92    321       4    0.692 0.02114        0.652        0.735
   93    317       4    0.683 0.02132        0.643        0.726
   94    313       2    0.679 0.02141        0.638        0.722
   95    311       2    0.674 0.02149        0.634        0.718
   96    308       4    0.666 0.02165        0.624        0.709
   97    303       6    0.652 0.02188        0.611        0.697
   98    296       3    0.646 0.02199        0.604        0.690
   99    290       5    0.635 0.02217        0.593        0.680
  100    284       5    0.623 0.02234        0.581        0.669
  101    277       4    0.614 0.02246        0.572        0.660
  102    272       2    0.610 0.02252        0.567        0.656
  103    270       4    0.601 0.02264        0.558        0.647
  104    266       4    0.592 0.02274        0.549        0.638
  105    262       3    0.585 0.02282        0.542        0.632
  106    257       4    0.576 0.02291        0.533        0.623
  107    253       1    0.574 0.02293        0.531        0.620
  108    249       3    0.567 0.02300        0.523        0.614
  109    244       3    0.560 0.02307        0.516        0.607
  110    241       9    0.539 0.02324        0.495        0.586
  111    231       6    0.525 0.02333        0.481        0.573
  112    225       6    0.511 0.02339        0.467        0.559
  113    218       4    0.502 0.02343        0.458        0.550
  114    214       3    0.495 0.02345        0.451        0.543
  115    211       3    0.488 0.02346        0.444        0.536
  116    208       4    0.478 0.02348        0.434        0.526
  117    201       3    0.471 0.02349        0.427        0.519
  118    197       4    0.461 0.02349        0.418        0.510
  119    193       5    0.449 0.02348        0.406        0.498
  120    187       8    0.430 0.02344        0.387        0.479
  121    179       1    0.428 0.02343        0.384        0.476
  122    176       4    0.418 0.02340        0.375        0.467
  123    171       4    0.408 0.02336        0.365        0.457
  124    165       2    0.403 0.02334        0.360        0.452
  125    162       5    0.391 0.02327        0.348        0.439
  126    156       3    0.383 0.02322        0.341        0.432
  127    153       3    0.376 0.02317        0.333        0.424
  128    150       4    0.366 0.02309        0.323        0.414
  129    145       1    0.363 0.02307        0.321        0.412
  130    143       2    0.358 0.02302        0.316        0.406
  131    140       2    0.353 0.02298        0.311        0.401
  132    136       4    0.343 0.02288        0.301        0.391
  133    132       2    0.338 0.02283        0.296        0.385
  134    130       3    0.330 0.02274        0.288        0.378
  135    125       6    0.314 0.02255        0.273        0.361
  136    118       2    0.309 0.02248        0.268        0.356
  139    114       3    0.301 0.02237        0.260        0.348
  140    111       2    0.295 0.02229        0.254        0.342
  141    107       1    0.292 0.02225        0.252        0.339
  143     97       1    0.289 0.02223        0.249        0.336
  146     89       1    0.286 0.02221        0.246        0.333
  148     84       2    0.279 0.02220        0.239        0.326
  150     80       1    0.276 0.02219        0.236        0.323
  156     62       2    0.267 0.02235        0.226        0.314
  159     58       1    0.262 0.02244        0.222        0.310
  165     46       1    0.257 0.02266        0.216        0.305
  167     44       1    0.251 0.02288        0.210        0.300
  171     37       1    0.244 0.02325        0.202        0.294
  175     35       1    0.237 0.02361        0.195        0.288
  177     33       1    0.230 0.02396        0.187        0.282
  179     25       1    0.221 0.02470        0.177        0.275
  189     13       1    0.204 0.02803        0.156        0.267
  202      6       1    0.170 0.03880        0.108        0.266
  216      2       2    0.000     NaN           NA           NA</code></pre>
</div>
</div>
<p><strong>Exercice</strong></p>
<p>Calculer la probabilité de survivre plus de 30 semaines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la probabilité de survie au-delà de 30 semaines</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km2, <span class="at">times =</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ 1)

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   30    494       7    0.986 0.00525        0.976        0.996</code></pre>
</div>
</div>
<p><strong>Réponse</strong></p>
<ol type="1">
<li><p>Les individus à risque de quitter à ce moment = 493 = 500-n.event=500-7 (ils n’ont pas quitté ni n’ont été censurés).</p></li>
<li><p>7 individus ont quitté à moins de 30 semaines d’abonnement.</p></li>
<li><p>S(30)= (1-1/499)<em>(1-1/498)</em>(1-1/497)<em>(1-1/496)</em>(1-1/495)<em>(1-1/494)</em>(1-1/493)=1-7/493= 0.98597</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie de Kaplan-Meier</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
</section>
<section id="quelques-stats-avec-km" class="level4" data-number="1.3.3">
<h4 data-number="1.3.3" class="anchored" data-anchor-id="quelques-stats-avec-km"><span class="header-section-number">1.3.3</span> Quelques stats avec KM</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renvoie les temps où la survie atteint 75%, 50% et 25% (Q1, médiane, Q3)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(fit_km2, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$quantile
 25  50  75 
 84 114 171 

$lower
 25  50  75 
 80 110 143 

$upper
 25  50  75 
 90 119  NA </code></pre>
</div>
</div>
<p>Pour mesurer la tendance centrale de la variable d’intérêt, il est préférable d’utiliser la médiane ou les quartiles. S(171)= 25% S(114)=50% (médiane) S(84)=75%</p>
<p>Exemple: la probabilité de survivre plus de 171 semaines est de 25%.</p>
</section>
<section id="courbes-de-survie-hommefemme" class="level4" data-number="1.3.4">
<h4 data-number="1.3.4" class="anchored" data-anchor-id="courbes-de-survie-hommefemme"><span class="header-section-number">1.3.4</span> Courbes de survie Homme/Femme</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On ajuste le modèle de survie sur la variable sexe</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fit_km_sexe2 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_km_sexe2 )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = objet_survie2 ~ netflix$sexe)

                netflix$sexe=0 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    2    309       1   0.9968 0.00323       0.9905        1.000
   11    308       1   0.9935 0.00456       0.9846        1.000
   27    307       1   0.9903 0.00558       0.9794        1.000
   29    306       1   0.9871 0.00643       0.9745        1.000
   34    305       4   0.9741 0.00903       0.9566        0.992
   36    301       1   0.9709 0.00957       0.9523        0.990
   37    300       2   0.9644 0.01054       0.9440        0.985
   38    298       2   0.9579 0.01142       0.9358        0.981
   39    296       2   0.9515 0.01223       0.9278        0.976
   40    294       2   0.9450 0.01297       0.9199        0.971
   42    292       1   0.9417 0.01332       0.9160        0.968
   43    291       1   0.9385 0.01367       0.9121        0.966
   44    288       1   0.9353 0.01400       0.9082        0.963
   45    287       2   0.9287 0.01464       0.9005        0.958
   48    284       2   0.9222 0.01525       0.8928        0.953
   49    282       1   0.9189 0.01555       0.8890        0.950
   50    281       2   0.9124 0.01611       0.8814        0.945
   51    279       1   0.9091 0.01638       0.8776        0.942
   52    277       3   0.8993 0.01716       0.8663        0.934
   54    273       2   0.8927 0.01765       0.8587        0.928
   55    271       1   0.8894 0.01789       0.8550        0.925
   56    270       1   0.8861 0.01813       0.8513        0.922
   57    268       1   0.8828 0.01836       0.8475        0.920
   58    265       1   0.8795 0.01859       0.8438        0.917
   59    263       1   0.8761 0.01882       0.8400        0.914
   60    262       1   0.8728 0.01904       0.8362        0.911
   61    260       2   0.8661 0.01948       0.8287        0.905
   63    258       2   0.8593 0.01990       0.8212        0.899
   64    256       2   0.8526 0.02030       0.8138        0.893
   65    254       5   0.8358 0.02124       0.7952        0.879
   67    246       4   0.8223 0.02196       0.7803        0.866
   68    241       3   0.8120 0.02246       0.7692        0.857
   69    238       1   0.8086 0.02263       0.7654        0.854
   70    237       4   0.7950 0.02325       0.7507        0.842
   71    233       4   0.7813 0.02383       0.7360        0.829
   73    229       1   0.7779 0.02397       0.7323        0.826
   76    225       2   0.7710 0.02425       0.7249        0.820
   77    223       5   0.7537 0.02491       0.7064        0.804
   78    217       4   0.7398 0.02540       0.6917        0.791
   80    210       2   0.7328 0.02564       0.6842        0.785
   81    207       3   0.7221 0.02599       0.6729        0.775
   82    204       2   0.7151 0.02622       0.6655        0.768
   83    202       3   0.7044 0.02654       0.6543        0.758
   84    199       5   0.6867 0.02702       0.6358        0.742
   85    194       3   0.6761 0.02729       0.6247        0.732
   86    191       3   0.6655 0.02754       0.6136        0.722
   87    187       1   0.6619 0.02763       0.6100        0.718
   88    184       1   0.6583 0.02771       0.6062        0.715
   89    183       3   0.6476 0.02795       0.5950        0.705
   90    180       1   0.6440 0.02802       0.5913        0.701
   91    179       1   0.6404 0.02809       0.5876        0.698
   92    178       3   0.6296 0.02830       0.5765        0.688
   93    175       1   0.6260 0.02837       0.5728        0.684
   95    174       2   0.6188 0.02850       0.5654        0.677
   96    171       3   0.6079 0.02868       0.5542        0.667
   97    168       5   0.5898 0.02894       0.5357        0.649
   98    163       2   0.5826 0.02904       0.5284        0.642
   99    159       2   0.5753 0.02913       0.5209        0.635
  100    157       3   0.5643 0.02926       0.5097        0.625
  101    152       2   0.5568 0.02934       0.5022        0.617
  102    149       1   0.5531 0.02938       0.4984        0.614
  103    148       2   0.5456 0.02945       0.4908        0.607
  104    146       3   0.5344 0.02955       0.4795        0.596
  105    143       1   0.5307 0.02958       0.4758        0.592
  106    140       1   0.5269 0.02961       0.4719        0.588
  107    139       1   0.5231 0.02964       0.4681        0.585
  108    135       2   0.5153 0.02970       0.4603        0.577
  109    132       2   0.5075 0.02976       0.4524        0.569
  110    130       6   0.4841 0.02988       0.4289        0.546
  111    124       2   0.4763 0.02991       0.4212        0.539
  112    122       4   0.4607 0.02993       0.4056        0.523
  113    117       2   0.4528 0.02993       0.3978        0.515
  114    115       1   0.4489 0.02993       0.3939        0.512
  115    114       3   0.4371 0.02991       0.3822        0.500
  116    111       3   0.4253 0.02987       0.3706        0.488
  117    107       2   0.4173 0.02983       0.3627        0.480
  118    104       1   0.4133 0.02981       0.3588        0.476
  119    103       1   0.4093 0.02979       0.3549        0.472
  120    101       6   0.3850 0.02963       0.3311        0.448
  121     95       1   0.3809 0.02960       0.3271        0.444
  122     92       4   0.3644 0.02944       0.3110        0.427
  123     87       3   0.3518 0.02931       0.2988        0.414
  124     84       1   0.3476 0.02926       0.2947        0.410
  125     82       4   0.3306 0.02903       0.2784        0.393
  126     77       2   0.3221 0.02891       0.2701        0.384
  127     75       3   0.3092 0.02869       0.2578        0.371
  128     72       3   0.2963 0.02844       0.2455        0.358
  130     69       2   0.2877 0.02826       0.2373        0.349
  131     67       1   0.2834 0.02816       0.2333        0.344
  132     65       4   0.2660 0.02775       0.2168        0.326
  134     61       2   0.2572 0.02751       0.2086        0.317
  135     58       3   0.2439 0.02714       0.1961        0.303
  136     54       1   0.2394 0.02701       0.1919        0.299
  139     52       2   0.2302 0.02675       0.1833        0.289
  143     44       1   0.2250 0.02665       0.1784        0.284
  146     41       1   0.2195 0.02656       0.1732        0.278
  148     37       1   0.2136 0.02649       0.1675        0.272
  156     24       1   0.2047 0.02684       0.1583        0.265
  159     21       1   0.1949 0.02727       0.1482        0.256
  177     14       1   0.1810 0.02866       0.1327        0.247
  189      6       1   0.1508 0.03645       0.0939        0.242
  202      2       1   0.0754 0.05636       0.0174        0.326

                netflix$sexe=1 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   14    191       1    0.995 0.00522        0.985        1.000
   18    190       1    0.990 0.00737        0.975        1.000
   30    189       1    0.984 0.00900        0.967        1.000
   42    188       2    0.974 0.01155        0.951        0.997
   46    186       1    0.969 0.01262        0.944        0.994
   55    183       1    0.963 0.01362        0.937        0.990
   57    182       1    0.958 0.01453        0.930        0.987
   63    181       2    0.947 0.01619        0.916        0.980
   65    179       1    0.942 0.01694        0.909        0.976
   67    178       1    0.937 0.01765        0.903        0.972
   68    176       1    0.932 0.01834        0.896        0.968
   69    175       1    0.926 0.01899        0.890        0.964
   71    173       1    0.921 0.01962        0.883        0.960
   73    172       3    0.905 0.02136        0.864        0.948
   75    167       1    0.899 0.02190        0.857        0.943
   78    166       3    0.883 0.02343        0.838        0.930
   79    163       1    0.878 0.02391        0.832        0.926
   80    162       2    0.867 0.02481        0.820        0.917
   81    160       2    0.856 0.02566        0.807        0.908
   82    158       1    0.851 0.02606        0.801        0.903
   84    156       1    0.845 0.02646        0.795        0.899
   86    154       4    0.823 0.02795        0.770        0.880
   87    150       2    0.812 0.02864        0.758        0.870
   90    146       1    0.807 0.02898        0.752        0.865
   91    145       2    0.796 0.02963        0.740        0.856
   92    143       1    0.790 0.02994        0.733        0.851
   93    142       3    0.773 0.03082        0.715        0.836
   94    139       2    0.762 0.03136        0.703        0.826
   96    137       1    0.757 0.03162        0.697        0.821
   97    135       1    0.751 0.03188        0.691        0.816
   98    133       1    0.745 0.03214        0.685        0.811
   99    131       3    0.728 0.03288        0.667        0.796
  100    127       2    0.717 0.03334        0.654        0.785
  101    125       2    0.705 0.03378        0.642        0.775
  102    123       1    0.700 0.03399        0.636        0.769
  103    122       2    0.688 0.03439        0.624        0.759
  104    120       1    0.682 0.03458        0.618        0.754
  105    119       2    0.671 0.03493        0.606        0.743
  106    117       3    0.654 0.03542        0.588        0.727
  108    114       1    0.648 0.03557        0.582        0.722
  109    112       1    0.642 0.03572        0.576        0.716
  110    111       3    0.625 0.03613        0.558        0.700
  111    107       4    0.601 0.03662        0.534        0.678
  112    103       2    0.590 0.03683        0.522        0.667
  113    101       2    0.578 0.03702        0.510        0.655
  114     99       2    0.566 0.03718        0.498        0.644
  116     97       1    0.561 0.03725        0.492        0.639
  117     94       1    0.555 0.03733        0.486        0.633
  118     93       3    0.537 0.03753        0.468        0.616
  119     90       4    0.513 0.03771        0.444        0.592
  120     86       2    0.501 0.03776        0.432        0.581
  123     84       1    0.495 0.03778        0.426        0.575
  124     81       1    0.489 0.03780        0.420        0.569
  125     80       1    0.483 0.03782        0.414        0.563
  126     79       1    0.477 0.03783        0.408        0.557
  128     78       1    0.471 0.03784        0.402        0.551
  129     76       1    0.464 0.03784        0.396        0.545
  131     73       1    0.458 0.03786        0.390        0.539
  133     71       2    0.445 0.03787        0.377        0.526
  134     69       1    0.439 0.03787        0.370        0.520
  135     67       3    0.419 0.03783        0.351        0.500
  136     64       1    0.412 0.03781        0.345        0.494
  139     62       1    0.406 0.03778        0.338        0.487
  140     61       2    0.393 0.03769        0.325        0.474
  141     58       1    0.386 0.03764        0.319        0.467
  148     47       1    0.378 0.03773        0.310        0.459
  150     45       1    0.369 0.03781        0.302        0.451
  156     38       1    0.359 0.03804        0.292        0.442
  165     28       1    0.347 0.03879        0.278        0.432
  167     27       1    0.334 0.03942        0.265        0.421
  171     23       1    0.319 0.04029        0.249        0.409
  175     21       1    0.304 0.04114        0.233        0.396
  179     16       1    0.285 0.04273        0.212        0.382
  216      2       2    0.000     NaN           NA           NA</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie de Kaplan-Meier</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit_km_sexe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(fit_km_sexe2, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$quantile
               25  50  75
netflix$sexe=0 78 110 135
netflix$sexe=1 98 123 216

$lower
               25  50  75
netflix$sexe=0 71 102 128
netflix$sexe=1 91 114 171

$upper
                25  50  75
netflix$sexe=0  84 115 177
netflix$sexe=1 105 136  NA</code></pre>
</div>
</div>
<p><strong>Exercice:</strong></p>
<p>Commentez les résultats.</p>
</section>
<section id="comparaison-de-deux-groupes" class="level4" data-number="1.3.5">
<h4 data-number="1.3.5" class="anchored" data-anchor-id="comparaison-de-deux-groupes"><span class="header-section-number">1.3.5</span> Comparaison de deux groupes</h4>
<p>Les hypothèses du test sont identiques à celle énoncées dans le cas des tables de survie.</p>
<p>H₀ : S fₑₘₘₑ(t)= S hₒₘₘₑ(t)<br>
H₁ : S fₑₘₘₑ(t) ≠ S hₒₘₘₑ(t) pour au moins une valeur de t</p>
<p><strong>Log-rank</strong> : suppose que le ratio des fonctions de risques des 2 groupes est constant pour toute la période d’intérêt.</p>
<p><strong>Breslow (Wilcoxon)</strong>: accorde plus de poids aux différences observées dés le début qu’aux différences observées plus loin dans le temps. Il est donc le plus puissant dans un contexte où les différences sont plus prononcées au tout début.</p>
<p><strong>Terone-Ware:</strong> plus de poids au début.</p>
<p>On a effectué le test du Log-Rank plus haut. Ici, on s’intéresse au test test de Breslow et celui de Tarone-Ware.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Breslow</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe, <span class="at">rho =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = objet_survie2 ~ netflix$sexe, rho = 1)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
netflix$sexe=0 309    145.9    120.2      5.48      17.6
netflix$sexe=1 191     69.4     95.1      6.93      17.6

 Chisq= 17.6  on 1 degrees of freedom, p= 3e-05 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Tarone-Ware </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(objet_survie2 <span class="sc">~</span> netflix<span class="sc">$</span>sexe, <span class="at">rho =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = objet_survie2 ~ netflix$sexe, rho = 0.5)

                 N Observed Expected (O-E)^2/E (O-E)^2/V
netflix$sexe=0 309    175.3      145      6.21      17.3
netflix$sexe=1 191     88.6      119      7.61      17.3

 Chisq= 17.3  on 1 degrees of freedom, p= 3e-05 </code></pre>
</div>
</div>
<p><strong>Exercice</strong></p>
<p>Comparer les fonctions de survies des différentes régions. Commentez les résultats.</p>
</section>
</section>
</section>
<section id="méthode-destimation-semi-paramétrique-modèle-de-cox" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="méthode-destimation-semi-paramétrique-modèle-de-cox"><span class="header-section-number">2</span> Méthode d’estimation semi-paramétrique: Modèle de Cox</h2>
<section id="introduction-au-modèle-de-cox" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="introduction-au-modèle-de-cox"><span class="header-section-number">2.1</span> Introduction au modèle de COX</h3>
<ul>
<li><p>Le modèle de Cox est un modèle de régression semi-paramétrique, appelé aussi, modèle à risques proportionnels (<strong>proportional Hazard model</strong>).</p></li>
<li><p>Le modèle de Cox permet d’estimer l’effet des variables explicatives sur la variable aléatoire T sans postulat de distribution particulière (sans spécifier une loi de distribution) pour celle celle-ci.</p></li>
<li><p>C’est un modèle semi-paramétrique car <strong>seulement une partie</strong> du modèle doit être <strong>spécifiée</strong>.</p></li>
<li><p>Le modèle de Cox est similaire au modèle de régression logistique mais évalue la relation entre le temps de survie et les variables explicatives.</p></li>
<li><p>C’est le modèle le plus utilisé pour analyser les données de survie.</p></li>
</ul>
<section id="description-du-modèle" class="level4" data-number="2.1.1">
<h4 data-number="2.1.1" class="anchored" data-anchor-id="description-du-modèle"><span class="header-section-number">2.1.1</span> Description du modèle</h4>
<p>𝒉(𝒕|𝒙₁, 𝒙₂, … , 𝒙ₖ) est la fonction de risque pour les individus ayant les caractéristiques spécifiques (𝒙₁, 𝒙₂, … , 𝒙ₖ).</p>
<p>Le modèle de Cox s’écrit: <span class="math display">\[
h(t | x_1, x_2, \dots, x_k) = h_0(t) \times \exp(\beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k)
\]</span> est une fonction de risque de base qui n’ a pas besoin d’être spécifié.</p>
<p>La fonction de risque est donc le produit de deux parties distinctes:</p>
<ol type="1">
<li><p>une partie sans paramètres, <strong>qui dépend uniquement du temps</strong></p></li>
<li><p>et une partie avec paramètres qui <strong>dépend uniquement des variables explicatives.</strong></p></li>
</ol>
<p>Remarques:</p>
<ul>
<li><p>Lorsque toutes les variables explicatives prennent la valeur 0, on retrouve 𝒉₀ 𝒕 (cette valeur est équivalente à « l’ordonnée à l’origine en régression linéaire »).</p></li>
<li><p>ex p(β₁x₁ + β₂x₂ + … + βₖxₖ modélise l’effet d’un changement des valeurs des variables explicatives sur la fonction de risque de base”)</p></li>
</ul>
</section>
<section id="interprétation-des-paramètres-r-modèle-de-cox-avec-toutes-les-variables-explicatives" class="level4" data-number="2.1.2">
<h4 data-number="2.1.2" class="anchored" data-anchor-id="interprétation-des-paramètres-r-modèle-de-cox-avec-toutes-les-variables-explicatives"><span class="header-section-number">2.1.2</span> Interprétation des paramètres R: Modèle de Cox avec toutes les variables explicatives</h4>
<p>Si on compare le ratio des risques de deux individus ayant les mêmes valeurs pour les variables explicatives, à l’exception de la variable x1, qui diffère d’une unité, on obtient ce qui suit:</p>
<p><span class="math display">\[
\frac{h(t | x_1 + 1, x_2, \dots, x_k)}{h(t | x_1, x_2, \dots, x_k)}
= \frac{h_0(t) \exp\left(\beta_1 (x_1 + 1) + \beta_2 x_2 + \dots + \beta_k x_k \right)}{h_0(t) \exp\left(\beta_1 x_1 + \beta_2 x_2 + \dots + \beta_k x_k \right)}
= e^{\beta_1}
\]</span></p>
<p><strong>Interprétation de β₁ :</strong></p>
<p>lorsque x1 augmente d’une unité, le risque est multiplié par 𝒆ᵝ¹ (ratio de risque).</p>
<p><strong>Résultats:</strong></p>
<ul>
<li><p>Le ratio de risque ne dépend pas du temps.</p></li>
<li><p>Le ratio de risque est constant par rapport au temps. (l’effet de la variable explicative est stable dans le temps).</p></li>
</ul>
</section>
<section id="r-modèle-de-cox-avec-toutes-les-variables-explicatives" class="level4" data-number="2.1.3">
<h4 data-number="2.1.3" class="anchored" data-anchor-id="r-modèle-de-cox-avec-toutes-les-variables-explicatives"><span class="header-section-number">2.1.3</span> R: Modèle de Cox avec toutes les variables explicatives</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuster le modèle de Cox avec les variables âge, sexe et région</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(Temps, censure) <span class="sc">~</span> age <span class="sc">+</span> sexe <span class="sc">+</span> region, <span class="at">data =</span> netflix, <span class="at">ties =</span> <span class="st">"exact"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumer le modèle de Cox</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(Temps, censure) ~ age + sexe + region, data = netflix, 
    ties = "exact")

  n= 500, number of events= 166 

            coef exp(coef) se(coef)      z Pr(&gt;|z|)    
age     -0.04314   0.95778  0.00947 -4.555 5.23e-06 ***
sexe1   -0.48278   0.61706  0.17045 -2.832  0.00462 ** 
region2 -0.40384   0.66775  0.27041 -1.493  0.13532    
region3 -0.04773   0.95339  0.25291 -0.189  0.85031    
region4 -0.41091   0.66304  0.25774 -1.594  0.11087    
region5 -0.16652   0.84661  0.25633 -0.650  0.51594    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

        exp(coef) exp(-coef) lower .95 upper .95
age        0.9578      1.044    0.9402    0.9757
sexe1      0.6171      1.621    0.4418    0.8618
region2    0.6677      1.498    0.3930    1.1345
region3    0.9534      1.049    0.5808    1.5651
region4    0.6630      1.508    0.4001    1.0988
region5    0.8466      1.181    0.5123    1.3992

Concordance= 0.637  (se = 0.026 )
Likelihood ratio test= 29.62  on 6 df,   p=5e-05
Wald test            = 27.97  on 6 df,   p=1e-04
Score (logrank) test = 28.22  on 6 df,   p=9e-05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la courbe de survie estimée à partir du modèle de Cox</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(cox))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la fonction de risque cumulée (cumulative hazard)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">survfit</span>(cox), <span class="at">fun =</span> <span class="st">"cumhaz"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T7_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interprétation" class="level4" data-number="2.1.4">
<h4 data-number="2.1.4" class="anchored" data-anchor-id="interprétation"><span class="header-section-number">2.1.4</span> Interprétation</h4>
<p>On estime, toutes choses étant égale par ailleurs (si tout demeure constant):</p>
<ul>
<li><p><strong>À tout moment dans le temps</strong>, le risque qu’une femme (sexe=1) mette fin à son contrat est exp(-0.519)=0.595 fois le risque d’un homme (le risque est 40.5% inférieur (1-0.595=0.405)).</p></li>
<li><p>Pour chaque augmentation d’une année de l’âge lors de l’abonnement, le risque de quitter diminue de 4.3% (exp(-0,043)=0.957) <strong>à tout moment dans le temps</strong>.</p></li>
<li><p><strong>À tout moment dans le temps</strong>, le risque qu’un client de la région 2 résilie son contrat est exp(-0.329)=0.729 fois celui de la région 1 (référence).</p></li>
</ul>
<p><strong>Exercice</strong></p>
<p>Testez les significativité des paramètres dans le modèle au niveau 5% et interprétez le reste des coefficients estimés.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>