<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thème 2:Comparaison des moyennes deux groupes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/clipboard/clipboard.min.js"></script>
<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/quarto.js"></script>
<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/popper.min.js"></script>
<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/anchor.min.js"></script>
<link href="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LIVRABLE_T2-DESKTOP-OQF5J47_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="LIVRABLE_T2-DESKTOP-OQF5J47_files/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#comparaison-des-moyennes-de-deux-échantillons-indépendants" id="toc-comparaison-des-moyennes-de-deux-échantillons-indépendants" class="nav-link active" data-scroll-target="#comparaison-des-moyennes-de-deux-échantillons-indépendants">Comparaison des moyennes de deux échantillons indépendants</a>
  <ul class="collapse">
  <li><a href="#comparaison-de-2-moyennes-échantillons-indépendants" id="toc-comparaison-de-2-moyennes-échantillons-indépendants" class="nav-link" data-scroll-target="#comparaison-de-2-moyennes-échantillons-indépendants">Comparaison de 2 moyennes (échantillons indépendants)</a></li>
  <li><a href="#cadre-théorique-comparaison-de-2-moyennes-échantillons-indépendants" id="toc-cadre-théorique-comparaison-de-2-moyennes-échantillons-indépendants" class="nav-link" data-scroll-target="#cadre-théorique-comparaison-de-2-moyennes-échantillons-indépendants">Cadre théorique: Comparaison de 2 moyennes (échantillons indépendants)</a></li>
  <li><a href="#test-t-student-et-intervalle-de-confiance" id="toc-test-t-student-et-intervalle-de-confiance" class="nav-link" data-scroll-target="#test-t-student-et-intervalle-de-confiance">Test-T (Student) et intervalle de confiance</a></li>
  <li><a href="#remarques-sur-le-test-t-et-ic" id="toc-remarques-sur-le-test-t-et-ic" class="nav-link" data-scroll-target="#remarques-sur-le-test-t-et-ic">Remarques sur le test-T et IC</a></li>
  <li><a href="#alternative-au-test-t" id="toc-alternative-au-test-t" class="nav-link" data-scroll-target="#alternative-au-test-t">Alternative au Test-T</a></li>
  <li><a href="#test-t-versus-mww" id="toc-test-t-versus-mww" class="nav-link" data-scroll-target="#test-t-versus-mww">Test-T versus MWW</a></li>
  <li><a href="#comparaison-de-2-proportions-échantillons-indépendants" id="toc-comparaison-de-2-proportions-échantillons-indépendants" class="nav-link" data-scroll-target="#comparaison-de-2-proportions-échantillons-indépendants">Comparaison de 2 proportions (échantillons indépendants)</a></li>
  <li><a href="#comparaison-de-2-proportions-échantillons-indépendants-1" id="toc-comparaison-de-2-proportions-échantillons-indépendants-1" class="nav-link" data-scroll-target="#comparaison-de-2-proportions-échantillons-indépendants-1">Comparaison de 2 proportions (échantillons indépendants)</a></li>
  <li><a href="#test-z-et-intervalle-de-confiance" id="toc-test-z-et-intervalle-de-confiance" class="nav-link" data-scroll-target="#test-z-et-intervalle-de-confiance">Test Z et intervalle de confiance</a></li>
  <li><a href="#conditions-dutilisation-du-test-z-ou-pearson-chi-square-et-de-lic" id="toc-conditions-dutilisation-du-test-z-ou-pearson-chi-square-et-de-lic" class="nav-link" data-scroll-target="#conditions-dutilisation-du-test-z-ou-pearson-chi-square-et-de-lic">Conditions d’utilisation du test Z ou Pearson Chi-Square et de l’IC</a></li>
  </ul></li>
  <li><a href="#comparaison-de-deux-échantillons-dépendants" id="toc-comparaison-de-deux-échantillons-dépendants" class="nav-link" data-scroll-target="#comparaison-de-deux-échantillons-dépendants">Comparaison de deux échantillons dépendants</a>
  <ul class="collapse">
  <li><a href="#comparaison-de-deux-moyennes-échantillons-dépendants" id="toc-comparaison-de-deux-moyennes-échantillons-dépendants" class="nav-link" data-scroll-target="#comparaison-de-deux-moyennes-échantillons-dépendants">Comparaison de deux moyennes: Échantillons dépendants</a></li>
  <li><a href="#test-t-pour-échantillon-dépendants" id="toc-test-t-pour-échantillon-dépendants" class="nav-link" data-scroll-target="#test-t-pour-échantillon-dépendants">Test-T pour échantillon dépendants</a></li>
  <li><a href="#conditions-dutilisation-du-test-t-pour-données-appariées-et-de-lintervalle-de-confiance" id="toc-conditions-dutilisation-du-test-t-pour-données-appariées-et-de-lintervalle-de-confiance" class="nav-link" data-scroll-target="#conditions-dutilisation-du-test-t-pour-données-appariées-et-de-lintervalle-de-confiance">Conditions d’utilisation du Test-T pour données appariées et de l’intervalle de confiance</a></li>
  <li><a href="#test-non-paramétriques-pour-les-données-appariées" id="toc-test-non-paramétriques-pour-les-données-appariées" class="nav-link" data-scroll-target="#test-non-paramétriques-pour-les-données-appariées">Test non-paramétriques pour les données appariées</a></li>
  <li><a href="#comparaison-entre-test-t-pour-données-appariées-test-du-signe-et-test-wrs" id="toc-comparaison-entre-test-t-pour-données-appariées-test-du-signe-et-test-wrs" class="nav-link" data-scroll-target="#comparaison-entre-test-t-pour-données-appariées-test-du-signe-et-test-wrs">Comparaison entre Test-T pour données appariées, test du signe et test WRS</a></li>
  <li><a href="#comparaison-de-2-proportions-échantillons-dépendants" id="toc-comparaison-de-2-proportions-échantillons-dépendants" class="nav-link" data-scroll-target="#comparaison-de-2-proportions-échantillons-dépendants">Comparaison de 2 proportions (échantillons dépendants)</a></li>
  <li><a href="#test-du-mcnemar" id="toc-test-du-mcnemar" class="nav-link" data-scroll-target="#test-du-mcnemar">Test du McNemar</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thème 2:Comparaison des moyennes deux groupes</h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="comparaison-des-moyennes-de-deux-échantillons-indépendants" class="level2">
<h2 class="anchored" data-anchor-id="comparaison-des-moyennes-de-deux-échantillons-indépendants">Comparaison des moyennes de deux échantillons indépendants</h2>
<section id="comparaison-de-2-moyennes-échantillons-indépendants" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-de-2-moyennes-échantillons-indépendants">Comparaison de 2 moyennes (échantillons indépendants)</h3>
<p><strong>Mise en situation 1</strong></p>
<p>La chaîne de supermarchés «&nbsp;Finebouche&nbsp;», chef de file de l’alimentation au détail, s’engage à offrir à ses clients une expérience unique de magasinage. Les hauts dirigeants de la chaîne ne s’entendent pas sur la politique de gestion des plaintes des clients. Certains prétendent qu’une compensation monétaire sous forme d’un coupon de 20&nbsp;$ devrait être envoyée par la poste aux clients non satisfaits et d’autres pensent qu’un message de courtoisie personnalisé serait suffisant pour rétablir la confiance des clients insatisfaits.</p>
<p>Les analystes de la chaîne ont décidé d’analyser l’effet de ces deux politiques afin de parvenir à une recommandation. Deux échantillons aléatoires simples de 500 clients chacun ont été tirés. Une compensation monétaire a été accordée au premier échantillon et une lettre de courtoisie a été envoyée au deuxième échantillon.</p>
<p><strong>Données</strong></p>
<p>Le fichier de données «&nbsp;offre_finebouche.csv&nbsp;» contient des données propres à cette mise en situation. Il contient 1000 observations et deux variables:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Offre</td>
<td style="text-align: left;">montant des dépenses par visite un mois après la mise en œuvre des deux politiques.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Groupe</td>
<td style="text-align: left;">1 - clients ayant reçu le coupon de 20$; 2 - clients ayant reçu la lettre de courtoisie.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail  </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données depuis un fichier CSV  </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>offre <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Offre_Finebouche.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)  </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la variable "Groupe" en facteur (variable catégorielle)  </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>offre<span class="sc">$</span>Groupe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(offre<span class="sc">$</span>Groupe)  </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Remplacer les virgules par des points dans la colonne "Offre" </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>offre<span class="sc">$</span>Offre <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, offre<span class="sc">$</span>Offre)  </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la colonne Offre en numérique  </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>offre<span class="sc">$</span>Offre <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(offre<span class="sc">$</span>Offre)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Exercice 1:</strong></p>
<p>1-Représentez la distribution du montant des dépenses par visite pour chaque groupe.</p>
<p>2-Commentez le résultat dans le contexte du problème.</p>
<p>3-Existe-t-il une différence significative entre les dépenses moyennes par visite chez les deux groupes?</p>
<p>4-Quantifiez la grandeur de la différence entre les deux moyennes.</p>
<p>5-Quelle politique vous semble la plus appropriée dans ce contexte?</p>
<p><strong>Résultats</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package ggplot2 pour la visualisation  </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un boxplot de la variable Offre en fonction des Groupes  </span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(offre, <span class="fu">aes</span>(<span class="at">x =</span> Groupe, <span class="at">y =</span> Offre, <span class="at">fill =</span> Groupe)) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Offre"</span>, <span class="at">x =</span> <span class="st">"Groupe"</span>, <span class="at">title =</span> <span class="st">"Distribution de l'Offre par Groupe"</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"lightblue"</span>)) <span class="sc">+</span>  </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title=</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>)  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T2-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package dplyr</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des statistiques descriptives de la variable Offre pour chaque groupe </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>Stat_desc<span class="ot">&lt;-</span> offre <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Groupe) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Effectif =</span> <span class="fu">n</span>(),                             </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    Médiane<span class="ot">=</span> <span class="fu">median</span>(Offre,<span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum=</span> <span class="fu">min</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum=</span> <span class="fu">max</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">sd</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),       </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Afficher le résultat</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Stat_desc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  Groupe Effectif Moyenne Médiane Minimum Maximum Ecart_Type
  &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
1 1           500    120.    120.    62.1    181.       20.7
2 2           500    200.    200.    57.8    340.       49.5</code></pre>
</div>
</div>
</section>
<section id="cadre-théorique-comparaison-de-2-moyennes-échantillons-indépendants" class="level3">
<h3 class="anchored" data-anchor-id="cadre-théorique-comparaison-de-2-moyennes-échantillons-indépendants">Cadre théorique: Comparaison de 2 moyennes (échantillons indépendants)</h3>
<p><img src="images/clipboard-3641564561.png" class="img-fluid"></p>
<pre><code></code></pre>
</section>
<section id="test-t-student-et-intervalle-de-confiance" class="level3">
<h3 class="anchored" data-anchor-id="test-t-student-et-intervalle-de-confiance">Test-T (Student) et intervalle de confiance</h3>
<p>Pour comparer deux moyennes de deux échantillons indépendants, on utilise habituellement le Test-T.</p>
<p><strong>Mais il existe deux versions du T-Test:</strong></p>
<p><strong>Version 1</strong>: les variances des populations sont supposées égales.</p>
<p><strong>Version 2</strong>: les variances des populations sont quelconques.</p>
<p><strong>Conditions d’utilisation :</strong></p>
<ul>
<li><p>Test-T est conçu initialement pour des variables <strong>quantitatives</strong>.</p></li>
<li><p>Les 2 échantillons doivent être prélevés de manière <strong>indépendante</strong>.</p></li>
<li><p>Si les échantillons sont « petits », les distributions des variables Y<sub>1</sub> et Y<sub>2</sub> dans les populations de référence doivent s’approcher d’une loi normale.</p></li>
<li><p>Si les échantillons sont assez grands, le test demeure valide même si les variables ne sont pas normalement distribuées dans les populations de référence. Dans la plupart des cas, des échantillons de 30 observations et plus sont suffisants. En fait, plus les distributions initiales sont asymétriques, plus les tailles des échantillons devront être grandes.</p></li>
</ul>
<section id="text-version1-variances-des-populations-quadsigma_12-text-et-sigma_22-text-supposées-égales" class="level4">
<h4 class="anchored" data-anchor-id="text-version1-variances-des-populations-quadsigma_12-text-et-sigma_22-text-supposées-égales"><span class="math display">\[
\text{ Version1: Variances des populations  }\quad\sigma_1^2 \text{ et } \sigma_2^2 \text{ supposées égales}
\]</span></h4>
<p><strong>Statistique du test :</strong></p>
<p><span class="math display">\[
T = \frac{\overline{Y}_1 - \overline{Y}_2}
{\sqrt{\frac{(n_1 - 1) S_1^2 + (n_2 - 1) S_2^2}{n_1 + n_2 - 2}
\times \left( \frac{1}{n_1} + \frac{1}{n_2} \right) }}
\]</span></p>
<p><strong>Intervalle de confiance pour estimer (</strong> <strong>μ₁ et μ₂)</strong></p>
<p><span class="math display">\[
\overline{Y}_1 - \overline{Y}_2 \pm t_{\alpha/2}
\sqrt{\frac{(n_1 - 1) S_1^2 + (n_2 - 1) S_2^2}{n_1 + n_2 - 2}
\times \left( \frac{1}{n_1} + \frac{1}{n_2} \right)}
\]</span></p>
<p><strong>Nombre de degrés de liberté :</strong></p>
<p><span class="math display">\[
n_1 + n_2 - 2
\]</span></p>
<ul>
<li><p>Cette version du test est <strong>« puissante » en autant que les variances des 2 populations sont égales</strong>.</p></li>
<li><p>Il faut donc effectuer <em>un test préalable sur les variances des populations</em> (<strong>Test de Levene</strong>) <strong>pour voir si on peut se permettre de supposer leur égalité avant de tester les moyennes</strong>. En cas de doute, la version 2 (variances quelconques) du test est préférable.</p></li>
</ul>
</section>
<section id="text-version2-variances-des-populations-quadsigma_12-text-et-sigma_22-text-quelconques" class="level4">
<h4 class="anchored" data-anchor-id="text-version2-variances-des-populations-quadsigma_12-text-et-sigma_22-text-quelconques"><span class="math display">\[
\text{ Version2: Variances des populations  }\quad\sigma_1^2 \text{ et } \sigma_2^2 \text{ quelconques}
\]</span></h4>
<p><strong>Statistique du test:</strong></p>
<p><span class="math display">\[
T = \frac{\overline{Y}_1 - \overline{Y}_2}
{\sqrt{\frac{S_1^2}{n_1} + \frac{S_2^2}{n_2}}} \text{(Si H₀ est vraie, distribution T=student)}
\]</span></p>
<p><strong>Intervalle de confiance pour estimer μ₁ - μ₂:</strong></p>
<p><span class="math display">\[
\overline{Y}_1 - \overline{Y}_2 \pm t_{\alpha/2}
\sqrt{\frac{S_1^2}{n_1} + \frac{S_2^2}{n_2}}
\]</span></p>
<p>Pour cette version du test et de l’intervalle, le nombre de degrés de liberté associés à la Student est approximativement égal à :</p>
<p><span class="math display">\[
\frac{(w_1 + w_2)^2}{\frac{w_1^2}{(n_1 - 1)} + \frac{w_2^2}{(n_2 - 1)}}\text {  avec  } \ w_i = \frac{S_i^2}{n_i}\text{ approximation de Satterthwaite}
\]</span></p>
<p><strong>Démarche</strong></p>
<p>A fin de comparer les dépenses moyennes des deux groupes, on commence par tester l’égalité des variances dans les populations considérées pour ensuite choisir le Test-T approprié.:</p>
<p><strong><em>Étape 1: tester l’égalité des variances (Test de Levene):</em></strong></p>
<p><span class="math display">\[
H₀: \sigma_1^2 = \sigma_2^2 \quad \text{vs} \quad H₁: \sigma_1^2 \neq \sigma_2^2
\]</span></p>
<p><strong><em>Étape 2: tester l’égalité des moyennes:</em></strong></p>
<p><span class="math display">\[
H₀: \mu_1 = \mu_2 \quad \text{vs} \quad H₁: \mu_1 \neq \mu_2
\]</span></p>
</section>
<section id="réponses-34-et-5-interprétez-les-résultats-suivants" class="level4">
<h4 class="anchored" data-anchor-id="réponses-34-et-5-interprétez-les-résultats-suivants">Réponses 3,4 et 5: Interprétez les résultats suivants</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger le package car pour effectuer le test de Levene  </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Levene pour vérifier l'égalité des variances entre les groupes  </span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre,<span class="at">center=</span>mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
       Df F value    Pr(&gt;F)    
group   1  257.97 &lt; 2.2e-16 ***
      998                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t de Student pour comparer les moyennes lorsque les variances ne sont pas égales  </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Offre by Groupe
t = -33.39, df = 668.1, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -84.86323 -75.43678
sample estimates:
mean in group 1 mean in group 2 
       120.1528        200.3028 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des statistiques descriptives de la variable Offre pour chaque groupe  </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Stat_desc_groupe <span class="ot">&lt;-</span> offre <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Groupe) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Effectif =</span> <span class="fu">n</span>(),                             </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),        </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">sd</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),       </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Erreur_Standard =</span> Ecart_Type <span class="sc">/</span> <span class="fu">sqrt</span>(Effectif)  <span class="co"># Erreur standard de la moyenne</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résultat</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Stat_desc_groupe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  Groupe Effectif Moyenne Ecart_Type Erreur_Standard
  &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;
1 1           500    120.       20.7           0.925
2 2           500    200.       49.5           2.21 </code></pre>
</div>
</div>
</section>
</section>
<section id="remarques-sur-le-test-t-et-ic" class="level3">
<h3 class="anchored" data-anchor-id="remarques-sur-le-test-t-et-ic">Remarques sur le test-T et IC</h3>
<ul>
<li><p>R fournit la valeur-p du test bidirectionnels et unidirectionnels, selon l’argument alternative dans la commande t.test(). two.sided pour un test bidirectionnel et one.sided pour un test unidirectionnel.</p></li>
<li><p>Lien entre intervalle de confiance et <em>test bidirectionnel (valeur-p)</em>:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Test unidirectionnel</strong></p>
<p>Dans R, on peut effectuer un test unilatéral en précisant l’argument <code>alternative</code> dans <code>t.test()</code> :</p>
<ul>
<li><code>t.test(x, y, alternative = "greater")</code> pour tester l’hypothèse H₁ : μ₁ &gt; μ₂<br>
</li>
<li><code>t.test(x, y, alternative = "less")</code>&nbsp;&nbsp;&nbsp;pour tester l’hypothèse H₁ : μ₁ &lt; μ₂</li>
</ul>
</div>
</div></li>
<li><p><strong>Faiblesse du test-T</strong>: sensible aux valeurs très extrêmes.</p></li>
</ul>
<p><strong>Exercice</strong>:</p>
<p>Changez la valeur de la première ligne du fichier à 20000$ et interprétez le résultat trouvé.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer une copie du dataframe offre et l'appeler offre2  </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>offre2 <span class="ot">&lt;-</span> offre</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modifier la valeur de la première ligne de la colonne Offre à 20000 dans offre2  </span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>offre2[<span class="dv">1</span>, <span class="st">"Offre"</span>] <span class="ot">&lt;-</span> <span class="dv">20000</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Vérifier la modification dans offre2  </span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(offre2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Offre Groupe
1 20000.00000      1
2   109.76692      1
3    89.26780      1
4    93.55777      1
5   112.09800      1
6   126.47238      1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des statistiques descriptives de la variable Offre pour chaque groupe dans offre2  </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Stat_desc_groupe2 <span class="ot">&lt;-</span> offre2 <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Groupe) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Effectif =</span> <span class="fu">n</span>(),                             </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">mean</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),        </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">sd</span>(Offre, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),       </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Erreur_Standard =</span> Ecart_Type <span class="sc">/</span> <span class="fu">sqrt</span>(Effectif)  </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le résultat</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Stat_desc_groupe2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  Groupe Effectif Moyenne Ecart_Type Erreur_Standard
  &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;
1 1           500    160.      889.            39.8 
2 2           500    200.       49.5            2.21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Levene pour vérifier l'égalité des variances entre les groupes dans offre2  </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre2,<span class="at">center=</span>mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
       Df F value Pr(&gt;F)
group   1  1.0211 0.3125
      998               </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t de Student pour comparer les moyennes entre les groupes dans offre2 (en supposant l'égalité des variances)  </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre2, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Offre by Groupe
t = -1.0127, df = 998, p-value = 0.3114
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -118.50214   37.82582
sample estimates:
mean in group 1 mean in group 2 
       159.9647        200.3028 </code></pre>
</div>
</div>
</section>
<section id="alternative-au-test-t" class="level3">
<h3 class="anchored" data-anchor-id="alternative-au-test-t">Alternative au Test-T</h3>
<p><strong>Test Mann-Whitney-Wilcoxon (MWW)</strong></p>
<p>Test « <strong>non-paramétrique</strong> » : Pas de condition relative à la distribution dans les populations de référence. Les variables doivent être <strong>au moins ordinales</strong>.</p>
<p><strong>Hypothèses réelles testées <em>(légèrement différentes du test-T)</em></strong></p>
<p><span class="math display">\[
H₀ : P(Y_1 \leq Y_2) = P(Y_1 &gt; Y_2) = \frac{1}{2}
\]</span><br>
<em>(il y a autant de chance que la variable prenne une valeur plus grande ou plus petite dans une population que dans l’autre)</em></p>
<p><span class="math display">\[
H₁ : P(Y_1 &lt; Y_2) \neq P(Y_1 &gt; Y_2)
\]</span><br>
<em>(la variable a tendance à prendre des valeurs plus élevées dans une population que dans l’autre)</em></p>
<p><em>La statistique du test MWW est basée sur le rang des observations.</em></p>
<p><strong>Éch 1 :</strong></p>
<p><span class="math display">\[
n_1\text{ (taille échantillon) }
\]</span> <span class="math display">\[
Y_{11}, Y_{12}, \dots, Y_{1n1}\text{ (observations)}
\]</span></p>
<p><strong>Éch 2 :</strong></p>
<p><span class="math display">\[
n_2 \text{ (taille échantillon)}
\]</span> <span class="math display">\[
Y_{21}, Y_{22}, \dots, Y_{2n2}\text{ (observations)}
\]</span></p>
<p><strong>La statistique du test MWW</strong> est basée sur le <strong>rang</strong> des observations.</p>
<p><code>Exemples:</code></p>
<p><br>
<span class="math display">\[ \text{ Observations: } 1.2 \quad ; \quad -2.5 \quad ; \quad 0.8 \quad ; \quad 5 \quad ; \quad 3.4 \]</span><br>
<br>
<span class="math display">\[ \text{ Rangs:  }3 \quad ; \quad 1 \quad ; \quad 2 \quad ; \quad 5 \quad ; \quad 4 \]</span></p>
<p><br>
<span class="math display">\[ \text{ Rangs: } 3 \quad ; \quad 1 \quad ; \quad 3 \quad ; \quad 2 \quad ; \quad 6 \quad ; \quad 5 \]</span></p>
<p><span class="math display">\[
\text{Soit } R_{11}, R_{12}, \dots, R_{1n1} \text{ les rangs respectifs des observations }
Y_{11}, Y_{12}, \dots, Y_{1n1} \text{ du premier échantillon par rapport aux deux échantillons combinés.}
\]</span></p>
<p><code>Exemples:</code><br>
<span class="math display">\[  \text{éch1:   } 1.2 \quad ; \quad -2.5 \quad ; \quad 0.8 \quad ; \quad 5 \quad ; \quad 3.4 \]</span></p>
<p><br>
<br>
<span class="math display">\[ \text{éch2:  }-1 \quad ; \quad 1.5 \quad ; \quad 2.5 \quad ; \quad 4.3 \quad ; \quad 6 \quad ; \quad 6.5 \]</span></p>
<p><strong>Échantillons combinés</strong> :</p>
<p><span class="math display">\[ 1.2 \quad ; \quad -2.5 \quad ; \quad 0.8 \quad ; \quad 5 \quad ; \quad 3.4 \quad ; \quad -1 \quad ; \quad 1.5 \quad ; \quad 2.5 \quad ; \quad 4.3 \quad ; \quad 6 \quad ; \quad 6.5 \]</span></p>
<p><strong>Rangs</strong> :</p>
<p><span class="math display">\[ 4 \quad ; \quad 1 \quad ; \quad 3 \quad ; \quad 9 \quad ; \quad 7 \quad ; \quad 2 \quad ; \quad 5 \quad ; \quad 6 \quad ; \quad 8 \quad ; \quad 10 \quad ; \quad 11 \]</span></p>
<p>La somme des rangs du premier échantillon = 4+1+3+9+7=24<br>
</p>
<p><strong>Statistique du test MWW :</strong></p>
<p><span class="math display">\[
W = \sum_{i=1}^{n_1} R_i\text{ (somme des rangs du 1er échantillon)}
\]</span></p>
<p><span class="math display">\[
\text{ Si H₀ est vraie, alors: }\ Z = \frac{W - E(W)}{\sqrt{\text{Var}(W)}}\text{ approximativement de la loi N(0,1)}
\]</span></p>
<p>Mann-Whitney Test</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Mann-Whitney-Wilcoxon pour comparer les distributions de Offre entre les groupes  </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  Offre by Groupe
W = 16955, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Mann-Whitney Test: Ajout d’une valeur extrême</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Mann-Whitney-Wilcoxon pour comparer les distributions de Offre entre les groupes dans offre2  </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Offre <span class="sc">~</span> Groupe, <span class="at">data =</span> offre2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  Offre by Groupe
W = 17447, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>La valeur-p est inchangée malgré l’ajout d’une valeur extrême. On obtient la même conclusion!</p>
</section>
<section id="test-t-versus-mww" class="level3">
<h3 class="anchored" data-anchor-id="test-t-versus-mww">Test-T versus MWW</h3>
<ul>
<li><p>Le test MWW s’utilise peu importe la distribution des variables dans les populations d’origine. <strong>Il peut même être appliqué avec des données ordinales</strong> (seul le rang des observations est important).</p></li>
<li><p>Le test MWW est beaucoup <strong>moins sensible à la présence de valeurs extrêmes</strong>.</p></li>
<li><p>Le test-T est <strong>plus puissant</strong> que le test MWW lorsque les variables sont normalement distribuées dans les populations de référence. Plus on s’écarte de la loi normale, plus la puissance du test-T s’amenuise. Dans certaines situations (non normalité et échantillons trop petits, présence de valeurs très extrêmes, etc…), le test MWW pourrait devenir plus puissant que le test-T.</p></li>
<li><p>Lorsqu’on a des doutes sur les conditions d’utilisation du test-T, on peut essayer de confirmer (ou infirmer) les résultats avec un test non-paramétrique.</p></li>
</ul>
<p><img src="images/clipboard-549594982.png" class="img-fluid" width="800"></p>
<pre><code></code></pre>
</section>
<section id="comparaison-de-2-proportions-échantillons-indépendants" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-de-2-proportions-échantillons-indépendants">Comparaison de 2 proportions (échantillons indépendants)</h3>
<p><strong>Mise en situation 2</strong></p>
<p><strong>But de l’étude</strong></p>
<p>Vérifier si l’intérêt envers une application d’achat de vêtements en ligne diffère selon le sexe.</p>
<p><strong>Méthodologie</strong></p>
<p>Les sujets devaient simplement indiquer s’ils étaient intéressés ou non à utiliser le service.</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sexe</td>
<td style="text-align: left;">Sexe du client (Homme = 0, Femme = 1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interet</td>
<td style="text-align: left;">Interet du client (Oui = 1, Non = 0)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail  </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)  </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Importer le jeu de données service_en_ligne </span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>service <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"service_en_ligne.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir les variables interet et sexe en facteurs</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>service<span class="sc">$</span>interet <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(service<span class="sc">$</span>interet)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>service<span class="sc">$</span>sexe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(service<span class="sc">$</span>sexe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="données-des-deux-échantillons" class="level4">
<h4 class="anchored" data-anchor-id="données-des-deux-échantillons">Données des deux échantillons</h4>
<p>Tableau croisé intérêt × sexe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un tableau croisé des variables interet et sexe </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>sexe_interet <span class="ot">&lt;-</span> <span class="fu">table</span>(service<span class="sc">$</span>interet, service<span class="sc">$</span>sexe)  </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajouter les totaux au tableau des effectifs  </span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>sexe_interet_totaux <span class="ot">&lt;-</span> <span class="fu">addmargins</span>(sexe_interet)  </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les pourcentages par sexe (colonnes)  </span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>pourcentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(service<span class="sc">$</span>interet, service<span class="sc">$</span>sexe), <span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span>  </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajouter les totaux aux pourcentages  </span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>pourcentages_avec_totaux <span class="ot">&lt;-</span> <span class="fu">addmargins</span>(pourcentages)  </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Combiner les effectifs et les pourcentages arrondis  </span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>sexe_interet_tableau <span class="ot">&lt;-</span> <span class="fu">cbind</span>(sexe_interet_totaux, <span class="fu">round</span>(pourcentages_avec_totaux, <span class="dv">1</span>))  </span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Renommer les colonnes du tableau  </span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sexe_interet_tableau) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Hommes"</span>, <span class="st">"Femmes"</span>, <span class="st">"Total"</span>, <span class="st">"Hommes %"</span>, <span class="st">"Femmes %"</span>, <span class="st">"Total %"</span>)  </span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le tableau final  </span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sexe_interet_tableau)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Hommes Femmes Total Hommes % Femmes % Total %
0       46     25    71     79.3     59.5   138.8
1       12     17    29     20.7     40.5    61.2
Sum     58     42   100    100.0    100.0   200.0</code></pre>
</div>
</div>
</section>
</section>
<section id="comparaison-de-2-proportions-échantillons-indépendants-1" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-de-2-proportions-échantillons-indépendants-1">Comparaison de 2 proportions (échantillons indépendants)</h3>
<p><img src="images/clipboard-833120389.png" class="img-fluid"></p>
<pre><code></code></pre>
</section>
<section id="test-z-et-intervalle-de-confiance" class="level3">
<h3 class="anchored" data-anchor-id="test-z-et-intervalle-de-confiance">Test Z et intervalle de confiance</h3>
<p><strong>Statistique du test :</strong></p>
<p><span class="math display">\[
Z = \frac{\hat{p}_1 - \hat{p}_2}
{\sqrt{\hat{p} (1 - \hat{p}) \left(\frac{1}{n_1} + \frac{1}{n_2} \right)}} \text{ où }\ \hat{p} = \frac{n_1 \hat{p}_1 + n_2 \hat{p}_2}{n_1 + n_2}
\]</span></p>
<p>Si (H₀) est vraie, ( Z ) est approximativement de loi N(0,1)</p>
<p><strong>Intervalle de confiance pour estimer</strong> π1 - π2:</p>
<p><span class="math display">\[
(\hat{\pi}_1 - \hat{\pi}_2) \pm Z_{\alpha / 2} \sqrt{\frac{\hat{\pi}_1 (1 - \hat{\pi}_1)}{n_1} + \frac{\hat{\pi}_2 (1 - \hat{\pi}_2)}{n_2}}
\]</span></p>
<p>(remarque : au niveau de confiance 95%, Zₐ⁄₂ = 1.96 )</p>
<p>Le test Z pour 2 proportions n’est pas directement programmé dans R mais on peut quand même obtenir l’équivalent de son résultat à l’aide du test du Khi-deux de Pearson (Chi-square). Ces deux tests sont équivalents et produisent la même valeur-p.&nbsp;L’intervalle de confiance doit être calculé séparément</p>
<p>Test du <strong>Chi-deux</strong> de Pearson : la statistique correspond à χ².</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Appliquer le test du Khi-deux de Pearson</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">chisq.test</span>(sexe_interet,<span class="at">correct =</span><span class="cn">FALSE</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  sexe_interet
X-squared = 4.6319, df = 1, p-value = 0.03138</code></pre>
</div>
</div>
</section>
<section id="conditions-dutilisation-du-test-z-ou-pearson-chi-square-et-de-lic" class="level3">
<h3 class="anchored" data-anchor-id="conditions-dutilisation-du-test-z-ou-pearson-chi-square-et-de-lic">Conditions d’utilisation du test Z ou Pearson Chi-Square et de l’IC</h3>
<ul>
<li><p>Les 2 échantillons doivent être prélevés de manière <strong>indépendante</strong> dans les populations de référence.</p></li>
<li><p>Les échantillons doivent être suffisamment grands.</p></li>
<li><p>Pour le test « Pearson Chi-Square », on doit avoir un <strong>effectif espéré</strong> d’au moins 5 dans chaque cellule du tableau.</p></li>
<li><p>Si les échantillons sont petits (effectifs espérés de moins de 5 dans certaines cellules), il est préférable d’utiliser <strong>le test exact de Fisher</strong>.</p></li>
</ul>
</section>
</section>
<section id="comparaison-de-deux-échantillons-dépendants" class="level2">
<h2 class="anchored" data-anchor-id="comparaison-de-deux-échantillons-dépendants">Comparaison de deux échantillons dépendants</h2>
<section id="comparaison-de-deux-moyennes-échantillons-dépendants" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-de-deux-moyennes-échantillons-dépendants">Comparaison de deux moyennes: Échantillons dépendants</h3>
<p><strong>Mise en situation 3</strong></p>
<p>Un responsable du service des ressources humaines d’une grande organisation s’inquiète du fort taux de roulement chez les femmes âgés de 30 à 40 ans. Le gestionnaire soupçonne le changement de l’étatmatrimonial des femmes dans leurs décisions de quitter la compagnie.</p>
<p><strong>Méthodologie</strong></p>
<p>Le gestionnaire dispose d’un historique des scores de satisfaction (échelle de 1 à 7) au travail mesurés à l’aide de différents items du même questionnaire distribué au personnel à chaque année. Une valeur élevée du score de mobilisation indique une satisfaction plus grande.</p>
<p><strong>Échantillon</strong></p>
<p>43 femmes ayant eu un enfant au cours des 5 dernières années et ayant travaillé au même endroit avant et après leur congé de maternité.</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les variables et descriptions</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nom_Variable =</span> <span class="fu">c</span>(<span class="st">"Sujet"</span>,<span class="st">"Avant"</span>,<span class="st">"Après"</span>,<span class="st">"Pendant"</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">"ID du sujet"</span>, <span class="st">"score de satisfaction avant la grossesse"</span>,<span class="st">"score de satisfaction après le congé de maternité"</span>,<span class="st">"score de satisfaction pendant la grossesse"</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le tableau</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(variables, <span class="at">format =</span> <span class="st">"pipe"</span>, <span class="at">align =</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sujet</td>
<td style="text-align: left;">ID du sujet</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avant</td>
<td style="text-align: left;">score de satisfaction avant la grossesse</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Après</td>
<td style="text-align: left;">score de satisfaction après le congé de maternité</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pendant</td>
<td style="text-align: left;">score de satisfaction pendant la grossesse</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail  </span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)  </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données depuis un fichier csv</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>mobilisation <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"mobilisation_femmes.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Remplacement des virgules par des points dans les variables avant pendant et apres</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>avant <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, mobilisation<span class="sc">$</span>avant)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>pendant <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, mobilisation<span class="sc">$</span>pendant)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>apres <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, mobilisation<span class="sc">$</span>apres)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Conversion des variables en format numérique</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>avant <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(mobilisation<span class="sc">$</span>avant)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>pendant <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(mobilisation<span class="sc">$</span>pendant)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>mobilisation<span class="sc">$</span>apres <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(mobilisation<span class="sc">$</span>apres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Résultats observés:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un boxplot pour comparer les scores de satisfaction Avant et Après </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(mobilisation<span class="sc">$</span>avant, mobilisation<span class="sc">$</span>apres,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Avant"</span>, <span class="st">"Après"</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot des scores de satisfaction"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Valeurs"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"lightblue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="LIVRABLE_T2-DESKTOP-OQF5J47_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives pour les périodes Avant et Après</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>Stat_desc_avant_apres <span class="ot">&lt;-</span> mobilisation <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">c</span>(<span class="fu">length</span>(avant), <span class="fu">length</span>(apres)),                   </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Moyenne =</span> <span class="fu">c</span>(<span class="fu">mean</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">mean</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),  </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    Médiane <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">median</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min =</span> <span class="fu">c</span>(<span class="fu">min</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">min</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),  </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max =</span> <span class="fu">c</span>(<span class="fu">max</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),  </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Ecart_Type =</span> <span class="fu">c</span>(<span class="fu">sd</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">sd</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Erreur_Standard =</span> <span class="fu">c</span>(<span class="fu">sd</span>(avant, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(avant)), </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">sd</span>(apres, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(apres)))  </span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Période <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Avant"</span>, <span class="st">"Après"</span>)) <span class="sc">%&gt;%</span>  </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Période, <span class="fu">everything</span>()) </span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Stat_desc_avant_apres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Période  N  Moyenne Médiane  Min  Max Ecart_Type Erreur_Standard
1   Avant 43 5.954651    6.03 3.71 7.76  0.9589189       0.1462338
2   Après 43 4.862791    4.85 1.67 7.71  1.2076449       0.1841641</code></pre>
</div>
</div>
</section>
<section id="test-t-pour-échantillon-dépendants" class="level3">
<h3 class="anchored" data-anchor-id="test-t-pour-échantillon-dépendants">Test-T pour échantillon dépendants</h3>
<p><span class="math display">\[
Y_{11}, Y_{12}, \dots, Y_{1n} : \text{ observations de } Y_1 \text{ dans le 1}^{\text{er}} \text{ échantillon de taille } n.
\]</span></p>
<p><span class="math display">\[
Y_{21}, Y_{22}, \dots, Y_{2n} : \text{ observations de } Y_2 \text{ dans le 2}^{\text{ème}} \text{ échantillon de taille } n.
\]</span></p>
<p><strong>Le cas le plus fréquent :</strong> Les 2 échantillons sont liés aux mêmes individus (données <em>appariées</em>).</p>
<p><strong>Hypothèses du test bidirectionnel :</strong></p>
<p><span class="math display">\[
H₀ : \mu_{\text{avant}} = \mu_{\text{après}}
\]</span></p>
<p><span class="math display">\[
H₁ : \mu_{\text{avant}} \neq \mu_{\text{après}}
\]</span></p>
<p>Puisque les données sont <strong>appariées</strong>, on peut former une paire d’observations<br>
pour chaque individu et travailler seulement sur les différences :</p>
<p><span class="math display">\[
D_i = Y_{1i} - Y_{2i}
\]</span></p>
<p>C’est comme si on définit directement <strong>une nouvelle variable (D)</strong> correspondant à la différence :</p>
<p><span class="math display">\[
D_i = Y_{1} - Y_{2}
\]</span></p>
<p>et qu’on teste la moyenne de cette variable : <span class="math display">\[\mu_D = \mu_1 - \mu_2\]</span></p>
<p>À l’aide de la moyenne des différences observées sur les ( n ) individus :</p>
<p><span class="math display">\[
\overline{D} = \frac{\sum_{i=1}^{n} D_i}{n}
\]</span></p>
<p><strong>Hypothèses :</strong></p>
<p><span class="math display">\[
H₀ : \mu_D = 0 \quad (\mu_1 - \mu_2 = 0) \quad \quad H₁ : \mu_D \neq 0 \quad (\mu_1 - \mu_2 \neq 0)
\]</span></p>
<p><strong>Statistique du test :</strong></p>
<p><span class="math display">\[
T = \frac{\overline{D}}{S_D / \sqrt{n}}
\]</span></p>
<p>SD correspond à l’écart type des différences observées.<br>
Si H₀ est vraie, T suit une loi de Student à n-1 degrés de liberté.</p>
<p><strong>Intervalle de confiance :</strong></p>
<p><span class="math display">\[
\overline{D} \pm t_{\alpha/2} \frac{S_D}{\sqrt{n}}
\]</span></p>
<p><strong>R : Utiliser la commande t.test() avec l’argument paired = TRUE</strong></p>
<p><em>Remarque :</em> Il est également possible de faire un test sur la variable ( D ).</p>
<p><strong>R : Utiliser la commande <code>t.test()</code></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test t de Student apparié pour comparer les moyennes Avant et Après  </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mobilisation<span class="sc">$</span>avant, mobilisation<span class="sc">$</span>apres, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  mobilisation$avant and mobilisation$apres
t = 4.6, df = 42, p-value = 3.858e-05
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.6128471 1.5708738
sample estimates:
mean difference 
        1.09186 </code></pre>
</div>
</div>
<p>Différence moyenne observée = 5.9547-4.8628 = 1.09186</p>
<ul>
<li><p>Le score de satisfaction moyen avant la grossesse est de 1.09 supérieur en moyenne au score de satisfaction moyen après le congé de maternité.</p></li>
<li><p>On estime au NC 95% que le score de satisfaction moyen avant la grossesse est de 0.612 à 1.57 supérieur en moyenne au score de satisfaction moyen après le congé de maternité dans la population considérée.</p></li>
</ul>
<p><code>Question:</code> Quelles sont les implications managériales de ce résultat dans ce contexte?</p>
</section>
<section id="conditions-dutilisation-du-test-t-pour-données-appariées-et-de-lintervalle-de-confiance" class="level3">
<h3 class="anchored" data-anchor-id="conditions-dutilisation-du-test-t-pour-données-appariées-et-de-lintervalle-de-confiance">Conditions d’utilisation du Test-T pour données appariées et de l’intervalle de confiance</h3>
<ul>
<li><p>Si n est « petit », la distribution de la <strong>variable D</strong> (différence Y₁ - Y₂) dans la population de référence doit s’approcher d’une loi normale.</p></li>
<li><p>Si n est assez grand, le test demeure valide même si la variable D n’est pas normalement distribuée dans la population de référence.</p></li>
<li><p>Tout comme le Test-T pour échantillons indépendants, le Test-T pour données appariées est sensible à la <strong>présence de valeurs extrêmes.</strong></p></li>
</ul>
<p><strong>Mise en garde! Attention, ici on parle toujours des différences Dᵢ</strong> <strong>et non des variables prises individuellement.</strong></p>
</section>
<section id="test-non-paramétriques-pour-les-données-appariées" class="level3">
<h3 class="anchored" data-anchor-id="test-non-paramétriques-pour-les-données-appariées">Test non-paramétriques pour les données appariées</h3>
<p>Il existe deux alternatives au Test-T pour données appariées dans le cas de petits échantillons :<br>
1. Le test du signe<br>
2. Le test de Wilcoxon des rangs signés (WRS)</p>
<section id="test-du-signe-basé-sur-la-différence-dy₁---y₂" class="level4">
<h4 class="anchored" data-anchor-id="test-du-signe-basé-sur-la-différence-dy₁---y₂"><strong>1. Test du signe :</strong> Basé sur la différence D=Y₁ - Y₂</h4>
<p><strong>Hypothèses :</strong></p>
<p><span class="math display">\[
H₀ : \text{médiane } D = 0 \quad \quad H₁ : \text{médiane } D \neq 0
\]</span></p>
<p><strong>Statistique du test :</strong> S = nombre de différences Dᵢ positives <em>(les</em> Dᵢ<em>= Y1i - Y2i sont les différences observées)</em></p>
<p>Si H₀ est vraie : S: Binomiale (n, 1/2)</p>
<p><em>(s’il n’y a pas de différence nulle)</em></p>
<p><span class="math display">\[
\text{et } Z = \frac{S - E(S)}{\sqrt{\text{Var}(S)}} \text{ approximativement N(0,1)}
\]</span></p>
<p>Remarque : On doit omettre les différences nulles pour calculer S et corriger le ‘’n’’ en conséquence.<br>
</p>
<p><strong>Réaliser le test du signe sur R:</strong></p>
<ul>
<li><p>Calculer les différences entre les paires de données</p></li>
<li><p>Compter le nombre de valeurs positives et négatives</p></li>
<li><p>Utiliser la fonction binom.test() pour effectuer un test binomial</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les différences entre Avant et Après</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a> differences <span class="ot">&lt;-</span> mobilisation<span class="sc">$</span>apres <span class="sc">-</span> mobilisation<span class="sc">$</span>avant</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a> <span class="co"># Afficher les différences</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">print</span>(differences)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0.19  1.87 -4.67 -1.30  0.02 -0.97  0.19 -2.33  0.08 -1.97 -1.79 -2.45
[13] -0.73  0.77 -1.66 -0.76 -2.99 -0.83 -1.23  1.92 -1.54 -0.45 -0.64  1.10
[25] -1.44  0.79 -1.97 -3.83  0.72 -0.06  0.15 -3.85 -0.27 -1.47 -3.50 -4.27
[37] -0.85 -0.33 -2.56  0.16 -1.55 -0.91 -1.74</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># Compter le nombre de différences positives, négatives et nulles</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a> diff_positif <span class="ot">&lt;-</span> <span class="fu">sum</span>(differences <span class="sc">&gt;</span> <span class="dv">0</span>)  </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a> diff_negatif <span class="ot">&lt;-</span> <span class="fu">sum</span>(differences <span class="sc">&lt;</span> <span class="dv">0</span>)  </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a> diff_nul <span class="ot">&lt;-</span> <span class="fu">sum</span>(differences <span class="sc">==</span> <span class="dv">0</span>)     </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a> <span class="co"># Afficher les fréquences des différences </span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">cat</span>(<span class="st">"apres &lt; avant :"</span>, diff_negatif, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>apres &lt; avant : 31 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">cat</span>(<span class="st">"apres &gt; avant :"</span>, diff_positif, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>apres &gt; avant : 12 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">cat</span>(<span class="st">"apres = avant :"</span>, diff_nul, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>apres = avant : 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># Appliquer le test des signes</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">binom.test</span>(<span class="at">x =</span> diff_positif, <span class="at">n =</span> diff_positif <span class="sc">+</span> diff_negatif, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  diff_positif and diff_positif + diff_negatif
number of successes = 12, number of trials = 43, p-value = 0.005402
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.1532892 0.4366870
sample estimates:
probability of success 
             0.2790698 </code></pre>
</div>
</div>
</section>
<section id="test-de-wilcoxon-des-rangs-signés-wrs" class="level4">
<h4 class="anchored" data-anchor-id="test-de-wilcoxon-des-rangs-signés-wrs"><strong>2. Test de Wilcoxon des rangs signés (WRS)</strong></h4>
<p>Pour chaque différence observée ( Dᵢ ), on définit :</p>
<p><span class="math display">\[
\varphi_i =
\begin{cases}
1 \quad \text{si } D_i &gt; 0 \\
0 \quad \text{si } D_i &lt; 0
\end{cases}
\]</span></p>
<p><span class="math display">\[
| D_i | : \text{ valeur absolue de la différence } \quad (\text{distance entre la différence et « 0 »})
\]</span></p>
<p><span class="math display">\[
R_i : \text{ rang de } | D_i |
\]</span></p>
<p>Remarque :</p>
<p>Tout comme pour le test du signe, on doit omettre les différences nulles et corriger ( n ) en conséquence. De plus, tout comme dans le test MWW, en présence de rangs ex æquo, on utilise le rang moyen.</p>
<p>Statistique du test :</p>
<p><span class="math display">\[
W^+ = \sum_{i=1}^{n} \varphi_i R_i
\]</span></p>
<p><span class="math display">\[
\text{ Si H₀ est vraie: }  Z = \frac{W^+ - E(W^+)}{\sqrt{\text{Var}(W^+)}}\text{ approximativement N(0,1)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Wilcoxon Signed Rank pour comparer les scores Avant et Après  </span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(mobilisation<span class="sc">$</span>avant, mobilisation<span class="sc">$</span>apres, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank exact test

data:  mobilisation$avant and mobilisation$apres
V = 793, p-value = 4.956e-05
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</section>
</section>
<section id="comparaison-entre-test-t-pour-données-appariées-test-du-signe-et-test-wrs" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-entre-test-t-pour-données-appariées-test-du-signe-et-test-wrs">Comparaison entre Test-T pour données appariées, test du signe et test WRS</h3>
<ul>
<li><p><strong>Le Test-T pour données appariées</strong> est le plus « puissant » des trois tests lorsque la distribution de la différence D s’approche d’une loi normale. Cette optimalité de la puissance disparaît au fur et à mesure qu’on s’éloigne de la normalité <em>si la taille des échantillons est petite</em>. De plus, il est très sensible aux valeurs extrêmes.</p></li>
<li><p><strong>Le test WRS</strong> est moins sensible aux valeurs extrêmes et peut aussi bien s’utiliser pour des variables quantitatives que des données ordinales. Dans bien des cas, il pourra être plus puissant que le test t pour données appariées.</p></li>
<li><p><strong>Le test du signe</strong> peut aussi s’utiliser sur des données quantitatives ou ordinales. Il est le moins puissant des trois tests, sauf en présence de nombreuses valeurs extrêmes.</p></li>
</ul>
</section>
<section id="comparaison-de-2-proportions-échantillons-dépendants" class="level3">
<h3 class="anchored" data-anchor-id="comparaison-de-2-proportions-échantillons-dépendants">Comparaison de 2 proportions (échantillons dépendants)</h3>
<p><strong>Mise en situation 4</strong></p>
<p>Vérifier l’impact d’un test de goût sur l’intérêt envers un produit.</p>
<p><strong>Méthodologie</strong></p>
<p>Avant le test de goût, les sujets devaient répondre oui ou non à la question : « Êtes-vous intéressé par l’achat de ce produit ? ». Les mêmes individus devaient répondre à la même question après le test.</p>
<p><strong>Échantillon</strong></p>
<p>200 individus</p>
<p><strong>Variables</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les variables et descriptions</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nom_Variable =</span> <span class="fu">c</span>(<span class="st">"Avant"</span>,<span class="st">"Après"</span>),</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(<span class="st">"l’individu est intéressé à acheter le produit avant le test de goût (avant=1 si oui et avant=0 si non)"</span>, <span class="st">"l’individu est intéressé à acheter le produit après le test de goût (après=1 si oui et après=0 si non)"</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le tableau</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(variables, <span class="at">format =</span> <span class="st">"pipe"</span>, <span class="at">align =</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nom_Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Avant</td>
<td style="text-align: left;">l’individu est intéressé à acheter le produit avant le test de goût (avant=1 si oui et avant=0 si non)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Après</td>
<td style="text-align: left;">l’individu est intéressé à acheter le produit après le test de goût (après=1 si oui et après=0 si non)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Le fichier « Test_de_goût.csv » contient des données de cet exemple.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définir le répertoire de travail  </span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Fatou/OneDrive - HEC Montréal/PROJET SUPERVISE/Data"</span>)  </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Importer les données</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a> gout <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Test_de_goût.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir les variables apres et avant en facteurs </span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>gout<span class="sc">$</span>apres <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(gout<span class="sc">$</span>apres)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>gout<span class="sc">$</span>avant <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(gout<span class="sc">$</span>avant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="test-du-mcnemar" class="level3">
<h3 class="anchored" data-anchor-id="test-du-mcnemar">Test du McNemar</h3>
<p><strong>Hypothèses du test :</strong></p>
<p><span class="math display">\[
H₀ : p_1 = p_2 \quad \quad H₁ : p_1 \neq p_22
\]</span></p>
<p>Le test est basé sur les effectifs observés dans chaque catégorie.</p>
<p><span class="math display">\[
\begin{array}{c|cc}
   &amp; 0 &amp; 1 \\
  \hline
  0 &amp; {n}_{11} &amp; {n}_{12} \\
  1 &amp; {n}_{21} &amp; {n}_{22} \\
\end{array}
\]</span></p>
<p><strong>Statistique du test dans R</strong></p>
<p><span class="math display">\[
Z^2 = \frac{( | n_{12} - n_{21} | - 1 )^2}{n_{12} + n_{21}}
\]</span></p>
<p>Si H₀ est vraie et les échantillons assez grands, Z² suit approximativement une loi Khi-deux (Chi-Square).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un tableau de contingence pour comparer les réponses Avant et Après </span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>table_mcnemar <span class="ot">&lt;-</span> <span class="fu">table</span>(gout<span class="sc">$</span>avant, gout<span class="sc">$</span>apres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger la bibliothèque nécessaire  </span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectuer le test de McNemar pour comparer les réponses Avant et Après </span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(table_mcnemar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test with continuity correction

data:  table_mcnemar
McNemar's chi-squared = 6.4533, df = 1, p-value = 0.01107</code></pre>
</div>
</div>
<p>Intervalle de confiance pour estimer p₁ - p₂ :</p>
<p><span class="math display">\[
(\hat{p}_1 - \hat{p}_2) \pm Z_{\alpha / 2} \sqrt{\frac{\hat{p}_1 (1 - \hat{p}_1) + \hat{p}_2 (1 - \hat{p}_2) - 2 (\hat{p}_{11} \hat{p}_{22} - \hat{p}_{12} \hat{p}_{21})}{n}}
\]</span></p>
<ul>
<li>Les proportions observées dans chaque cellule sont :</li>
</ul>
<p><span class="math display">\[
\begin{array}{c|cc}
   &amp; 0 &amp; 1 \\
  \hline
  0 &amp; \hat{p}_{11} &amp; \hat{p}_{12} \\
  1 &amp; \hat{p}_{21} &amp; \hat{p}_{22} \\
\end{array}
\]</span></p>
<ul>
<li>π̂₁ : proportion observée dans le premier groupe et π̂₂: proportion observée dans le deuxième groupe</li>
<li>Au niveau de confiance 95%</li>
</ul>
<p><span class="math display">\[
(\hat{p}_1 - \hat{p}_2) \pm 1.96 \sqrt{\frac{\hat{p}_1 (1 - \hat{p}_1) + \hat{p}_2 (1 - \hat{p}_2) - 2 (\hat{p}_{11} \hat{p}_{22} - \hat{p}_{12} \hat{p}_{21})}{n}}
\]</span></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->

<div style="margin-top: 40px; display: flex; justify-content: space-between;">
  <a href="t1.html" style="font-size: 18px; text-decoration: none;" aria-label="Leçon précédente">
    ⬅️ Leçon précédente
  </a>
  <a href="t3.html" style="font-size: 18px; text-decoration: none;" aria-label="Leçon suivante">
    Leçon suivante ➡️
  </a>
</div>

</body>
</html>
